export const _as = {
  // nav
  navFeatures: 'বৈশিষ্ট্যসমূহ',
  navOversight: 'নিৰীক্ষণ',
  navSignIn: 'প্ৰৱেশ কৰক',
  // hero
  heroBadge: 'কল্যাণ নীতি বাস্তৱায়ন',
  heroTitle1: 'নিখুঁত শাসন।',
  heroTitle2: 'পুনৰ কল্পনা কৰা।',
  heroSubtitle: 'এটি সুৰক্ষিত, নাগৰিক-প্ৰথম মঞ্চ য\'ত ৰিয়েল-টাইম তথ্য, বিকেন্দ্ৰীভূত পৰিচয় আৰু প্ৰত্যক্ষ স্থানান্তৰণে সঠিক ব্যক্তিলৈ কল্যাণ সুবিধা প্ৰদান কৰে।',
  heroCta: 'আপোনাৰ ডেশ্ববৰ্ডত যাওক',
  // features
  featuresBadge: 'সামৰ্থ্য',
  featuresTitle: 'এটি আধুনিক কল্যাণ ব্যৱস্থায় যি প্ৰয়োজন।',
  featuresSubtitle: 'এটি সংযুক্ত মঞ্চই পৰিচয়, লক্ষ্যবস্তু, পৰিশোধ আৰু জবাবদিহিতাক একীভূত কৰে।',
  tileDynamicRegistries: 'গতিশীল সামাজিক-অৰ্থনৈতিক নিবন্ধন',
  tileDynamicRegistriesDesc: 'কৰ, ইউটিলিটি আৰু অসামৰিক ৰেকৰ্ডৰ পৰা নিৰন্তৰ যোগ্যতা আপডেট — সদায় বাস্তৱতা প্ৰতিফলিত কৰা লক্ষ্যবস্তু, কেতিয়াও পুৰণি জনগণনা নহয়।',
  tileBiometrics: 'বিকেন্দ্ৰীভূত বায়োমেট্ৰিক্স',
  tileBiometricsDesc: 'সুৰক্ষিত, বিকেন্দ্ৰীভূত বায়োমেট্ৰিক পৰিচয় যিয়ে দ্বাৰত পৰিচয় জালিয়াতি আৰু দুবাৰ লাভ বন্ধ কৰে।',
  tileDbt: 'প্ৰত্যক্ষ লাভ স্থানান্তৰণ (DBT)',
  tileDbtDesc: 'নগদ আৰু ভৰ্তুকি সৰাসৰি যাচাইকৃত নাগৰিক হিচাপলৈ — মধ্যস্থতাকাৰী শূন্য।',
  tileConditional: 'চৰ্তসাপেক্ষ স্থানান্তৰণ',
  tileConditionalDesc: 'শিক্ষা আৰু স্বাস্থ্য মাইলৰৰ সৈতে জড়িত পৰিশোধ পৰিমেয় সামাজিক ফলাফলৰ বাবে।',
  tileAudits: 'সম্প্ৰদায় সামাজিক নিৰীক্ষণ',
  tileAuditsDesc: 'জনসাধাৰণৰ সভা য\'ত নাগৰিকে মাটিত থকা সম্পদৰ বিৰুদ্ধে ব্যয় পৰীক্ষা কৰে।',
  tileAi: 'স্বয়ংক্ৰিয় ব্যতিক্ৰম প্ৰতিবেদন',
  tileAiDesc: 'AIয়ে সন্দেহজনক ধৰণ চিহ্নিত কৰে — যেনে এটি ফোন নম্বৰ একাধিক লাভ হিচাপৰ সৈতে যুক্ত — তাৎক্ষণিক তদন্তৰ বাবে।',
  // oversight
  oversightBadge: 'মন্ত্ৰালয় নিৰীক্ষণ',
  oversightTitle: 'মন্ত্ৰালয় কাঠামো আৰু পৰিকাঠামো',
  oversightSubtitle: 'মন্ত্ৰালয়সমূহে আইনী কাঠামো স্থাপন, নিৰীক্ষণ বাজেট বণ্টন, সুৰক্ষিত তথ্য ব্যৱস্থা ৰক্ষণাবেক্ষণ আৰু দণ্ড আৰোপ কৰি কল্যাণ নীতি নিৰীক্ষণ কৰে।',
  pillarAudit: 'বাধ্যতামূলক নিৰীক্ষণ নিৰ্দেশাৱলী',
  pillarAuditDesc: 'মানদণ্ড কাৰ্যপদ্ধতি আৰু আইনী কাঠামো যিয়ে সামাজিক আৰু আৰ্থিক নিৰীক্ষণ বাধ্যতামূলক কৰে।',
  pillarMetrics: 'স্পষ্ট কাৰ্যক্ষমতা মাপকাঠী',
  pillarMetricsDesc: 'পৰিমেয় মানদণ্ড — যেনে খৰ্বতা বা বেকাৰতাত নিৰ্দিষ্ট হ্ৰাস হাৰ।',
  pillarBodies: 'স্বাধীন সংস্থা',
  pillarBodiesDesc: 'ৰাজনৈতিক হস্তক্ষেপৰ বিৰুদ্ধে তৃতীয় পক্ষৰ নিৰীক্ষক আৰু স্থানীয় সামাজিক নিৰীক্ষণ এককৰ বাবে আইনী সুৰক্ষা।',
  pillarDatabases: 'সুৰক্ষিত মাষ্টাৰ ডেটাবেইচ',
  pillarDatabasesDesc: 'পৰিষ্কাৰ তথ্যৰ সৈতে কেন্দ্ৰীয় লাভাৰ্থী নিবন্ধন, কেৱল অনুমোদিত নিৰীক্ষণ সংস্থাৰ বাবে অভিগম্য।',
  // footer
  footerTagline: 'জন-প্ৰথম নীতিৰ বাবে নিখুঁত শাসন।',
  footerSub: 'গতিশীল নিবন্ধন · বিকেন্দ্ৰীভূত বায়োমেট্ৰিক্স · প্ৰত্যক্ষ লাভ স্থানান্তৰণ',
  // login
  loginTitle: 'স্বাগতম',
  loginSubtitle: 'আপোনাৰ সুৰক্ষিত নাগৰিক ডেশ্ববৰ্ড অভিগম কৰিবলৈ প্ৰৱেশ কৰক। নতুন নাগৰিক দুই মিনিটৰ ভিতৰত অন্তৰ্ভুক্ত হয়।',
  loginContinueGoogle: 'Googleৰে চলি থাকক',
  loginContinueDemo: 'ডেমো হিচাপৰে চলি থাকক',
  loginDemoHint: 'ডেমো হিচাপ',
  loginPresetLabel: 'এজন ডেমো নাগৰিক দ্ৰুত পূৰণ কৰক:',
  loginOrUse: 'অথবা আপোনাৰ বিৱৰণ ব্যৱহাৰ কৰক',
  loginEmail: 'ই-মেইল',
  loginName: 'নাম',
  loginImage: 'ছবি URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'আপোনাৰ Aadhaar যাচাই কৰক',
  verifySubtitle: 'একবাৰীয়া পৰিচয় যাচাইকৰণে আপোনাৰ কল্যাণ ডেশ্ববৰ্ড উন্মোচন কৰে।',
  verifyAadhaarLabel: '১২-অঙ্কৰ Aadhaar নম্বৰ',
  verifyMobileLabel: 'OTP লাভ কৰিবলৈ মোবাইল নম্বৰ',
  verifyGenerateOtp: 'OTP সৃষ্টি কৰক',
  verifySendingOtp: 'OTP পঠিয়াই থকা হৈছে…',
  verifyDemoNote: 'ডেমো মোড — OTP অনুৰোধটো অনুকৰণ কৰা হৈছে। কোনো প্ৰকৃত Aadhaar তথ্য প্ৰেৰণ কৰা নহয়।',
  verifyOtpSentTo: 'OTP আপোনাৰ ৰেজিষ্টাৰ্ড মোবাইল নম্বৰলৈ পঠোৱা হৈছে',
  verifyDemoOtpLabel: 'ডেমো OTP:',
  verifyDemoOtpNote: 'প্ৰকৃত বিয়োগে এইটো SMSৰে পঠিয়ায় — পৰীক্ষাৰ বাবে এতিয়া দেখুওৱা হৈছে।',
  verifyOtpLabel: '৬-অঙ্কৰ OTP',
  verifyVerifyOtp: 'OTP যাচাই কৰক',
  verifyVerifying: 'যাচাই কৰি থকা হৈছে…',
  verifyChangeAadhaar: 'Aadhaar নম্বৰ সলনি কৰক',
  verifyIdentityVerified: 'পৰিচয় যাচাই কৰা হৈছে',
  verifyRedirecting: 'আপোনাৰ ডেশ্ববৰ্ডলৈ পুনৰ নিৰ্দেশিত কৰি থকা হৈছে…',
  verifyInvalidAadhaar: 'অনুগ্ৰহ কৰি এটি বৈধ ১২-অঙ্কৰ Aadhaar নম্বৰ লিখক।',
  verifyInvalidOtp: 'অনুগ্ৰহ কৰি আপোনাৰ ফোনলৈ পঠোৱা ৬-অঙ্কৰ OTP লিখক।',
  verifyInvalidMobile: 'অনুগ্ৰহ কৰি এটি বৈধ ১০-অঙ্কৰ মোবাইল নম্বৰ লিখক।',
  verifyFailedGenerate: 'OTP সৃষ্টি কৰিবলৈ বিফল।',
  verifyFailedVerify: 'যাচাইকৰণ বিফল। অনুগ্ৰহ কৰি পুনৰ চেষ্টা কৰক।',
  verifySpeakHint: 'মাইকত টিপ কৰক আৰু আপোনাৰ Aadhaar বা OTP কওক',
  // dashboard
  dashWelcome: 'স্বাগতম',
  dashCitizen: 'নাগৰিক',
  dashVerified: 'যাচাইকৰণ অৱস্থা: যাচাই কৰা হৈছে',
  dashPending: 'যাচাইকৰণ অৱস্থা: মুল্যায়নাধীন',
  dashVerifyAadhaar: 'Aadhaar যাচাই কৰক',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'প্ৰৱেশমুক্ত কৰক',
  dashFoodSubsidy: 'খাদ্য ভৰ্তুকি (PDS)',
  dashDbt: 'প্ৰত্যক্ষ লাভ স্থানান্তৰণ',
  dashEducation: 'শিক্ষা অনুদান',
  dashHealth: 'স্বাস্থ্য সুৰক্ষা',
  dashNotEnrolled: 'নামভৰ্তি নহয়',
  dashNextSocialAudit: 'পৰৱৰ্তী সামাজিক নিৰীক্ষণ',
  dashSocialAuditDesc: 'আপোনাৰ গাওঁৰ ৰাজহুৱা ব্যয় পৰ্যালোচনা — সকলো বাসিন্দাৰ বাবে মুকলি।',
  // admin
  adminAccess: 'প্ৰশাসক অভিগম',
  adminOversightPortal: 'মন্ত্ৰালয় নিৰীক্ষণ প\'ৰ্টেল',
  adminAccessPassword: 'অভিগম পাছৱাৰ্ড',
  adminEnterPortal: 'প\'ৰ্টেলত প্ৰৱেশ কৰক',
  adminIncorrect: 'অশুদ্ধ পাছৱাৰ্ড। পুনৰ চেষ্টা কৰক।',
  adminDemoPassword: 'ডেমো পাছৱাৰ্ড:',
  adminRegistration: 'চৰকাৰী ৰেজিষ্ট্ৰেশন',
  adminRegisterDesc: 'অভিযোগ ডেশ্ববৰ্ড অভিগম কৰিবলৈ আপোনাৰ নিৰীক্ষণ ভূমিকা ৰেজিষ্টাৰ কৰক।',
  adminFullName: 'পূৰ্ণ নাম',
  adminEmail: 'চৰকাৰী ই-মেইল',
  adminPhone: 'ফোন',
  adminPosition: 'পদ',
  adminState: 'ৰাজ্য',
  adminDistrict: 'জিলা',
  adminSelectState: 'ৰাজ্য নিৰ্বাচন কৰক',
  adminSelectDistrict: 'জিলা নিৰ্বাচন কৰক',
  adminRegisterContinue: 'ৰেজিষ্টাৰ কৰক আৰু চলি থাকক',
  adminOversightDashboard: 'নিৰীক্ষণ ডেশ্ববৰ্ড',
  adminGrievanceIntelligence: 'অভিযোগ গোচৰ বুদ্ধিমত্তা',
  adminAllDistricts: 'সকলো জিলা',
  adminExit: 'প্ৰস্থান',
  adminStatusDistribution: 'অৱস্থা বিতৰণ',
  adminByCategory: 'শ্ৰেণী অনুসৰি অভিযোগ',
  adminDistrictBreakdown: 'জিলা বিৱৰণ',
  adminRecentGrievances: 'সাম্প্ৰতিক অভিযোগ',
  adminTotalGrievances: 'মুঠ অভিযোগ',
  adminOpen: 'মুকলি',
  adminNoGrievances: 'এই দৃশ্যত কোনো অভিযোগ নাই।',
  adminAiSummary: 'AI বিষয় সাৰাংশ',
  adminAiNone: 'এই দৃশ্যত কোনো অভিযোগ ৰেকৰ্ড কৰা হোৱা নাই।',
  adminPosDm: 'জিলা মেজিষ্ট্ৰেট',
  adminPosBdo: 'ব্লক উন্নয়ন বিষয়া',
  adminPosPanchayat: 'পঞ্চায়ত সচিব',
  adminPosWelfare: 'কল্যাণ বিষয়া',
  adminPosAudit: 'সামাজিক নিৰীক্ষণ সমন্বয়ক',
  adminPosState: 'ৰাজ্য নোডেল বিষয়া',
  adminPosManager: 'কাৰ্যসূচী ব্যৱস্থাপক',
  // common
  commonSubmit: 'দাখিল কৰক',
  commonCancel: 'বাতিল কৰক',
  commonLoading: 'ল\'ড কৰি থকা হৈছে…',
}
