export const _brx = {
  // nav
  navFeatures: 'बिसेफोर',
  navOversight: 'निरीक्षण',
  navSignIn: 'सानथाइ',
  // hero
  heroBadge: 'हाजतियारि नीति बासायनाय',
  heroTitle1: 'सुथायारि निरीक्षण।',
  heroTitle2: 'नव सोमाजायनाय।',
  heroSubtitle: 'मोनसेआरो सिगाथिं खौरांगखौ सुरक्षित बिफान जाया रियल-टाइम डाटा, डिसेन्ट्रलाइज्ड आइडेन्टिटि आरो सिधा ट्रान्सफारखौ हाजतियारि सुविधा जाया थागै मोनसेनि सायाव हायाया।',
  heroCta: 'नुंनि Dashboard खौ हायो',
  // features
  featuresBadge: 'गुणफोर',
  featuresTitle: 'आधुनिक हाजतियारि बिफानखौ लायोदोंमोन सोलायदों।',
  featuresSubtitle: 'गोथाव आरो सानगिजा बिफानखौ आइडेन्टिटि, टारगेटिङ, पेमेन्ट आरो जबाबदायिखि गोथावनायो।',
  tileDynamicRegistries: 'डाइनामिक सोसियोइकोनमिक रेजिस्ट्रि',
  tileDynamicRegistriesDesc: 'ट्याक्स, उटिलिटि आरो सिभिल रेकर्डफोरिनि थिंगाव समय समयनि थाखाय एलिजिबिलिटि अपडेट — जाया टारगेटिङखौ सुथायारि समयखौ फिन्नायो, गोबां समयनि सेन्सस नआ।',
  tileBiometrics: 'डिसेन्ट्रलाइज्ड बायोमेट्रिक्स',
  tileBiometricsDesc: 'सुरक्षित आरो डिसेन्ट्रलाइज्ड बायोमेट्रिक आइडि जाया आइडेन्टिटि फ्रड आरो डबल-डिप्पिङखौ दुआरनि गेदेराव थांवायो।',
  tileDbt: 'सिधा सुविधा ट्रान्सफार (DBT)',
  tileDbtDesc: 'क्यास आरो सब्सिडि सुरक्षित मोनसे खातानि भितर सिधा रांखां — गिजिराव थांनाय मोनसे नङा।',
  tileConditional: 'कन्डिसनल ट्रान्सफार',
  tileConditionalDesc: 'एजुकेसन आरो हेल्थ माइलस्टोननि सायाव जोर दिहुनाय पेमेन्टफोर जाया माप लायनाय सोसियल आउटकमखौ हायो।',
  tileAudits: 'कमिउनिटि सोसियल अडिट',
  tileAuditsDesc: 'पब्लिक एसेम्ब्लि जाया मोनसेफोरा खर्च खौ ग्राउन्डनि एसेटनि बिरुद्ध खोलायो।',
  tileAi: 'अटोमेटेड एक्सेप्सन रिपार्ट',
  tileAiDesc: 'AI नं बिथांग हांखोखौ फ्ल्याग खालामो — जायाव गोथाव सेलफोन नम्बारखौ बेसेबि बेनिफिट खातानि सायाव जोड़ दिहुनाय खालामो — तरुंखौ इन्भेस्टिगेसननि थाखाय।',
  // oversight
  oversightBadge: 'मन्त्रालय निरीक्षण',
  oversightTitle: 'मन्त्रालय फ्रेमवर्क आरो इन्फ्रास्ट्रक्चर',
  oversightSubtitle: 'मन्त्रालयफोरा हाजतियारि नीति अडिटखौ निरीक्षण खालामो जाया लिगल फ्रेमवर्क, निरीक्षण बजेट बांशों, सुरक्षित डाटा बिफान मायो आरो पेनाल्टि मानायो।',
  pillarAudit: 'मेन्डेटरि अडिट गाइडलाइन',
  pillarAuditDesc: 'स्ट्यान्डार्ड अपरेटिङ प्रोसिजर आरो लिगल फ्रेमवर्क जाया सोसियल आरो फाइनान्सियल अडिटखौ मेन्डेटरि खालामो।',
  pillarMetrics: 'स्पस्ट परफरमेन्स मेट्रिक',
  pillarMetricsDesc: 'माप लायनाय बेन्चमार्क — जायाव स्टेन्टिङ आरो बेरोजगारि बांसिनि स्पस्ट रिडक्सन रेट।',
  pillarBodies: 'इन्डिपेन्डेन्ट बडि',
  pillarBodiesDesc: 'थर्ड-पार्टि अडिटर आरो लोकल सोसियल अडिट युनिटनि थाखाय पोलिटिकल इन्टरफियरेन्सनि बिरुद्ध लिगल सेफगार्ड।',
  pillarDatabases: 'सुरक्षित मास्टर डाटाबेस',
  pillarDatabasesDesc: 'सिदिङा बेनिफिसियरी रेजिस्ट्रि सुथायारि डाटा होंवा, अधिकृत अडिट एजेन्सिनि खालाय सायाव मात्र।',
  // footer
  footerTagline: 'मोनसेआरो सिगाथिं नीतिनि थाखाय सुथायारि निरीक्षण।',
  footerSub: 'डाइनामिक रेजिस्ट्रि · डिसेन्ट्रलाइज्ड बायोमेट्रिक्स · सिधा सुविधा ट्रान्सफार',
  // login
  loginTitle: 'नुंखौ बानफिनो',
  loginSubtitle: 'नुंनि सुरक्षित मोनसे ड्यासबार्ड खौ हायोखौ सानथाइ। गोदान मोनसेफोरखौ दुइ मिनिटनि उनाव रेजिस्टर खालामनाय जायो।',
  loginContinueGoogle: 'Google होनाय',
  loginContinueDemo: 'Demo Account होनाय',
  loginDemoHint: 'Demo Account',
  loginPresetLabel: 'Demo मोनसेखौ तेज्यायो खालामो:',
  loginOrUse: 'आरो नुंनि विवरण खौ बेबारायो',
  loginEmail: 'Email',
  loginName: 'मुं',
  loginImage: 'Image URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'नुंनि Aadhaar खौ भेरिफाइ खालामो',
  verifySubtitle: 'एक बारनि आइडेन्टिटि भेरिफिकेसन नुंनि हाजतियारि ड्यासबार्ड खौ उन्लक खालामो।',
  verifyAadhaarLabel: '12-अंक Aadhaar नम्बार',
  verifyMobileLabel: 'OTP खौ रायखां मोबाइल नम्बार',
  verifyGenerateOtp: 'OTP जनारेट खालामो',
  verifySendingOtp: 'OTP थांवाय…',
  verifyDemoNote: 'Demo मडनं — OTP सोमोनखौ सिमुलेट खालामनाय जायो। बास्तब Aadhaar डाटा नं थांवाय जाया नङा।',
  verifyOtpSentTo: 'OTP नुंनि रेजिस्टार्ड मोबाइल नम्बारनि सायाव थांवायजायो',
  verifyDemoOtpLabel: 'Demo OTP:',
  verifyDemoOtpNote: 'बास्तब डिप्लयमेन्ट आया नं SMS नि थिंगाव थांवायो — टेस्टिङनि थाखाय निजायाव खालामनाय जायो।',
  verifyOtpLabel: '6-अंक OTP',
  verifyVerifyOtp: 'OTP भेरिफाइ खालामो',
  verifyVerifying: 'भेरिफाइ खालाम…',
  verifyChangeAadhaar: 'Aadhaar नम्बार खौ बदलो',
  verifyIdentityVerified: 'आइडेन्टिटि भेरिफाइ जानाय',
  verifyRedirecting: 'नुंनि ड्यासबार्डनि सायाव रिडिरेक्ट खालाम…',
  verifyInvalidAadhaar: 'मोनसे सुथायारि 12-अंक Aadhaar नम्बार सायो।',
  verifyInvalidOtp: 'नुंनि फोननि थिंगाव थांवाय 6-अंक OTP खौ सायो।',
  verifyInvalidMobile: 'मोनसे सुथायारि 10-अंक मोबाइल नम्बार सायो।',
  verifyFailedGenerate: 'OTP जनारेट खालामदोंमोन।',
  verifyFailedVerify: 'भेरिफिकेसन बायफेल जालांगो। आबाय फिन्नाय।',
  verifySpeakHint: 'माइक खौ ट्याप खालामो आरो नुंनि Aadhaar आरो OTP खौ बुङो',
  // dashboard
  dashWelcome: 'बानफिनो',
  dashCitizen: 'मोनसे',
  dashVerified: 'भेरिफिकेसन स्थिति: भेरिफाइ जानाय',
  dashPending: 'भेरिफिकेसन स्थिति: पेन्डिङ',
  dashVerifyAadhaar: 'Aadhaar भेरिफाइ खालामो',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'बाहागो',
  dashFoodSubsidy: 'फुड सब्सिडि (PDS)',
  dashDbt: 'सिधा सुविधा ट्रान्सफार (DBT)',
  dashEducation: 'एजुकेसन ग्रान्ट',
  dashHealth: 'हेल्थ कभरेज',
  dashNotEnrolled: 'एन्रोल नङा',
  dashNextSocialAudit: 'गिबि सोसियल अडिट',
  dashSocialAuditDesc: 'नुंनि गावनि पब्लिक खर्च रिभ्यु — थागै बासिनि थाखाय खुला।',
  // admin
  adminAccess: 'Admin Access',
  adminOversightPortal: 'मन्त्रालय निरीक्षण पोर्टल',
  adminAccessPassword: 'Access password',
  adminEnterPortal: 'Portal खौ हायो',
  adminIncorrect: 'बायदों पासवर्ड। आबाय फिन्नाय।',
  adminDemoPassword: 'Demo password:',
  adminRegistration: 'अफिसियल रेजिस्ट्रेसन',
  adminRegisterDesc: 'ग्रिभेन्स ड्यासबार्ड खौ हायोखौ नुंनि निरीक्षण जायगा खौ रेजिस्टर खालामो।',
  adminFullName: 'मुंथाय',
  adminEmail: 'अफिसियल Email',
  adminPhone: 'फोन',
  adminPosition: 'जायगा',
  adminState: 'राज्य',
  adminDistrict: 'जिला',
  adminSelectState: 'राज्य खौ बाछायो',
  adminSelectDistrict: 'जिला खौ बाछायो',
  adminRegisterContinue: 'रेजिस्टर खालामो आरो जारिमिथियो',
  adminOversightDashboard: 'निरीक्षण ड्यासबार्ड',
  adminGrievanceIntelligence: 'ग्रिभेन्स इन्टेलिजेन्स',
  adminAllDistricts: 'थागै जिलाफोर',
  adminExit: 'बाहागो',
  adminStatusDistribution: 'स्थिति बितरण',
  adminByCategory: 'क्याटेगरि हादोरसायाव ग्रिभेन्सफोर',
  adminDistrictBreakdown: 'जिला ब्रेकडाउन',
  adminRecentGrievances: 'गिबि ग्रिभेन्सफोर',
  adminTotalGrievances: 'थाम ग्रिभेन्स',
  adminOpen: 'खुला',
  adminNoGrievances: 'नि भ्युनि भितर ग्रिभेन्स नङा।',
  adminAiSummary: 'AI टपिक समरि',
  adminAiNone: 'नि भ्युनि थाखाय ग्रिभेन्स रेकर्ड नङा।',
  adminPosDm: 'जिला म्याजिस्ट्रेट',
  adminPosBdo: 'ब्लक डेभेलपमेन्ट अफिसर',
  adminPosPanchayat: 'पञ्चायत सेक्रेटरि',
  adminPosWelfare: 'हाजतियारि अफिसर',
  adminPosAudit: 'सोसियल अडिट कोअर्डिनेटर',
  adminPosState: 'राज्य नडल अफिसर',
  adminPosManager: 'प्रोग्राम म्यानेजर',
  // common
  commonSubmit: 'जमा',
  commonCancel: 'क्यान्सेल',
  commonLoading: 'लडिङ…',
}
