export const _bn = {
  // nav
  navFeatures: 'বৈশিষ্ট্যসমূহ',
  navOversight: 'তত্ত্বাবধান',
  navSignIn: 'সাইন ইন',
  // hero
  heroBadge: 'কল্যাণ নীতি বাস্তবায়ন',
  heroTitle1: 'নিখুঁত শাসন।',
  heroTitle2: 'পুনর্কল্পনা করা হয়েছে।',
  heroSubtitle: 'একটি নিরাপদ, নাগরিক-প্রথম প্ল্যাটফর্ম যেখানে রিয়েল-টাইম ডেটা, বিকেন্দ্রীভূত পরিচয় এবং সরাসরি স্থানান্তর ঠিক সঠিক ব্যক্তিদের কাছে কল্যাণ সুবিধা পৌঁছে দেয়।',
  heroCta: 'আপনার ড্যাশবোর্ড দেখুন',
  // features
  featuresBadge: 'সুবিধাসমূহ',
  featuresTitle: 'একটি আধুনিক কল্যাণ ব্যবস্থার জন্য প্রয়োজনীয় সবকিছু।',
  featuresSubtitle: 'একটি সংযুক্ত প্ল্যাটফর্ম পরিচয়, লক্ষ্যবস্তি নির্ধারণ, পেমেন্ট এবং জবাবদিহিতাকে একত্রিত করে।',
  tileDynamicRegistries: 'গতিশীল সামাজিক-অর্থনৈতিক নিবন্ধন',
  tileDynamicRegistriesDesc: 'কর, বিদ্যুৎ এবং নাগরিক রেকর্ড থেকে ধারাবাহিক যোগ্যতা হালনাগাদ — এমন লক্ষ্যবস্তি নির্ধারণ যা সবসময় বাস্তবতা প্রতিফলিত করে, কোনো পুরনো আদমশুমারি নয়।',
  tileBiometrics: 'বিকেন্দ্রীভূত বায়োমেট্রিক',
  tileBiometricsDesc: 'নিরাপদ, বিকেন্দ্রীভূত বায়োমেট্রিক পরিচয় যা দরজায় পরিচয় জালিয়াতি ও একাধিক সুবিধা গ্রহণ বন্ধ করে।',
  tileDbt: 'সরাসরি সুবিধা স্থানান্তর',
  tileDbtDesc: 'নগদ ও ভর্তুকি সরাসরি যাচাইকৃত নাগরিক অ্যাকাউন্টে পাঠানো হয় — কোনো মধ্যস্বত্বভোগী নেই।',
  tileConditional: 'শর্তসাপেক্ষ স্থানান্তর',
  tileConditionalDesc: 'শিক্ষা ও স্বাস্থ্যের মাইলফলকের সাথে যুক্ত পেআউট যা পরিমাপযোগ্য সামাজিক ফলাফল দেয়।',
  tileAudits: 'সম্প্রদায়িক সামাজিক নিরীক্ষা',
  tileAuditsDesc: 'জনসভা যেখানে নাগরিকরা মাঠপর্যায়ের সম্পদের বিপরীতে ব্যয়ের তদন্ত করে।',
  tileAi: 'স্বয়ংক্রিয় ব্যতিক্রম প্রতিবেদন',
  tileAiDesc: 'AI সন্দেহজনক ধাঁচ চিহ্নিত করে — যেমন একটি ফোন নম্বর একাধিক সুবিধা অ্যাকাউন্টের সাথে যুক্ত — তাৎক্ষণিক তদন্তের জন্য।',
  // oversight
  oversightBadge: 'মন্ত্রণালয় তত্ত্বাবধান',
  oversightTitle: 'মন্ত্রণালয় কাঠামো ও অবকাঠামো',
  oversightSubtitle: 'মন্ত্রণালয়গুলি আইনি কাঠামো প্রতিষ্ঠা, তত্ত্বাবধান বাজেট বরাদ্দ, নিরাপদ ডেটা ব্যবস্থা বজায় রাখা এবং শাস্তি প্রয়োগ করে কল্যাণ নীতি নিরীক্ষা তত্ত্বাবধান করে।',
  pillarAudit: 'বাধ্যতামূলক নিরীক্ষা নির্দেশিকা',
  pillarAuditDesc: 'স্ট্যান্ডার্ড অপারেটিং পদ্ধতি এবং আইনি কাঠামো যা সামাজিক ও আর্থিক নিরীক্ষাকে বাধ্যতামূলক করে।',
  pillarMetrics: 'স্পষ্ট কর্মক্ষমতা মেট্রিক',
  pillarMetricsDesc: 'পরিমাপযোগ্য মাপকাঠি — যেমন খর্বাকৃতি বা বেকারত্বের নির্দিষ্ট হ্রাস হার।',
  pillarBodies: 'স্বাধীন সংস্থা',
  pillarBodiesDesc: 'তৃতীয় পক্ষের নিরীক্ষক ও স্থানীয় সামাজিক নিরীক্ষা ইউনিটের বিরুদ্ধে রাজনৈতিক হস্তক্ষেপ থেকে আইনি সুরক্ষা।',
  pillarDatabases: 'নিরাপদ মাস্টার ডেটাবেস',
  pillarDatabasesDesc: 'কেন্দ্রীয় সুবিধাভোগী নিবন্ধন পরিষ্কার ডেটার সাথে, যা কেবল অনুমোদিত নিরীক্ষা সংস্থার জন্য অ্যাক্সেসযোগ্য।',
  // footer
  footerTagline: 'মানুষ-প্রথম নীতির জন্য নিখুঁত শাসন।',
  footerSub: 'গতিশীল নিবন্ধন · বিকেন্দ্রীভূত বায়োমেট্রিক · সরাসরি সুবিধা স্থানান্তর',
  // login
  loginTitle: 'স্বাগতম',
  loginSubtitle: 'আপনার নিরাপদ নাগরিক ড্যাশবোর্ডে অ্যাক্সেস করতে সাইন ইন করুন। নতুন নাগরিকদের দুই মিনিটের মধ্যে অনবোর্ড করা হয়।',
  loginContinueGoogle: 'Google দিয়ে চালিয়ে যান',
  loginContinueDemo: 'ডেমো অ্যাকাউন্ট দিয়ে চালিয়ে যান',
  loginDemoHint: 'ডেমো অ্যাকাউন্ট',
  loginPresetLabel: 'দ্রুত একটি ডেমো নাগরিক পূরণ করুন:',
  loginOrUse: 'অথবা আপনার বিবরণ ব্যবহার করুন',
  loginEmail: 'ইমেইল',
  loginName: 'নাম',
  loginImage: 'ছবির URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'আপনার Aadhaar যাচাই করুন',
  verifySubtitle: 'একবারের জন্য পরিচয় যাচাইকরণ আপনার কল্যাণ ড্যাশবোর্ড আনলক করে।',
  verifyAadhaarLabel: '১২-অঙ্কের Aadhaar নম্বর',
  verifyMobileLabel: 'OTP পাওয়ার মোবাইল নম্বর',
  verifyGenerateOtp: 'OTP তৈরি করুন',
  verifySendingOtp: 'OTP পাঠানো হচ্ছে…',
  verifyDemoNote: 'ডেমো মোড — OTP অনুরোধ সিমুলেট করা হয়। কোনো বাস্তব Aadhaar ডেটা প্রেরণ করা হয় না।',
  verifyOtpSentTo: 'আপনার নিবন্ধিত মোবাইল নম্বরে OTP পাঠানো হয়েছে',
  verifyDemoOtpLabel: 'ডেমো OTP:',
  verifyDemoOtpNote: 'প্রকৃত ডিপ্লয়মেন্ট এটি SMS-এর মাধ্যমে পাঠায় — পরীক্ষার জন্য এখানে দেখানো হয়েছে।',
  verifyOtpLabel: '৬-অঙ্কের OTP',
  verifyVerifyOtp: 'OTP যাচাই করুন',
  verifyVerifying: 'যাচাই করা হচ্ছে…',
  verifyChangeAadhaar: 'Aadhaar নম্বর পরিবর্তন করুন',
  verifyIdentityVerified: 'পরিচয় যাচাইকৃত',
  verifyRedirecting: 'আপনার ড্যাশবোর্ডে রিডাইরেক্ট করা হচ্ছে…',
  verifyInvalidAadhaar: 'অনুগ্রহ করে একটি বৈধ ১২-অঙ্কের Aadhaar নম্বর লিখুন।',
  verifyInvalidOtp: 'অনুগ্রহ করে আপনার ফোনে প্রেরিত ৬-অঙ্কের OTP লিখুন।',
  verifyInvalidMobile: 'অনুগ্রহ করে একটি বৈধ ১০-অঙ্কের মোবাইল নম্বর লিখুন।',
  verifyFailedGenerate: 'OTP তৈরি করতে ব্যর্থ।',
  verifyFailedVerify: 'যাচাইকরণ ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।',
  verifySpeakHint: 'মাইকে ট্যাপ করুন এবং আপনার Aadhaar বা OTP বলুন',
  // dashboard
  dashWelcome: 'স্বাগতম',
  dashCitizen: 'নাগরিক',
  dashVerified: 'যাচাইকরণ অবস্থা: যাচাইকৃত',
  dashPending: 'যাচাইকরণ অবস্থা: মুলতুবি',
  dashVerifyAadhaar: 'Aadhaar যাচাই করুন',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'সাইন আউট',
  dashFoodSubsidy: 'খাদ্য ভর্তুকি (PDS)',
  dashDbt: 'সরাসরি সুবিধা স্থানান্তর',
  dashEducation: 'শিক্ষা অনুদান',
  dashHealth: 'স্বাস্থ্য কভারেজ',
  dashNotEnrolled: 'নিবন্ধিত নয়',
  dashNextSocialAudit: 'পরবর্তী সামাজিক নিরীক্ষা',
  dashSocialAuditDesc: 'আপনার গ্রামের জনসাধারণের ব্যয় পর্যালোচনা — সব বাসিন্দার জন্য উন্মুক্ত।',
  // admin
  adminAccess: 'অ্যাডমিন অ্যাক্সেস',
  adminOversightPortal: 'মন্ত্রণালয় তত্ত্বাবধান পোর্টাল',
  adminAccessPassword: 'অ্যাক্সেস পাসওয়ার্ড',
  adminEnterPortal: 'পোর্টালে প্রবেশ করুন',
  adminIncorrect: 'ভুল পাসওয়ার্ড। আবার চেষ্টা করুন।',
  adminDemoPassword: 'ডেমো পাসওয়ার্ড:',
  adminRegistration: 'আধিকারিক নিবন্ধন',
  adminRegisterDesc: 'অভিযোগ ড্যাশবোর্ডে অ্যাক্সেস করতে আপনার তত্ত্বাবধান ভূমিকা নিবন্ধন করুন।',
  adminFullName: 'পূর্ণ নাম',
  adminEmail: 'আধিকারিক ইমেইল',
  adminPhone: 'ফোন',
  adminPosition: 'পদ',
  adminState: 'রাজ্য',
  adminDistrict: 'জেলা',
  adminSelectState: 'রাজ্য নির্বাচন করুন',
  adminSelectDistrict: 'জেলা নির্বাচন করুন',
  adminRegisterContinue: 'নিবন্ধন করুন ও চালিয়ে যান',
  adminOversightDashboard: 'তত্ত্বাবধান ড্যাশবোর্ড',
  adminGrievanceIntelligence: 'অভিযোগ ইন্টেলিজেন্স',
  adminAllDistricts: 'সব জেলা',
  adminExit: 'প্রস্থান',
  adminStatusDistribution: 'অবস্থা বিতরণ',
  adminByCategory: 'বিভাগ অনুযায়ী অভিযোগ',
  adminDistrictBreakdown: 'জেলাভিত্তিক বিভাজন',
  adminRecentGrievances: 'সাম্প্রতিক অভিযোগ',
  adminTotalGrievances: 'মোট অভিযোগ',
  adminOpen: 'খোলা',
  adminNoGrievances: 'এই ভিউতে কোনো অভিযোগ নেই।',
  adminAiSummary: 'AI বিষয় সারসংক্ষেপ',
  adminAiNone: 'এই ভিউতে কোনো অভিযোগ রেকর্ড করা হয়নি।',
  adminPosDm: 'জেলা ম্যাজিস্ট্রেট',
  adminPosBdo: 'ব্লক উন্নয়ন আধিকারিক',
  adminPosPanchayat: 'পঞ্চায়েত সচিব',
  adminPosWelfare: 'কল্যাণ আধিকারিক',
  adminPosAudit: 'সামাজিক নিরীক্ষা সমন্বয়ক',
  adminPosState: 'রাজ্য নোডাল আধিকারিক',
  adminPosManager: 'প্রোগ্রাম ম্যানেজার',
  // common
  commonSubmit: 'জমা দিন',
  commonCancel: 'বাতিল করুন',
  commonLoading: 'লোড হচ্ছে…',
}
