export const _doi = {
  // nav
  navFeatures: 'विशेषताएँ',
  navOversight: 'निगरानी',
  navSignIn: 'साइन इन',
  // hero
  heroBadge: 'कल्याण नीति कार्यान्वयन',
  heroTitle1: 'सुनिश्चित शासन।',
  heroTitle2: 'पुनः कल्पना।',
  heroSubtitle: 'एक सुरक्षित, नागरिक-प्राथमिक मंच जित्थे रीयल-टाइम डेटा, विकेंद्रीकृत पहचान, अैड सीधे हस्तांतरण सही लोगां तक कल्याण लाभ पहुंचांदे ने।',
  heroCta: 'अपना डैशबोर्ड खोलो',
  // features
  featuresBadge: 'क्षमताएँ',
  featuresTitle: 'आधुनिक कल्याण प्रणाली जो कुझ लोड़ी हुंदा ए।',
  featuresSubtitle: 'एक जुड़ियां मंच पहचान, लक्ष्यीकरण, भुगतान अैड जवाबदेही नूं एकजुट करदा ए।',
  tileDynamicRegistries: 'गतिशील सामाजिक-आर्थिक रजिस्ट्रियाँ',
  tileDynamicRegistriesDesc: 'टैक्स, उपयोगिता अैड सिविल रिकॉर्डां तों लगातार पात्रता अपडेट — ओह लक्ष्यीकरण जो हमेशा हकीकत दिखांदा ए, कदे वी पुराणा जनगणना नहीं।',
  tileBiometrics: 'विकेंद्रीकृत बायोमेट्रिक्स',
  tileBiometricsDesc: 'सुरक्षित, विकेंद्रीकृत बायोमेट्रिक ID जे द्वारे ते पहचान धोखाधड़ी अैड दोहरी खपत रोकदे ने।',
  tileDbt: 'सीधे लाभ हस्तांतरण',
  tileDbtDesc: 'नकद अैड सब्सिडी सीधे प्रमाणित नागरिक खातेयां विच — कोई विचौलिया नहीं।',
  tileConditional: 'शर्तीय हस्तांतरण',
  tileConditionalDesc: 'शिक्षा अैड स्वास्थ्य मीलस्टोनां नाल जुड़ियां भुगतान, मापयोग सामाजिक नतीजेयां खातिर।',
  tileAudits: 'सामुदायिक सामाजिक लेखा-जोखा',
  tileAuditsDesc: 'लोक सभां जित्थे नागरिक ज़मीनी संपत्ति दे खिलाफ खर्च दी जाँच करदे ने।',
  tileAi: 'स्वचालित अपवाद रिपोर्टां',
  tileAiDesc: 'AI संदिग्ध पैटर्नां नूं चिन्हित करदा ए — जिवें कई लाभ खातेयां नाल जुड़ियां एक फोन नंबर — तुरंत जाँच खातिर।',
  // oversight
  oversightBadge: 'मंत्रालय निगरानी',
  oversightTitle: 'मंत्रालय ढाँचा अैड बुनियादी ढाँचा',
  oversightSubtitle: 'मंत्रालय कानूनी ढाँचे बनां के, निगरानी बजट दे के, सुरक्षित डेटा सिस्टम चलां के अैड जुर्माने लागू कर के कल्याण नीति लेखा-जोखा दी निगरानी करदे ने।',
  pillarAudit: 'अनिवार्य लेखा-जोखा दिशा-निर्देश',
  pillarAuditDesc: 'मानक संचालन प्रक्रियाएँ अैड कानूनी ढाँचे जे सामाजिक अैड वित्तीय लेखा-जोखा नूं अनिवार्य बनांदे ने।',
  pillarMetrics: 'स्पष्ट प्रदर्शन मेट्रिक्स',
  pillarMetricsDesc: 'मापयोग बेंचमार्क — जिवें स्टंटिंग या बेरोजगारी विच विशिष्ट कमी दरां।',
  pillarBodies: 'स्वतंत्र निकाय',
  pillarBodiesDesc: 'तीज-धरी ऑडिटरां अैड स्थानीय सामाजिक लेखा इकाईयां खातिर कानूनी सुरक्षा, राजनीतिक दखलंदाजी दे खिलाफ।',
  pillarDatabases: 'सुरक्षित मास्टर डेटाबेस',
  pillarDatabasesDesc: 'केंद्रीय लाभार्थी रजिस्ट्रियाँ साफ डेटा नाल, जे सिर्फ अधिकृत ऑडिट एजेंसियां दे लेखे ही उपलब्ध ने।',
  // footer
  footerTagline: 'लोक-प्राथमिक नीति खातिर सुनिश्चित शासन।',
  footerSub: 'गतिशील रजिस्ट्रियाँ · विकेंद्रीकृत बायोमेट्रिक्स · सीधे लाभ हस्तांतरण',
  // login
  loginTitle: 'फेर स्वागत ए',
  loginSubtitle: 'अपना सुरक्षित नागरिक डैशबोर्ड खोलन खातिर साइन इन करो। नये नागरिक दो मिनट तों घट्ठ नों दाखिल हुंदे ने।',
  loginContinueGoogle: 'Google नाल जारी रखो',
  loginContinueDemo: 'डेमो अकाउंट नाल जारी रखो',
  loginDemoHint: 'डेमो अकाउंट',
  loginPresetLabel: 'एक डेमो नागरिक तुरंत भरो:',
  loginOrUse: 'या अपने विवरण वर्तो',
  loginEmail: 'ईमेल',
  loginName: 'नाम',
  loginImage: 'इमेज URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'अपना Aadhaar प्रमाणित करो',
  verifySubtitle: 'एक-वार पहचान प्रमाणीकरण तुहाडे कल्याण डैशबोर्ड नूं खोलदा ए।',
  verifyAadhaarLabel: '12-अंकी Aadhaar नंबर',
  verifyMobileLabel: 'OTP प्राप्त करन लेई मोबाइल नंबर',
  verifyGenerateOtp: 'OTP बनाओ',
  verifySendingOtp: 'OTP भेजी जा रही ए…',
  verifyDemoNote: 'डेमो मोड — OTP दी माँग सिमुलेट कीती जांदी ए। कोई असली Aadhaar डेटा नहीं भेजिया जांदा।',
  verifyOtpSentTo: 'OTP तुहाडे रजिस्टर्ड मोबाइल नंबर ते भेजिया गेया',
  verifyDemoOtpLabel: 'डेमो OTP:',
  verifyDemoOtpNote: 'असली डिप्लॉयमेंट इहनूं SMS राहीं भेजदा ए — टेस्टिंग खातिर एथे दिखाया गेया ए।',
  verifyOtpLabel: '6-अंकी OTP',
  verifyVerifyOtp: 'OTP प्रमाणित करो',
  verifyVerifying: 'प्रमाणित कीता जा रहिया ए…',
  verifyChangeAadhaar: 'Aadhaar नंबर बदलो',
  verifyIdentityVerified: 'पहचान प्रमाणित',
  verifyRedirecting: 'तुहाडे डैशबोर्ड ते भेजिया जा रहिया ए…',
  verifyInvalidAadhaar: 'किरपा कर के वैध 12-अंकी Aadhaar नंबर दाखिल करो।',
  verifyInvalidOtp: 'किरपा कर के अपने फोन ते भेजिया 6-अंकी OTP दाखिल करो।',
  verifyInvalidMobile: 'किरपा कर के वैध 10-अंकी मोबाइल नंबर दाखिल करो।',
  verifyFailedGenerate: 'OTP बनाने विच असफल।',
  verifyFailedVerify: 'प्रमाणीकरण असफल। किरपा कर के फेर कोशिश करो।',
  verifySpeakHint: 'माइक दबाओ अैड अपना Aadhaar या OTP बोलो',
  // dashboard
  dashWelcome: 'स्वागत ए',
  dashCitizen: 'नागरिक',
  dashVerified: 'प्रमाणीकरण स्थिति: प्रमाणित',
  dashPending: 'प्रमाणीकरण स्थिति: बाकी',
  dashVerifyAadhaar: 'Aadhaar प्रमाणित करो',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'साइन आउट',
  dashFoodSubsidy: 'भोजन सब्सिडी (PDS)',
  dashDbt: 'सीधा लाभ हस्तांतरण',
  dashEducation: 'शिक्षा ग्रांट',
  dashHealth: 'स्वास्थ्य कवरेज',
  dashNotEnrolled: 'दाखिल नहीं',
  dashNextSocialAudit: 'अगला सामाजिक लेखा-जोखा',
  dashSocialAuditDesc: 'तुहाडे पिंड दा लोक खर्च समीक्षा — सारे रहवासियां खातिर खुल्ला।',
  // admin
  adminAccess: 'एडमिन एक्सेस',
  adminOversightPortal: 'मंत्रालय निगरानी पोर्टल',
  adminAccessPassword: 'एक्सेस पासवर्ड',
  adminEnterPortal: 'पोर्टल विच जाओ',
  adminIncorrect: 'गलत पासवर्ड। फेर कोशिश करो।',
  adminDemoPassword: 'डेमो पासवर्ड:',
  adminRegistration: 'अधिकारिक रजिस्ट्रेशन',
  adminRegisterDesc: 'शिकायत डैशबोर्ड खोलन खातिर अपना निगरानी रोल रजिस्टर करो।',
  adminFullName: 'पूरा नाम',
  adminEmail: 'अधिकारिक ईमेल',
  adminPhone: 'फोन',
  adminPosition: 'पद',
  adminState: 'राज्य',
  adminDistrict: 'ज़िला',
  adminSelectState: 'राज्य चुणो',
  adminSelectDistrict: 'ज़िला चुणो',
  adminRegisterContinue: 'रजिस्टर करो अैड जारी रखो',
  adminOversightDashboard: 'निगरानी डैशबोर्ड',
  adminGrievanceIntelligence: 'शिकायत इंटेलिजेंस',
  adminAllDistricts: 'सारे ज़िले',
  adminExit: 'बाहर जाओ',
  adminStatusDistribution: 'स्थिति वितरण',
  adminByCategory: 'श्रेणी अनुसार शिकायतां',
  adminDistrictBreakdown: 'ज़िला-वार विवरण',
  adminRecentGrievances: 'हालिया शिकायतां',
  adminTotalGrievances: 'कुल शिकायतां',
  adminOpen: 'खुल्लियां',
  adminNoGrievances: 'इस व्यू विच कोई शिकायत नहीं।',
  adminAiSummary: 'AI विषय सारांश',
  adminAiNone: 'इस व्यू खातिर कोई शिकायत दर्ज नहीं।',
  adminPosDm: 'ज़िला मैजिस्ट्रेट',
  adminPosBdo: 'ब्लॉक डेवलपमेंट ऑफिसर',
  adminPosPanchayat: 'पंचायत सचिव',
  adminPosWelfare: 'कल्याण अधिकारी',
  adminPosAudit: 'सामाजिक लेखा समन्वयक',
  adminPosState: 'राज्य नोडल अधिकारी',
  adminPosManager: 'प्रोग्राम मैनेजर',
  // common
  commonSubmit: 'जमा करो',
  commonCancel: 'रद्द करो',
  commonLoading: 'लोड हो रहिया ए…',
}
