export const _en = {
  // nav
  navFeatures: 'Features',
  navOversight: 'Oversight',
  navSignIn: 'Sign in',
  // hero
  heroBadge: 'Welfare Policy Implementation',
  heroTitle1: 'Precision Governance.',
  heroTitle2: 'Reimagined.',
  heroSubtitle: 'A secure, citizen-first platform where real-time data, decentralized identity, and direct transfers deliver welfare benefits to exactly the right people.',
  heroCta: 'Access your dashboard',
  // features
  featuresBadge: 'Capabilities',
  featuresTitle: 'Everything a modern welfare system needs.',
  featuresSubtitle: 'One connected platform unifies identity, targeting, payments, and accountability.',
  tileDynamicRegistries: 'Dynamic Socioeconomic Registries',
  tileDynamicRegistriesDesc: 'Continuous eligibility updates from tax, utility, and civil records — targeting that always reflects reality, never a stale census.',
  tileBiometrics: 'Decentralized Biometrics',
  tileBiometricsDesc: 'Secure, decentralized biometric IDs that stop identity fraud and double-dipping at the door.',
  tileDbt: 'Direct Benefit Transfers',
  tileDbtDesc: 'Cash and subsidies routed straight into verified citizen accounts — zero middlemen.',
  tileConditional: 'Conditional Transfers',
  tileConditionalDesc: 'Payouts tied to education and health milestones for measurable social outcomes.',
  tileAudits: 'Community Social Audits',
  tileAuditsDesc: 'Public assemblies where citizens cross-examine spending against assets on the ground.',
  tileAi: 'Automated Exception Reports',
  tileAiDesc: 'AI flags suspicious patterns — like a single phone number linked to multiple benefit accounts — for instant investigation.',
  // oversight
  oversightBadge: 'Ministry Oversight',
  oversightTitle: 'Ministry Framework and Infrastructure',
  oversightSubtitle: 'Ministries oversee welfare policy audits by establishing legal frameworks, allocating oversight budgets, maintaining secure data systems, and enforcing penalties.',
  pillarAudit: 'Mandatory Audit Guidelines',
  pillarAuditDesc: 'Standard operating procedures and legal frameworks that make social and financial audits mandatory.',
  pillarMetrics: 'Clear Performance Metrics',
  pillarMetricsDesc: 'Measurable benchmarks — like specific reduction rates in stunting or unemployment.',
  pillarBodies: 'Independent Bodies',
  pillarBodiesDesc: 'Legal safeguards for third-party auditors and local social audit units against political interference.',
  pillarDatabases: 'Secure Master Databases',
  pillarDatabasesDesc: 'Central beneficiary registries with clean data, accessible only to authorized audit agencies.',
  // footer
  footerTagline: 'Precision governance for people-first policy.',
  footerSub: 'Dynamic registries · Decentralized biometrics · Direct benefit transfers',
  // login
  loginTitle: 'Welcome back',
  loginSubtitle: 'Sign in to access your secure citizen dashboard. New citizens are onboarded in under two minutes.',
  loginContinueGoogle: 'Continue with Google',
  loginContinueDemo: 'Continue with Demo Account',
  loginDemoHint: 'Demo Account',
  loginPresetLabel: 'Quick fill a demo citizen:',
  loginOrUse: 'Or use your details',
  loginEmail: 'Email',
  loginName: 'Name',
  loginImage: 'Image URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'Verify your Aadhaar',
  verifySubtitle: 'One-time identity verification unlocks your welfare dashboard.',
  verifyAadhaarLabel: '12-digit Aadhaar number',
  verifyMobileLabel: 'Mobile number to receive OTP',
  verifyGenerateOtp: 'Generate OTP',
  verifySendingOtp: 'Sending OTP…',
  verifyDemoNote: 'Demo mode — the OTP request is simulated. No real Aadhaar data is transmitted.',
  verifyOtpSentTo: 'OTP sent to your registered mobile number for',
  verifyDemoOtpLabel: 'Demo OTP:',
  verifyDemoOtpNote: 'A real deployment sends this via SMS — shown here for testing.',
  verifyOtpLabel: '6-digit OTP',
  verifyVerifyOtp: 'Verify OTP',
  verifyVerifying: 'Verifying…',
  verifyChangeAadhaar: 'Change Aadhaar number',
  verifyIdentityVerified: 'Identity verified',
  verifyRedirecting: 'Redirecting to your dashboard…',
  verifyInvalidAadhaar: 'Please enter a valid 12-digit Aadhaar number.',
  verifyInvalidOtp: 'Please enter the 6-digit OTP sent to your phone.',
  verifyInvalidMobile: 'Please enter a valid 10-digit mobile number.',
  verifyFailedGenerate: 'Failed to generate OTP.',
  verifyFailedVerify: 'Verification failed. Please try again.',
  verifySpeakHint: 'Tap the mic and say your Aadhaar or OTP',
  // dashboard
  dashWelcome: 'Welcome',
  dashCitizen: 'Citizen',
  dashVerified: 'Verification Status: Verified',
  dashPending: 'Verification Status: Pending',
  dashVerifyAadhaar: 'Verify Aadhaar',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'Sign out',
  dashFoodSubsidy: 'Food Subsidy (PDS)',
  dashDbt: 'Direct Benefit Transfer',
  dashEducation: 'Education Grant',
  dashHealth: 'Health Coverage',
  dashNotEnrolled: 'Not enrolled',
  dashNextSocialAudit: 'Next Social Audit',
  dashSocialAuditDesc: 'Your village public spending review — open to all residents.',
  // admin
  adminAccess: 'Admin Access',
  adminOversightPortal: 'Ministry oversight portal',
  adminAccessPassword: 'Access password',
  adminEnterPortal: 'Enter Portal',
  adminIncorrect: 'Incorrect password. Try again.',
  adminDemoPassword: 'Demo password:',
  adminRegistration: 'Official Registration',
  adminRegisterDesc: 'Register your oversight role to access the grievance dashboard.',
  adminFullName: 'Full Name',
  adminEmail: 'Official Email',
  adminPhone: 'Phone',
  adminPosition: 'Position',
  adminState: 'State',
  adminDistrict: 'District',
  adminSelectState: 'Select state',
  adminSelectDistrict: 'Select district',
  adminRegisterContinue: 'Register and Continue',
  adminOversightDashboard: 'Oversight Dashboard',
  adminGrievanceIntelligence: 'Grievance Intelligence',
  adminAllDistricts: 'All districts',
  adminExit: 'Exit',
  adminStatusDistribution: 'Status Distribution',
  adminByCategory: 'Grievances by Category',
  adminDistrictBreakdown: 'District Breakdown',
  adminRecentGrievances: 'Recent Grievances',
  adminTotalGrievances: 'total grievances',
  adminOpen: 'open',
  adminNoGrievances: 'No grievances in this view.',
  adminAiSummary: 'AI Topic Summary',
  adminAiNone: 'No grievances recorded for this view.',
  adminPosDm: 'District Magistrate',
  adminPosBdo: 'Block Development Officer',
  adminPosPanchayat: 'Panchayat Secretary',
  adminPosWelfare: 'Welfare Officer',
  adminPosAudit: 'Social Audit Coordinator',
  adminPosState: 'State Nodal Officer',
  adminPosManager: 'Program Manager',
  // common
  commonSubmit: 'Submit',
  commonCancel: 'Cancel',
  commonLoading: 'Loading…',
  verifyEmailLabel: 'Email linked to this Aadhaar (OTP will be sent here)',
  verifyInvalidEmail: 'Please enter a valid email address.',
}
