export const _groupD = {
  sa: {
    navFeatures: 'सुविधाः',
    navOversight: 'पर्यवेक्षणम्',
    navSignIn: 'प्रवेशः',
    heroBadge: 'कल्याणनीतेः कार्यान्वयनम्',
    heroTitle1: 'सूक्ष्मशासनम् ।',
    heroTitle2: 'पुनःपरिकल्पितम् ।',
    heroSubtitle: 'एकः सुरक्षितः नागरिकप्राथम्यः मञ्चः यत्र वास्तविककालस्य दत्तांशः विकेन्द्रीकृतं अस्मितापत्रं प्रत्यक्षं च स्थानान्तरणं यथायोग्येभ्यः जनेभ्यः कल्याणलाभान् वितरति।',
    heroCta: 'स्वदशाफलकं प्रविशन्तु',
    featuresBadge: 'सामर्थ्यानि',
    featuresTitle: 'आधुनिकं कल्याणप्रणाल्यै आवश्यकं सर्वम् ।',
    featuresSubtitle: 'एकः संयोजितः मञ्चः अस्मितां लक्ष्यनिर्धारणं भुगतानं उत्तरदायित्वं च एकीकरोति।',
    tileDynamicRegistries: 'गतिशीलाः सामाजिक-आर्थिकपञ्जीकरणसूचयः',
    tileDynamicRegistriesDesc: 'कर- उपयोगिता- नागरिक-अभिलेखेभ्यः निरन्तरं पात्रतायाः अद्यतनं — यः लक्ष्यनिर्धारणः सदैव वास्तविकतां प्रतिबिम्बते न च स्थगितं जनगणनाम्।',
    tileBiometrics: 'विकेन्द्रीकृतं जैवमितिविज्ञानम्',
    tileBiometricsDesc: 'सुरक्षितानि विकेन्द्रीकृतानि जैवमितीय-अस्मितापत्राणि ये अस्मिताप्रपञ्चं द्विग्रहणं च द्वारे एव निवारयन्ति।',
    tileDbt: 'प्रत्यक्षं लाभस्थानान्तरणम् (DBT)',
    tileDbtDesc: 'नगदं सुविधाः च सत्यापितेषु नागरिकखातेषु प्रत्यक्षं प्रेष्यन्ते — मध्यस्थाः शून्याः।',
    tileConditional: 'शर्तयुक्तं स्थानान्तरणम्',
    tileConditionalDesc: 'शिक्षास्वास्थ्यसन्नद्धीनां सह बद्धानि भुगतानानि मापनीयानां सामाजिकपरिणामानां कृते।',
    tileAudits: 'सामुदायिकी सामाजिकी लेखापरीक्षा',
    tileAuditsDesc: 'लोकसभाः यत्र नागरिकाः व्ययं भूमिस्थितसम्पत्तीनां विरुद्धं परीक्षन्ते।',
    tileAi: 'स्वचालितानि अपवाद-प्रतिवेदनानि',
    tileAiDesc: 'AI सन्दिग्धान् प्रतिरूपान् — यथा एकस्य मोबाइल-सङ्ख्यायाः बहुभिः लाभखातैः सह सम्बन्धः — तत्क्षणीयाय अन्वेषणाय चिह्नयति।',
    oversightBadge: 'मन्त्रालय-पर्यवेक्षणम्',
    oversightTitle: 'मन्त्रालय-ढाञ्चः पायाः च',
    oversightSubtitle: 'मन्त्रालयानि कल्याणनीति-लेखापरीक्षां विधिक-ढाञ्चानां स्थापनेन पर्यवेक्षण-बजट-विनियोजनेन सुरक्षित-दत्तांश-प्रणालीनां पालनेन दण्डानां च प्रवर्तनेन पर्यवेक्षन्ते।',
    pillarAudit: 'अनिवार्या लेखापरीक्षा-दिशानिर्देशाः',
    pillarAuditDesc: 'मानक-सञ्चालन-प्रक्रियाः विधिक-ढाञ्चाः च ये सामाजिकीं वित्तीयीं च लेखापरीक्षां अनिवार्यां कुर्वन्ति।',
    pillarMetrics: 'स्पष्टानि कार्यसम्पादन-मापकानि',
    pillarMetricsDesc: 'मापनीयानि मानकाणि — यथा स्तम्भने बेरोज़गारी-निवारणे वा विशिष्टानि ह्रासदराः।',
    pillarBodies: 'स्वतन्त्राणि निकायाः',
    pillarBodiesDesc: 'तृतीयपक्ष-लेखापरीक्षकाणां स्थानीय-सामाजिक-लेखापरीक्षा-एककानां च राजनैतिक-हस्तक्षेपात् विधिक-सुरक्षा।',
    pillarDatabases: 'सुरक्षिताः मुख्य-सङ्ग्रहाः',
    pillarDatabasesDesc: 'केन्द्रीयाः लाभार्थि-पञ्जिकाः शुद्धेन दत्तांशेन सह केवलं अधिकृत-लेखापरीक्षा-संस्थाभ्यः उपलब्धाः।',
    footerTagline: 'नागरिकप्राथम्य-नीतये सूक्ष्मशासनम्।',
    footerSub: 'गतिशीलाः पञ्जिकाः · विकेन्द्रीकृतं जैवमितिविज्ञानम् · प्रत्यक्षं लाभस्थानान्तरणम्',
    loginTitle: 'पुनः स्वागतम्',
    loginSubtitle: 'स्वस्य सुरक्षितस्य नागरिकडैश्बोर्डस्य प्रवेशाय प्रविशन्तु। नवाः नागरिकाः द्विमिनटाभ्यन्तरे आरोप्यन्ते।',
    loginContinueGoogle: 'Google सह प्रविशन्तु',
    loginContinueDemo: 'डेमो खातेन सह प्रविशन्तु',
    loginDemoHint: 'डेमो खातम्',
    loginPresetLabel: 'द्रुतं डेमो-नागरिकं पूरयन्तु:',
    loginOrUse: 'अथवा स्वविवरणैः उपयुज्यताम्',
    loginEmail: 'ई-मेलः',
    loginName: 'नाम',
    loginImage: 'चित्रस्य URL',
    verifyStepAadhaar: 'Aadhaar',
    verifyStepOtp: 'OTP',
    verifyTitle: 'स्व Aadhaar सत्यापयन्तु',
    verifySubtitle: 'एकवारं अस्मिता-सत्यापनं स्वं कल्याण-डैश्बोर्ड् उन्मीलयति।',
    verifyAadhaarLabel: '12-अङ्कीयः Aadhaar सङ्ख्या',
    verifyMobileLabel: 'OTP प्राप्तुं मोबाइल-सङ्ख्या',
    verifyGenerateOtp: 'OTP जनयन्तु',
    verifySendingOtp: 'OTP प्रेष्यते…',
    verifyDemoNote: 'डेमो मोड् — OTP निवेदनं सिमुलेट् क्रियते। वास्तविकः Aadhaar दत्तांशः न प्रेष्यते।',
    verifyOtpSentTo: 'भवतः पञ्जीकृत-मोबाइल-सङ्ख्यायै OTP प्रेषितम्',
    verifyDemoOtpLabel: 'डेमो OTP:',
    verifyDemoOtpNote: 'वास्तविकः विस्तारः एतत् SMS द्वारा प्रेषयति — परीक्षणार्थं अत्र दर्शितम्।',
    verifyOtpLabel: '6-अङ्कीयः OTP',
    verifyVerifyOtp: 'OTP सत्यापयन्तु',
    verifyVerifying: 'सत्याप्यते…',
    verifyChangeAadhaar: 'Aadhaar सङ्ख्यां परिवर्तयन्तु',
    verifyIdentityVerified: 'अस्मिता सत्यापिता',
    verifyRedirecting: 'स्वं डैश्बोर्ड् प्रति पुनर्निर्दिश्यते…',
    verifyInvalidAadhaar: 'कृपया वैधं 12-अङ्कीयं Aadhaar सङ्ख्यां प्रविशन्तु।',
    verifyInvalidOtp: 'कृपया स्वमोबाइल-सङ्ख्यायां प्रेषितं 6-अङ्कीयं OTP प्रविशन्तु।',
    verifyInvalidMobile: 'कृपया वैधं 10-अङ्कीयं मोबाइल-सङ्ख्यां प्रविशन्तु।',
    verifyFailedGenerate: 'OTP जनयितुं असफलम्।',
    verifyFailedVerify: 'सत्यापनं असफलम्। पुनः प्रयतन्ताम्।',
    verifySpeakHint: 'माइक् स्पृश्य Aadhaar वा OTP वदन्तु',
    dashWelcome: 'स्वागतम्',
    dashCitizen: 'नागरिकः',
    dashVerified: 'सत्यापन-स्थितिः: सत्यापितम्',
    dashPending: 'सत्यापन-स्थितिः: प्रतीक्षमाणम्',
    dashVerifyAadhaar: 'Aadhaar सत्यापयन्तु',
    dashAadhaar: 'Aadhaar',
    dashSignOut: 'निर्गमनम्',
    dashFoodSubsidy: 'आहार-अनुदानम् (PDS)',
    dashDbt: 'प्रत्यक्षं लाभस्थानान्तरणम् (DBT)',
    dashEducation: 'शिक्षा-अनुदानम्',
    dashHealth: 'स्वास्थ्य-आवरणम्',
    dashNotEnrolled: 'पञ्जीकृतं न',
    dashNextSocialAudit: 'अग्रिमः सामाजिकः लेखापरीक्षा',
    dashSocialAuditDesc: 'भवतः ग्रामस्य सार्वजनिक-व्यय-समीक्षा — सर्वेभ्यः निवासिभ्यः मुक्ता।',
    adminAccess: 'व्यवस्थापक-प्रवेशः',
    adminOversightPortal: 'मन्त्रालय-पर्यवेक्षण-पोर्टल्',
    adminAccessPassword: 'प्रवेश-कूटशब्दः',
    adminEnterPortal: 'पोर्टल् प्रविशन्तु',
    adminIncorrect: 'अशुद्धः कूटशब्दः। पुनः प्रयतन्ताम्।',
    adminDemoPassword: 'डेमो कूटशब्दः:',
    adminRegistration: 'अधिकारिकं पञ्जीकरणम्',
    adminRegisterDesc: 'स्वं पर्यवेक्षण-भूमिकां पञ्जीकुर्वन्तु यतः शिकायत्-डैश्बोर्ड् प्राप्नुथ।',
    adminFullName: 'पूर्णं नाम',
    adminEmail: 'अधिकारिकं ई-मेलः',
    adminPhone: 'फोनः',
    adminPosition: 'पदम्',
    adminState: 'राज्यम्',
    adminDistrict: 'जिल्ला',
    adminSelectState: 'राज्यं चिनुत',
    adminSelectDistrict: 'जिल्लां चिनुत',
    adminRegisterContinue: 'पञ्जीकुरुत उपरि च सन्ततिः',
    adminOversightDashboard: 'पर्यवेक्षण-डैश्बोर्ड्',
    adminGrievanceIntelligence: 'शिकायत्-बुद्धिमत्ता',
    adminAllDistricts: 'सर्वे जिल्लाः',
    adminExit: 'निर्गमनम्',
    adminStatusDistribution: 'स्थिति-वितरणम्',
    adminByCategory: 'वर्गानुसारं शिकायतः',
    adminDistrictBreakdown: 'जिल्ला-विभाजनम्',
    adminRecentGrievances: 'साम्प्रताः शिकायतः',
    adminTotalGrievances: 'कुलं शिकायतः',
    adminOpen: 'मुक्तम्',
    adminNoGrievances: 'अस्मिन् दृश्ये काचित् शिकायत् नास्ति।',
    adminAiSummary: 'AI विषय-सारांशः',
    adminAiNone: 'अस्मिन् दृश्ये काचित् शिकायत् न पञ्जीकृता।',
    adminPosDm: 'जिल्लाधिकारी',
    adminPosBdo: 'ब्लॉक-विकास-अधिकारी',
    adminPosPanchayat: 'पञ्चायत-सचिवः',
    adminPosWelfare: 'कल्याण-अधिकारी',
    adminPosAudit: 'सामाजिक-लेखापरीक्षा-समन्वयकः',
    adminPosState: 'राज्य-नोडल्-अधिकारी',
    adminPosManager: 'कार्यक्रम-प्रबन्धकः',
    commonSubmit: 'समर्पयन्तु',
    commonCancel: 'रद्दं कुरुत',
    commonLoading: 'लोड् भवति…',
  },
}
