export const _gu = {
  // nav
  navFeatures: 'સુવિધાઓ',
  navOversight: 'દેખરેખ',
  navSignIn: 'સાઇન ઇન',
  // hero
  heroBadge: 'કલ્યાણ નીતિ અમલીકરણ',
  heroTitle1: 'સચોટ વહીવટી શાસન.',
  heroTitle2: 'પુનઃકલ્પિત.',
  heroSubtitle: 'એક સુરક્ષિત, નાગરિક-પ્રથમ પ્લેટફોર્મ જ્યાં રીઅલ-ટાઇમ ડેટા, વિકેન્દ્રિત ઓળખ અને સીધી ટ્રાન્સફર યોગ્ય લોકો સુધી કલ્યાણ લાભ પહોંચાડે છે.',
  heroCta: 'તમારું Dashboard ઍક્સેસ કરો',
  // features
  featuresBadge: 'ક્ષમતાઓ',
  featuresTitle: 'આધુનિક કલ્યાણ વ્યવસ્થાને જરૂરી બધું.',
  featuresSubtitle: 'એક જોડાયેલ પ્લેટફોર્મ ઓળખ, લક્ષ્યાંકન, ચુકવણી અને જવાબદારીને એકીકૃત કરે છે.',
  tileDynamicRegistries: 'ગતિશીલ સામાજિક-આર્થિક નોંધણીઓ',
  tileDynamicRegistriesDesc: 'કર, ઉપયોગિતા અને નાગરિક રેકોર્ડમાંથી સતત પાત્રતા અપડેટ્સ — હંમેશા વાસ્તવિકતા પ્રતિબિંબિત કરતું લક્ષ્યાંકન, ક્યારેય જૂની વસ્તી ગણતરી નહીં.',
  tileBiometrics: 'વિકેન્દ્રિત બાયોમેટ્રિક્સ',
  tileBiometricsDesc: 'સુરક્ષિત, વિકેન્દ્રિત બાયોમેટ્રિક આઈડી જે ઓળખ છેતરપિંડી અને ડબલ-ડિપિંગને દ્વારે અટકાવે છે.',
  tileDbt: 'સીધા લાભ ટ્રાન્સફર (DBT)',
  tileDbtDesc: 'રોકડ અને સબસિડી સીધી ચકાસાયેલ નાગરિક ખાતામાં — શૂન્ય મધ્યસ્થી.',
  tileConditional: 'શરતી ટ્રાન્સફર',
  tileConditionalDesc: 'શિક્ષણ અને આરોગ્ય માઇલસ્ટોન સાથે જોડાયેલ ચુકવણી માપી શકાય તેવા સામાજિક પરિણામો માટે.',
  tileAudits: 'સામુદાયિક સામાજિક ઓડિટ',
  tileAuditsDesc: 'જાહેર સભાઓ જ્યાં નાગરિકો જમીન પરની મિલકતો સામે ખર્ચની તપાસ કરે છે.',
  tileAi: 'સ્વચાલિત અપવાદ રિપોર્ટ',
  tileAiDesc: 'AI શંકાસ્પદ પેટર્નને ફ્લૅગ કરે છે — જેમ કે એકાધિક લાભ ખાતાઓ સાથે જોડાયેલ એક જ ફોન નંબર — તાત્કાલિક તપાસ માટે.',
  // oversight
  oversightBadge: 'મંત્રાલય દેખરેખ',
  oversightTitle: 'મંત્રાલય માળખું અને માળખાકીય સુવિધા',
  oversightSubtitle: 'મંત્રાલયો કાનૂની માળખાં સ્થાપિત કરી, દેખરેખ બજેટ ફાળવી, સુરક્ષિત ડેટા સિસ્ટમ્સ જાળવી અને દંડ લાદીને કલ્યાણ નીતિ ઓડિટની દેખરેખ રાખે છે.',
  pillarAudit: 'ફરજિયાત ઓડિટ માર્ગદર્શિકા',
  pillarAuditDesc: 'ધોરણસર કામગીરી પ્રક્રિયાઓ અને કાનૂની માળખાં જે સામાજિક અને નાણાકીય ઓડિટને ફરજિયાત બનાવે છે.',
  pillarMetrics: 'સ્પષ્ટ પ્રદર્શન મેટ્રિક્સ',
  pillarMetricsDesc: 'માપી શકાય તેવા બેન્ચમાર્ક — જેમ કે લાંબા-સમયના વિકાસ અથવા બેરોજગારીમાં ચોક્કસ ઘટાડાના દર.',
  pillarBodies: 'સ્વતંત્ર સંસ્થાઓ',
  pillarBodiesDesc: 'તૃતીય-પક્ષ ઓડિટર્સ અને સ્થાનિક સામાજિક ઓડિટ એકમો માટે રાજકીય દખલગીરી સામે કાનૂની સુરક્ષા.',
  pillarDatabases: 'સુરક્ષિત માસ્ટર ડેટાબેઝ',
  pillarDatabasesDesc: 'શુદ્ધ ડેટા સાથેની કેન્દ્રીય લાભાર્થી નોંધણી, જે માત્ર અધિકૃત ઓડિટ એજન્સીઓ માટે જ ઉપલબ્ધ છે.',
  // footer
  footerTagline: 'લોક-પ્રથમ નીતિ માટે સચોટ વહીવટ.',
  footerSub: 'ગતિશીલ નોંધણીઓ · વિકેન્દ્રિત બાયોમેટ્રિક્સ · સીધા લાભ ટ્રાન્સફર',
  // login
  loginTitle: 'પાછા આવ્યા સ્વાગત છે',
  loginSubtitle: 'તમારું સુરક્ષિત નાગરિક Dashboard ઍક્સેસ કરવા સાઇન ઇન કરો. નવા નાગરિકો બે મિનિટથી ઓછામાં ઓનબોર્ડ થાય છે.',
  loginContinueGoogle: 'Google સાથે ચાલુ રાખો',
  loginContinueDemo: 'ડેમો એકાઉન્ટ સાથે ચાલુ રાખો',
  loginDemoHint: 'ડેમો એકાઉન્ટ',
  loginPresetLabel: 'ઝડપથી ડેમો નાગરિક ભરો:',
  loginOrUse: 'અથવા તમારી વિગતો વાપરો',
  loginEmail: 'ઇમેઇલ',
  loginName: 'નામ',
  loginImage: 'છબી URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'તમારું Aadhaar ચકાસો',
  verifySubtitle: 'એકવારની ઓળખ ચકાસણી તમારું કલ્યાણ Dashboard અનલૉક કરે છે.',
  verifyAadhaarLabel: '12-અંકનો Aadhaar નંબર',
  verifyMobileLabel: 'OTP મેળવવા માટે મોબાઇલ નંબર',
  verifyGenerateOtp: 'OTP જનરેટ કરો',
  verifySendingOtp: 'OTP મોકલાઈ રહ્યો છે…',
  verifyDemoNote: 'ડેમો મોડ — OTP વિનંતી સિમ્યુલેટ થયેલ છે. કોઈ વાસ્તવિક Aadhaar ડેટા મોકલાતો નથી.',
  verifyOtpSentTo: 'તમારા નોંધાયેલ મોબાઇલ નંબર પર OTP મોકલાયો',
  verifyDemoOtpLabel: 'ડેમો OTP:',
  verifyDemoOtpNote: 'વાસ્તવિક ડિપ્લોયમેન્ટ આને SMS દ્વારા મોકલે છે — ટેસ્ટિંગ માટે અહીં દર્શાવેલ છે.',
  verifyOtpLabel: '6-અંકનો OTP',
  verifyVerifyOtp: 'OTP ચકાસો',
  verifyVerifying: 'ચકાસાઈ રહ્યું છે…',
  verifyChangeAadhaar: 'Aadhaar નંબર બદલો',
  verifyIdentityVerified: 'ઓળખ ચકાસાઈ',
  verifyRedirecting: 'તમારા Dashboard પર રીડાયરેક્ટ થઈ રહ્યું છે…',
  verifyInvalidAadhaar: 'કૃપા કરીને માન્ય 12-અંકનો Aadhaar નંબર દાખલ કરો.',
  verifyInvalidOtp: 'કૃપા કરીને તમારા ફોન પર મોકલેલ 6-અંકનો OTP દાખલ કરો.',
  verifyInvalidMobile: 'કૃપા કરીને માન્ય 10-અંકનો મોબાઇલ નંબર દાખલ કરો.',
  verifyFailedGenerate: 'OTP જનરેટ કરવામાં નિષ્ફળ.',
  verifyFailedVerify: 'ચકાસણી નિષ્ફળ. કૃપા કરીને ફરી પ્રયાસ કરો.',
  verifySpeakHint: 'માઇક પર ટેપ કરો અને તમારું Aadhaar અથવા OTP બોલો',
  // dashboard
  dashWelcome: 'સ્વાગત',
  dashCitizen: 'નાગરિક',
  dashVerified: 'ચકાસણી સ્થિતિ: ચકાસાયેલ',
  dashPending: 'ચકાસણી સ્થિતિ: બાકી',
  dashVerifyAadhaar: 'Aadhaar ચકાસો',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'સાઇન આઉટ',
  dashFoodSubsidy: 'ખાદ્ય સબસિડી (PDS)',
  dashDbt: 'સીધો લાભ ટ્રાન્સફર (DBT)',
  dashEducation: 'શિક્ષણ અનુદાન',
  dashHealth: 'આરોગ્ય કવચ',
  dashNotEnrolled: 'નોંધાયેલ નથી',
  dashNextSocialAudit: 'આગામી સામાજિક ઓડિટ',
  dashSocialAuditDesc: 'તમારા ગામની જાહેર ખર્ચ સમીક્ષા — બધા રહેવાસીઓ માટે ખુલ્લી.',
  // admin
  adminAccess: 'એડમિન ઍક્સેસ',
  adminOversightPortal: 'મંત્રાલય દેખરેખ પોર્ટલ',
  adminAccessPassword: 'ઍક્સેસ પાસવર્ડ',
  adminEnterPortal: 'પોર્ટલમાં પ્રવેશ કરો',
  adminIncorrect: 'ખોટો પાસવર્ડ. ફરી પ્રયાસ કરો.',
  adminDemoPassword: 'ડેમો પાસવર્ડ:',
  adminRegistration: 'અધિકૃત નોંધણી',
  adminRegisterDesc: 'ફરિયાદ Dashboard ઍક્સેસ કરવા તમારી દેખરેખ ભૂમિકા નોંધણી કરો.',
  adminFullName: 'પૂરું નામ',
  adminEmail: 'અધિકૃત ઇમેઇલ',
  adminPhone: 'ફોન',
  adminPosition: 'હોદ્દો',
  adminState: 'રાજ્ય',
  adminDistrict: 'જિલ્લો',
  adminSelectState: 'રાજ્ય પસંદ કરો',
  adminSelectDistrict: 'જિલ્લો પસંદ કરો',
  adminRegisterContinue: 'નોંધણી કરો અને ચાલુ રાખો',
  adminOversightDashboard: 'દેખરેખ Dashboard',
  adminGrievanceIntelligence: 'ફરિયાદ ઇન્ટેલિજન્સ',
  adminAllDistricts: 'બધા જિલ્લાઓ',
  adminExit: 'બહાર નીકળો',
  adminStatusDistribution: 'સ્થિતિ વિતરણ',
  adminByCategory: 'શ્રેણી દીઠ ફરિયાદો',
  adminDistrictBreakdown: 'જિલ્લા વિગતવાર',
  adminRecentGrievances: 'તાજેતરની ફરિયાદો',
  adminTotalGrievances: 'કુલ ફરિયાદો',
  adminOpen: 'ખુલ્લી',
  adminNoGrievances: 'આ દૃશ્યમાં કોઈ ફરિયાદ નથી.',
  adminAiSummary: 'AI વિષય સારાંશ',
  adminAiNone: 'આ દૃશ્ય માટે કોઈ ફરિયાદ નોંધાયેલ નથી.',
  adminPosDm: 'જિલ્લા મેજિસ્ટ્રેટ',
  adminPosBdo: 'બ્લૉક વિકાસ અધિકારી',
  adminPosPanchayat: 'પંચાયત સચિવ',
  adminPosWelfare: 'કલ્યાણ અધિકારી',
  adminPosAudit: 'સામાજિક ઓડિટ સંયોજક',
  adminPosState: 'રાજ્ય નોડલ અધિકારી',
  adminPosManager: 'પ્રોગ્રામ મેનેજર',
  // common
  commonSubmit: 'સબમિટ',
  commonCancel: 'રદ કરો',
  commonLoading: 'લોડ થઈ રહ્યું છે…',
}
