export const _hi = {
  // nav
  navFeatures: 'सुविधाएँ',
  navOversight: 'पर्यवेक्षण',
  navSignIn: 'साइन इन',
  // hero
  heroBadge: 'कल्याण नीति कार्यान्वयन',
  heroTitle1: 'सटीक शासन।',
  heroTitle2: 'पुनर्कल्पित।',
  heroSubtitle: 'एक सुरक्षित, नागरिक-प्रथम मंच जहाँ वास्तविक समय का डेटा, विकेंद्रीकृत पहचान और प्रत्यक्ष हस्तांतरण कल्याण लाभों को ठीक सही व्यक्तियों तक पहुँचाते हैं।',
  heroCta: 'अपना डैशबोर्ड एक्सेस करें',
  // features
  featuresBadge: 'क्षमताएँ',
  featuresTitle: 'एक आधुनिक कल्याण प्रणाली की जरूरत हर चीज़।',
  featuresSubtitle: 'एक जुड़ा हुआ मंच पहचान, लक्ष्यीकरण, भुगतान और जवाबदेही को एक साथ लाता है।',
  tileDynamicRegistries: 'गतिशील सामाजिक-आर्थिक रजिस्ट्रियाँ',
  tileDynamicRegistriesDesc: 'कर, उपयोगिता और नागरिक रिकॉर्ड से निरंतर पात्रता अद्यतन — ऐसा लक्ष्यीकरण जो हमेशा वास्तविकता को दर्शाता है, कभी पुरानी जनगणना नहीं।',
  tileBiometrics: 'विकेंद्रीकृत बायोमेट्रिक्स',
  tileBiometricsDesc: 'सुरक्षित, विकेंद्रीकृत बायोमेट्रिक पहचान जो द्वार पर पहचान धोखाधड़ी और डबल-डिपिंग को रोकती है।',
  tileDbt: 'प्रत्यक्ष लाभ हस्तांतरण',
  tileDbtDesc: 'नकद और सब्सिडी सीधे सत्यापित नागरिक खातों में भेजी जाती हैं — कोई बिचौलिए नहीं।',
  tileConditional: 'सशर्त हस्तांतरण',
  tileConditionalDesc: 'शिक्षा और स्वास्थ्य मील के पत्थरों से जुड़े भुगतान, मापनीय सामाजिक परिणामों के लिए।',
  tileAudits: 'सामुदायिक सामाजिक लेखापरीक्षा',
  tileAuditsDesc: 'सार्वजनिक सभाएँ जहाँ नागरिक जमीन पर संपत्तियों के विरुद्ध व्यय की परीक्षा करते हैं।',
  tileAi: 'स्वचालित अपवाद रिपोर्ट',
  tileAiDesc: 'AI संदिग्ध पैटर्न को झंडा दिखाता है — जैसे कई लाभ खातों से जुड़ा एक ही फोन नंबर — त्वरित जाँच के लिए।',
  // oversight
  oversightBadge: 'मंत्रालय पर्यवेक्षण',
  oversightTitle: 'मंत्रालय ढाँचा और बुनियादी संरचना',
  oversightSubtitle: 'मंत्रालय कानूनी ढाँचे स्थापित करने, पर्यवेक्षण बजट आवंटित करने, सुरक्षित डेटा प्रणालियाँ बनाए रखने और दंड लागू करने के माध्यम से कल्याण नीति लेखापरीक्षा की देखरेख करते हैं।',
  pillarAudit: 'अनिवार्य लेखापरीक्षा दिशानिर्देश',
  pillarAuditDesc: 'मानक संचालन प्रक्रियाएँ और कानूनी ढाँचे जो सामाजिक और वित्तीय लेखापरीक्षा को अनिवार्य बनाते हैं।',
  pillarMetrics: 'स्पष्ट प्रदर्शन मेट्रिक्स',
  pillarMetricsDesc: 'मापनीय मानक — जैसे स्तंभवृद्धि या बेरोजगारी में विशिष्ट कमी दर।',
  pillarBodies: 'स्वतंत्र निकाय',
  pillarBodiesDesc: 'तृतीय-पक्ष ऑडिटरों और स्थानीय सामाजिक लेखा इकाइयों के लिए राजनीतिक हस्तक्षेप के विरुद्ध कानूनी सुरक्षा।',
  pillarDatabases: 'सुरक्षित मास्टर डेटाबेस',
  pillarDatabasesDesc: 'केंद्रीय लाभार्थी रजिस्ट्रियाँ स्वच्छ डेटा के साथ, जो केवल अधिकृत ऑडिट एजेंसियों के लिए सुलभ हैं।',
  // footer
  footerTagline: 'लोग-प्रथम नीति के लिए सटीक शासन।',
  footerSub: 'गतिशील रजिस्ट्रियाँ · विकेंद्रीकृत बायोमेट्रिक्स · प्रत्यक्ष लाभ हस्तांतरण',
  // login
  loginTitle: 'वापस स्वागत है',
  loginSubtitle: 'अपने सुरक्षित नागरिक डैशबोर्ड तक पहुँचने के लिए साइन इन करें। नए नागरिक दो मिनट से कम समय में ऑनबोर्ड हो जाते हैं।',
  loginContinueGoogle: 'Google के साथ जारी रखें',
  loginContinueDemo: 'डेमो खाते के साथ जारी रखें',
  loginDemoHint: 'डेमो खाता',
  loginPresetLabel: 'एक डेमो नागरिक त्वरित भरें:',
  loginOrUse: 'या अपना विवरण उपयोग करें',
  loginEmail: 'ईमेल',
  loginName: 'नाम',
  loginImage: 'छवि URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'अपना Aadhaar सत्यापित करें',
  verifySubtitle: 'एक बार की पहचान सत्यापन आपका कल्याण डैशबोर्ड खोलता है।',
  verifyAadhaarLabel: '12-अंकीय Aadhaar नंबर',
  verifyMobileLabel: 'OTP प्राप्त करने का मोबाइल नंबर',
  verifyGenerateOtp: 'OTP जनरेट करें',
  verifySendingOtp: 'OTP भेजा जा रहा है…',
  verifyDemoNote: 'डेमो मोड — OTP अनुरोध अनुकरण किया गया है। कोई वास्तविक Aadhaar डेटा प्रेषित नहीं किया जाता।',
  verifyOtpSentTo: 'आपके पंजीकृत मोबाइल नंबर पर OTP भेजा गया',
  verifyDemoOtpLabel: 'डेमो OTP:',
  verifyDemoOtpNote: 'एक वास्तविक तैनाती इसे SMS के माध्यम से भेजती है — यहाँ परीक्षण के लिए दिखाया गया है।',
  verifyOtpLabel: '6-अंकीय OTP',
  verifyVerifyOtp: 'OTP सत्यापित करें',
  verifyVerifying: 'सत्यापित किया जा रहा है…',
  verifyChangeAadhaar: 'Aadhaar नंबर बदलें',
  verifyIdentityVerified: 'पहचान सत्यापित',
  verifyRedirecting: 'अपने डैशबोर्ड पर पुनर्निर्देशित किया जा रहा है…',
  verifyInvalidAadhaar: 'कृपया एक वैध 12-अंकीय Aadhaar नंबर दर्ज करें।',
  verifyInvalidOtp: 'कृपया अपने फोन पर भेजा गया 6-अंकीय OTP दर्ज करें।',
  verifyInvalidMobile: 'कृपया एक वैध 10-अंकीय मोबाइल नंबर दर्ज करें।',
  verifyFailedGenerate: 'OTP जनरेट करने में विफल।',
  verifyFailedVerify: 'सत्यापन विफल। कृपया पुनः प्रयास करें।',
  verifySpeakHint: 'माइक पर टैप करें और अपना Aadhaar या OTP बोलें',
  // dashboard
  dashWelcome: 'स्वागत',
  dashCitizen: 'नागरिक',
  dashVerified: 'सत्यापन स्थिति: सत्यापित',
  dashPending: 'सत्यापन स्थिति: लंबित',
  dashVerifyAadhaar: 'Aadhaar सत्यापित करें',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'साइन आउट',
  dashFoodSubsidy: 'खाद्य सब्सिडी (PDS)',
  dashDbt: 'प्रत्यक्ष लाभ हस्तांतरण',
  dashEducation: 'शिक्षा अनुदान',
  dashHealth: 'स्वास्थ्य कवरेज',
  dashNotEnrolled: 'नामांकित नहीं',
  dashNextSocialAudit: 'अगली सामाजिक लेखापरीक्षा',
  dashSocialAuditDesc: 'आपके गाँव का सार्वजनिक व्यय समीक्षा — सभी निवासियों के लिए खुला।',
  // admin
  adminAccess: 'व्यवस्थापक एक्सेस',
  adminOversightPortal: 'मंत्रालय पर्यवेक्षण पोर्टल',
  adminAccessPassword: 'एक्सेस पासवर्ड',
  adminEnterPortal: 'पोर्टल में प्रवेश करें',
  adminIncorrect: 'गलत पासवर्ड। पुनः प्रयास करें।',
  adminDemoPassword: 'डेमो पासवर्ड:',
  adminRegistration: 'आधिकारिक पंजीकरण',
  adminRegisterDesc: 'शिकायत डैशबोर्ड तक पहुँचने के लिए अपनी पर्यवेक्षण भूमिका पंजीकृत करें।',
  adminFullName: 'पूरा नाम',
  adminEmail: 'आधिकारिक ईमेल',
  adminPhone: 'फोन',
  adminPosition: 'पद',
  adminState: 'राज्य',
  adminDistrict: 'जिला',
  adminSelectState: 'राज्य चुनें',
  adminSelectDistrict: 'जिला चुनें',
  adminRegisterContinue: 'पंजीकृत करें और जारी रखें',
  adminOversightDashboard: 'पर्यवेक्षण डैशबोर्ड',
  adminGrievanceIntelligence: 'शिकायत इंटेलिजेंस',
  adminAllDistricts: 'सभी जिले',
  adminExit: 'बाहर जाएँ',
  adminStatusDistribution: 'स्थिति वितरण',
  adminByCategory: 'श्रेणी के अनुसार शिकायतें',
  adminDistrictBreakdown: 'जिला विवरण',
  adminRecentGrievances: 'हाल की शिकायतें',
  adminTotalGrievances: 'कुल शिकायतें',
  adminOpen: 'खुली',
  adminNoGrievances: 'इस दृश्य में कोई शिकायत नहीं।',
  adminAiSummary: 'AI विषय सारांश',
  adminAiNone: 'इस दृश्य के लिए कोई शिकायत दर्ज नहीं।',
  adminPosDm: 'जिला मजिस्ट्रेट',
  adminPosBdo: 'ब्लॉक विकास अधिकारी',
  adminPosPanchayat: 'पंचायत सचिव',
  adminPosWelfare: 'कल्याण अधिकारी',
  adminPosAudit: 'सामाजिक लेखा समन्वयक',
  adminPosState: 'राज्य नोडल अधिकारी',
  adminPosManager: 'कार्यक्रम प्रबंधक',
  // common
  commonSubmit: 'जमा करें',
  commonCancel: 'रद्द करें',
  commonLoading: 'लोड हो रहा है…',
}
