export const _ks = {
  // nav
  navFeatures: 'خاصیت',
  navOversight: 'نگرانی',
  navSignIn: 'داخل گژھو',
  // hero
  heroBadge: 'فلاحی پالیسی عمل آوری',
  heroTitle1: 'درست حکمرانی۔',
  heroTitle2: 'نوٚ متصور۔',
  heroSubtitle: 'اَکھ محفوظ تہٕ شہری اول پلیٹ فارم یَتھ مَنٛز حقیقی وقتُک ڈیٹا، غیر مرکزی شناخت، تہٕ سیدھہٕ منتقلی فلاحی فائدہٕ بالکل صحیح لوکن ہِیو پہنچان۔',
  heroCta: 'اپنہٕ ڈیش بورڈ کھولو',
  // features
  featuresBadge: 'صلاحیت',
  featuresTitle: 'اَکھ جدید فلاحی نظام خٲترٕ ضروری سارہِ کٲم۔',
  featuresSubtitle: 'اَکھ مربوط پلیٹ فارم شناخت، نشانہٕ بَنٲوٕنی، ادائیگی، تہٕ جوابدہی ہِکٲے جوڑنہٕ چھُ۔',
  tileDynamicRegistries: 'متحرک سماجی اقتصادی رجسٹری',
  tileDynamicRegistriesDesc: 'ٹیکس، یوٹیلٹی، تہٕ شہری ریکارڈہٕ پؠٹھ لگاتار اہلیت اپڈیٹ — نشانہٕ بَنٲوٕنی یُس ہمیشہٕ حقیقتٕ دکھاون، کٔنٛہہ پرانہٕ مردم شماری نہٕ۔',
  tileBiometrics: 'غیر مرکزی بائیو میٹرک',
  tileBiometricsDesc: 'محفوظ، غیر مرکزی بائیو میٹرک شناخت یُس دروازہٕ پؠٹھ شناختی دھوکہٕ تہٕ دوگانہٕ وصولی روکان۔',
  tileDbt: 'سیدھہٕ فائدہٕ منتقلی (DBT)',
  tileDbtDesc: 'نقد تہٕ سبسڈی تصدیق شُدہٕ شہری اکاؤنٹس مَنٛز سیدھہٕ منتقل — کٔنٛہہ درمیانی نہٕ۔',
  tileConditional: 'مشروط منتقلی',
  tileConditionalDesc: 'تعلیم تہٕ صحتُک نِشانن سٟتؠ جوڑنہٕ آمِت ادائیگی پؠٹھ پیمائشی سماجی نَتیجہٕ۔',
  tileAudits: 'کمیونٹی سماجی آڈٹ',
  tileAuditsDesc: 'عوامی جلسہٕ یَتھ مَنٛز شہری خَرچ زمینی اثاثن ہِیو مقابلہٕ کران۔',
  tileAi: 'خودکار استثناء رپورٹ',
  tileAiDesc: 'AI شکوکناک پیٹرن پہچانان — یِمہٕ اَکھ فون نمبر متعدد فائدہٕ اکاؤنٹس سٟتؠ جوڑنہٕ آمِت — فوری تفتیش خٲطرٕ۔',
  // oversight
  oversightBadge: 'وزارت نگرانی',
  oversightTitle: 'وزارت فریم ورک تہٕ بنیادی ڈانچہٕ',
  oversightSubtitle: 'وزارت فلاحی پالیسی آڈٹنٛد نگرانی قانونی فریم ورک بَنٲوٕنہٕ، نگرانی بجٹ مختص کرنہٕ، محفوظ ڈیٹا سسٹم برقرار تھٲونہٕ، تہٕ سزا نافذ کرنہٕ سٟتؠ کران۔',
  pillarAudit: 'لازمی آڈٹ گائیڈلائن',
  pillarAuditDesc: 'معیاری آپریٹنگ طریقہٕ کار تہٕ قانونی فریم ورک یُس سماجی تہٕ مالی آڈٹ لازمی بنٲوَن۔',
  pillarMetrics: 'واضح کارکردگی میٹرک',
  pillarMetricsDesc: 'پیمائشی بینچ مارک — یِمہٕ ستھ یا بے روزگاری مَنٛز مخصوص کمیٔ دَرجہٕ۔',
  pillarBodies: 'آزاد ادارہٕ',
  pillarBodiesDesc: 'تیسری پارٹی آڈٹرن تہٕ مقامی سماجی آڈٹ یونٹن خٲطرٕ سیاسی مداخلتہٕ خلاف قانونی تحفظ۔',
  pillarDatabases: 'محفوظ ماسٹر ڈیٹا بیس',
  pillarDatabasesDesc: 'مرکزی مستفید رجسٹری صاف ڈیٹا سٟتؠ، صرف مجاز آڈٹ ایجنسیوں خٲطرٕ قابل رسائی۔',
  // footer
  footerTagline: 'لوک اول پالیسی خٲطرٕ درست حکمرانی۔',
  footerSub: 'متحرک رجسٹری · غیر مرکزی بائیو میٹرک · سیدھہٕ فائدہٕ منتقلی',
  // login
  loginTitle: 'پرنٛد واپس',
  loginSubtitle: 'اپنہٕ محفوظ شہری ڈیش بورڈ کھولُن داخل گژھو۔ نوٚ شہری دوٚ مِنَٹہٕ کم مَنٛز آن بورڈ کرنہٕ چھِ۔',
  loginContinueGoogle: 'Google سٟتؠ جاری تھٲو',
  loginContinueDemo: 'ڈیمو اکاؤنٹ سٟتؠ جاری تھٲو',
  loginDemoHint: 'ڈیمو اکاؤنٹ',
  loginPresetLabel: 'جلدی ڈیمو شہری بھرو:',
  loginOrUse: 'یٲہ اپنہٕ تفصیل استعمال کرو',
  loginEmail: 'ای میل',
  loginName: 'ناو',
  loginImage: 'تصویر URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'اپنہٕ Aadhaar تصدیق کرو',
  verifySubtitle: 'اَکھ باری شناختی تصدیق اپنہٕ فلاحی ڈیش بورڈ کھولان۔',
  verifyAadhaarLabel: '12 ہندر Aadhaar نمبر',
  verifyMobileLabel: 'OTP حٲصل کرنہٕ خٲطرٕ موبائل نمبر',
  verifyGenerateOtp: 'OTP بناوٕ',
  verifySendingOtp: 'OTP گَژھان…',
  verifyDemoNote: 'ڈیمو موڈ — OTP درخواست سِمُلَیٹ چھُ۔ کٔنٛہہ اصلی Aadhaar ڈیٹا نہٕ گَژھان۔',
  verifyOtpSentTo: 'OTP اپنہٕ رجسٹر شُدہٕ موبائل نمبر پؠٹھ گَیہِ',
  verifyDemoOtpLabel: 'ڈیمو OTP:',
  verifyDemoOtpNote: 'اصلی تعیناتی یہِ SMS سٟتؠ گَسَن — ٹیسٹنگ خٲطرٕ یَتھ یہِ دکھاونہٕ آمِت۔',
  verifyOtpLabel: '6 ہندر OTP',
  verifyVerifyOtp: 'OTP تصدیق کرو',
  verifyVerifying: 'تصدیق گَژھان…',
  verifyChangeAadhaar: 'Aadhaar نمبر بدلو',
  verifyIdentityVerified: 'شناخت تصدیق گٔمٕت',
  verifyRedirecting: 'اپنہٕ ڈیش بورڈ مَنٛز ری ڈائریکٹ گَژھان…',
  verifyInvalidAadhaar: 'مہربانی کٔرِتھ درست 12 ہندر Aadhaar نمبر دِوٕ۔',
  verifyInvalidOtp: 'مہربانی کٔرِتھ 6 ہندر OTP دِوٕ یُس تہٕساز پؠٹھ آمِت۔',
  verifyInvalidMobile: 'مہربانی کٔرِتھ درست 10 ہندر موبائل نمبر دِوٕ۔',
  verifyFailedGenerate: 'OTP بَنٲوٕنہٕ مَنٛز ناکامی۔',
  verifyFailedVerify: 'تصدیق ناکام گٔی۔ مہربانی کٔرِتھ دوبارہ کوشش کرو۔',
  verifySpeakHint: 'مائیک دابو تہٕ پرو اپنہٕ Aadhaar یٲہ OTP',
  // dashboard
  dashWelcome: 'خوش آمدید',
  dashCitizen: 'شہری',
  dashVerified: 'تصدیق حالت: تصدیق شُدہٕ',
  dashPending: 'تصدیق حالت: زیر التوا',
  dashVerifyAadhaar: 'Aadhaar تصدیق کرو',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'باہر نِکلو',
  dashFoodSubsidy: 'خوراک سبسڈی (PDS)',
  dashDbt: 'سیدھہٕ فائدہٕ منتقلی (DBT)',
  dashEducation: 'تعلیم گرانٹ',
  dashHealth: 'صحت کوریج',
  dashNotEnrolled: 'داخل نہٕ',
  dashNextSocialAudit: 'اگلی سماجی آڈٹ',
  dashSocialAuditDesc: 'تہٕساز گامُک عوامی خَرچ جائزہٕ — سارنہٕ رہٲے وٲلن خٲطرٕ کھول۔',
  // admin
  adminAccess: 'ایڈمن رسائی',
  adminOversightPortal: 'وزارت نگرانی پورٹل',
  adminAccessPassword: 'رسائی پاس ورڈ',
  adminEnterPortal: 'پورٹل مَنٛز داخل گژھو',
  adminIncorrect: 'غلط پاس ورڈ۔ دوبارہ کوشش کرو۔',
  adminDemoPassword: 'ڈیمو پاس ورڈ:',
  adminRegistration: 'سرکاری رجسٹریشن',
  adminRegisterDesc: 'شکایت ڈیش بورڈ رسائی خٲطرٕ اپنہٕ نگرانی کردار رجسٹر کرو۔',
  adminFullName: 'پورو ناو',
  adminEmail: 'سرکاری ای میل',
  adminPhone: 'فون',
  adminPosition: 'عہدہٕ',
  adminState: 'ریاست',
  adminDistrict: 'ضلع',
  adminSelectState: 'ریاست چُنو',
  adminSelectDistrict: 'ضلع چُنو',
  adminRegisterContinue: 'رجسٹر کرو تہٕ جاری تھٲو',
  adminOversightDashboard: 'نگرانی ڈیش بورڈ',
  adminGrievanceIntelligence: 'شکایت انٹیلی جنس',
  adminAllDistricts: 'سارہٕ ضلع',
  adminExit: 'باہر',
  adminStatusDistribution: 'حالت تقسیم',
  adminByCategory: 'زمرہٕ وار شکایت',
  adminDistrictBreakdown: 'ضلع وار تفصیل',
  adminRecentGrievances: 'حالیہ شکایت',
  adminTotalGrievances: 'کل شکایت',
  adminOpen: 'کھول',
  adminNoGrievances: 'یہِ نظارہٕ مَنٛز کٔنٛہہ شکایت نہٕ۔',
  adminAiSummary: 'AI موضوع خلاصہٕ',
  adminAiNone: 'یہِ نظارہٕ خٲطرٕ کٔنٛہہ شکایت ریکارڈ نہٕ۔',
  adminPosDm: 'ضلعی مجسٹریٹ',
  adminPosBdo: 'بلاک ڈویلپمنٹ آفیسر',
  adminPosPanchayat: 'پنچایت سیکرٹری',
  adminPosWelfare: 'فلاحی آفیسر',
  adminPosAudit: 'سماجی آڈٹ کوآرڈینیٹر',
  adminPosState: 'ریاستی نوڈل آفیسر',
  adminPosManager: 'پروگرام مینیجر',
  // common
  commonSubmit: 'جمع کرو',
  commonCancel: 'منسوخ کرو',
  commonLoading: 'لوڈ گَژھان…',
}
