export const _kn = {
  // nav
  navFeatures: 'ವೈಶಿಷ್ಟ್ಯಗಳು',
  navOversight: 'ಮೇಲ್ವಿಚಾರಣೆ',
  navSignIn: 'ನಾವೇಶಿಸಿ',
  // hero
  heroBadge: 'ಕಲ್ಯಾಣ ನೀತಿ ಕಾರ್ಯರೂಪ',
  heroTitle1: 'ನಿಖರ ಆಡಳಿತ.',
  heroTitle2: 'ಮರುಕಲ್ಪನೆ.',
  heroSubtitle: 'ಸುರಕ್ಷಿತ, ನಾಗರಿಕ-ಪ್ರಥಮ ವೇದಿಕೆಯಲ್ಲಿ ನೈಜ-ಸಮಯದ ಡೇಟಾ, ವಿಕೇಂದ್ರೀಕೃತ ಗುರುತು ಮತ್ತು ನೇರ ವರ್ಗಾವಣೆಗಳು ಕಲ್ಯಾಣ ಸೌಲಭ್ಯಗಳನ್ನು ಸರಿಯಾದ ವ್ಯಕ್ತಿಗಳಿಗೆ ತಲುಪಿಸುತ್ತವೆ.',
  heroCta: 'ನಿಮ್ಮ Dashboard ತೆರೆಯಿರಿ',
  // features
  featuresBadge: 'ಸಾಮರ್ಥ್ಯಗಳು',
  featuresTitle: 'ಆಧುನಿಕ ಕಲ್ಯಾಣ ವ್ಯವಸ್ಥೆಗೆ ಬೇಕಾದೆಲ್ಲವೂ.',
  featuresSubtitle: 'ಒಂದು ಸಂಪರ್ಕಿತ ವೇದಿಕೆ ಗುರುತು, ಗುರಿಯಿಡುವಿಕೆ, ಪಾವತಿಗಳು ಮತ್ತು ಜವಾಬ್ದಾರಿಯನ್ನು ಏಕೀಕರಿಸುತ್ತದೆ.',
  tileDynamicRegistries: 'ಡೈನಾಮಿಕ್ ಸಾಮಾಜಿಕ-ಆರ್ಥಿಕ ನೋಂದಣಿಗಳು',
  tileDynamicRegistriesDesc: 'ತೆರಿಗೆ, ಸೌಲಭ್ಯ ಮತ್ತು ನಾಗರಿಕ ದಾಖಲೆಗಳಿಂದ ನಿರಂತರ ಅರ್ಹತಾ ನವೀಕರಣಗಳು — ಯಾವಾಗಲೂ ವಾಸ್ತವವನ್ನು ಪ್ರತಿಬಿಂಬಿಸುವ, ಹಳೆಯ ಜನಗಣತಿಯಲ್ಲದ ಗುರಿಯಿಡುವಿಕೆ.',
  tileBiometrics: 'ವಿಕೇಂದ್ರೀಕೃತ ಬಯೋಮೆಟ್ರಿಕ್ಸ್',
  tileBiometricsDesc: 'ಗುರುತು ವಂಚನೆ ಮತ್ತು ದ್ವಿಪಾತ್ರಿ ಪಡೆಯನ್ನು ಬಾಗಿಲಲ್ಲೇ ತಡೆಯುವ ಸುರಕ್ಷಿತ, ವಿಕೇಂದ್ರೀಕೃತ ಬಯೋಮೆಟ್ರಿಕ್ ಐಡಿಗಳು.',
  tileDbt: 'ನೇರ ಪ್ರಯೋಜನ (DBT) ವರ್ಗಾವಣೆಗಳು',
  tileDbtDesc: 'ನಗದು ಮತ್ತು ಸಬ್ಸಿಡಿಗಳು ಪರಿಶೀಲಿತ ನಾಗರಿಕ ಖಾತೆಗಳಿಗೆ ನೇರವಾಗಿ — ಮಧ್ಯವರ್ತಿಗಳಿಲ್ಲ.',
  tileConditional: 'ಷರತ್ತುಬದ್ಧ ವರ್ಗಾವಣೆಗಳು',
  tileConditionalDesc: 'ಅಳೆಯಬಹುದಾದ ಸಾಮಾಜಿಕ ಫಲಿತಾಂಶಗಳಿಗಾಗಿ ಶಿಕ್ಷಣ ಮತ್ತು ಆರೋಗ್ಯ ಮೈಲಿಗಲ್ಲುಗಳಿಗೆ ಸಂಬಂಧಿಸಿದ ಪಾವತಿಗಳು.',
  tileAudits: 'ಸಮುದಾಯ ಸಾಮಾಜಿಕ ಆಡಿಟ್‌ಗಳು',
  tileAuditsDesc: 'ನಾಗರಿಕರು ನೆಲದ ಮೇಲಿನ ಆಸ್ತಿಗಳ ವಿರುದ್ಧ ವೆಚ್ಚವನ್ನು ಪರೀಕ್ಷಿಸುವ ಸಾರ್ವಜನಿಕ ಸಭೆಗಳು.',
  tileAi: 'ಸ್ವಯಂಚಾಲಿತ ವಿನಾಯಿತಿ ವರದಿಗಳು',
  tileAiDesc: 'ಎಐ ಅನೇಕ ಪ್ರಯೋಜನ ಖಾತೆಗಳೊಂದಿಗೆ ಸಂಪರ್ಕಿತ ಏಕ ಫೋನ್ ಸಂಖ್ಯೆಯಂತಹ ಸಂಶಯಾಸ್ಪದ ನಮೂನೆಗಳನ್ನು ತ್ವರಿತ ತನಿಖೆಗಾಗಿ ಗುರುತಿಸುತ್ತದೆ.',
  // oversight
  oversightBadge: 'ಮಂತ್ರಾಲಯ ಮೇಲ್ವಿಚಾರಣೆ',
  oversightTitle: 'ಮಂತ್ರಾಲಯ ಚೌಕಟ್ಟು ಮತ್ತು ಮೂಲಸೌಕರ್ಯ',
  oversightSubtitle: 'ಮಂತ್ರಾಲಯಗಳು ಕಾನೂನು ಚೌಕಟ್ಟುಗಳನ್ನು ಸ್ಥಾಪಿಸುವುದು, ಮೇಲ್ವಿಚಾರಣಾ ಬಜೆಟ್‌ಗಳನ್ನು ನಿಯೋಜಿಸುವುದು, ಸುರಕ್ಷಿತ ಡೇಟಾ ವ್ಯವಸ್ಥೆಗಳನ್ನು ನಿರ್ವಹಿಸುವುದು ಮತ್ತು ದಂಡನೆಗಳನ್ನು ಜಾರಿಗೊಳಿಸುವ ಮೂಲಕ ಕಲ್ಯಾಣ ನೀತಿ ಆಡಿಟ್‌ಗಳನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡುತ್ತವೆ.',
  pillarAudit: 'ಕಡ್ಡಾಯ ಆಡಿಟ್ ಮಾರ್ಗಸೂಚಿಗಳು',
  pillarAuditDesc: 'ಸಾಮಾಜಿಕ ಮತ್ತು ಆರ್ಥಿಕ ಆಡಿಟ್‌ಗಳನ್ನು ಕಡ್ಡಾಯವಾಗಿಸುವ ಪ್ರಮಾಣಿತ ಕಾರ್ಯವಿಧಾನಗಳು ಮತ್ತು ಕಾನೂನು ಚೌಕಟ್ಟುಗಳು.',
  pillarMetrics: 'ಸ್ಪಷ್ಟ ಕಾರ್ಯಕ್ಷಮತಾ ಮಾನದಂಡಗಳು',
  pillarMetricsDesc: 'ಅಳೆಯಬಹುದಾದ ಮಾನದಂಡಗಳು — ಉದಾಹರಣೆಗೆ ಬೆಳವಣಿಗೆ ಕುಂಠಿತ ಅಥವಾ ನಿರುದ್ಯೋಗದ ನಿರ್ದಿಷ್ಟ ಇಳಿಕೆ ದರಗಳು.',
  pillarBodies: 'ಸ್ವತಂತ್ರ ಸಂಸ್ಥೆಗಳು',
  pillarBodiesDesc: 'ರಾಜಕೀಯ ಹಸ್ತಕ್ಷೇಪದ ವಿರುದ್ಧ ಮೂರನೇ-ಪಕ್ಷದ ಆಡಿಟರ್‌ಗಳು ಮತ್ತು ಸ್ಥಳೀಯ ಸಾಮಾಜಿಕ ಆಡಿಟ್ ಘಟಕಗಳಿಗೆ ಕಾನೂನು ರಕ್ಷಣೆಗಳು.',
  pillarDatabases: 'ಸುರಕ್ಷಿತ ಮಾಸ್ಟರ್ ಡೇಟಾಬೇಸ್‌ಗಳು',
  pillarDatabasesDesc: 'ಸ್ವಚ್ಛ ಡೇಟಾದೊಂದಿಗೆ ಕೇಂದ್ರೀಯ ಲಾಭಾರ್ಥಿ ನೋಂದಣಿಗಳು, ಅಧಿಕೃತ ಆಡಿಟ್ ಸಂಸ್ಥೆಗಳಿಗೆ ಮಾತ್ರ ಲಭ್ಯ.',
  // footer
  footerTagline: 'ಜನತಾ-ಪ್ರಥಮ ನೀತಿಗಾಗಿ ನಿಖರ ಆಡಳಿತ.',
  footerSub: 'ಡೈನಾಮಿಕ್ ನೋಂದಣಿಗಳು · ವಿಕೇಂದ್ರೀಕೃತ ಬಯೋಮೆಟ್ರಿಕ್ಸ್ · ನೇರ ಪ್ರಯೋಜನ ವರ್ಗಾವಣೆಗಳು',
  // login
  loginTitle: 'ಮತ್ತೆ ಸ್ವಾಗತ',
  loginSubtitle: 'ನಿಮ್ಮ ಸುರಕ್ಷಿತ ನಾಗರಿಕ Dashboard ಅನ್ನು ಪ್ರವೇಶಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ. ಹೊಸ ನಾಗರಿಕರನ್ನು ಎರಡು ನಿಮಿಷಗಳಲ್ಲಿ ನೋಂದಾಯಿಸಲಾಗುತ್ತದೆ.',
  loginContinueGoogle: 'Google ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ',
  loginContinueDemo: 'ಡೆಮೋ ಖಾತೆಯೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ',
  loginDemoHint: 'ಡೆಮೋ ಖಾತೆ',
  loginPresetLabel: 'ಡೆಮೋ ನಾಗರಿಕವನ್ನು ಶೀಘ್ರ ಭರ್ತಿ ಮಾಡಿ:',
  loginOrUse: 'ಅಥವಾ ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಬಳಸಿ',
  loginEmail: 'ಇಮೇಲ್',
  loginName: 'ಹೆಸರು',
  loginImage: 'ಚಿತ್ರ URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'ನಿಮ್ಮ Aadhaar ಅನ್ನು ಪರಿಶೀಲಿಸಿ',
  verifySubtitle: 'ಒಮ್ಮೆಯ ಗುರುತು ಪರಿಶೀಲನೆಯು ನಿಮ್ಮ ಕಲ್ಯಾಣ Dashboard ಅನ್ನು ತೆರೆಯುತ್ತದೆ.',
  verifyAadhaarLabel: '12-ಅಂಕಿಯ Aadhaar ಸಂಖ್ಯೆ',
  verifyMobileLabel: 'OTP ಸ್ವೀಕರಿಸಲು ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
  verifyGenerateOtp: 'OTP ರಚಿಸಿ',
  verifySendingOtp: 'OTP ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ…',
  verifyDemoNote: 'ಡೆಮೋ ಮೋಡ್ — OTP ವಿನಂತಿಯು ಅನುಕರಿಸಲ್ಪಟ್ಟಿದೆ. ಯಾವುದೇ ನಿಜವಾದ Aadhaar ಡೇಟಾ ಕಳುಹಿಸಲ್ಪಡುವುದಿಲ್ಲ.',
  verifyOtpSentTo: 'ನಿಮ್ಮ ನೋಂದಾಯಿತ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಗೆ OTP ಕಳುಹಿಸಲಾಗಿದೆ',
  verifyDemoOtpLabel: 'ಡೆಮೋ OTP:',
  verifyDemoOtpNote: 'ನಿಜವಾದ ನಿಯೋಜನೆಯು ಇದನ್ನು SMS ಮೂಲಕ ಕಳುಹಿಸುತ್ತದೆ — ಪರೀಕ್ಷೆಗಾಗಿ ಇಲ್ಲಿ ತೋರಿಸಲಾಗಿದೆ.',
  verifyOtpLabel: '6-ಅಂಕಿಯ OTP',
  verifyVerifyOtp: 'OTP ಪರಿಶೀಲಿಸಿ',
  verifyVerifying: 'ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ…',
  verifyChangeAadhaar: 'Aadhaar ಸಂಖ್ಯೆ ಬದಲಾಯಿಸಿ',
  verifyIdentityVerified: 'ಗುರುತು ಪರಿಶೀಲಿತವಾಗಿದೆ',
  verifyRedirecting: 'ನಿಮ್ಮ Dashboard ಗೆ ಮರುನಿರ್ದೇಶಿಸಲಾಗುತ್ತಿದೆ…',
  verifyInvalidAadhaar: 'ದಯವಿಟ್ಟು ಮಾನ್ಯ 12-ಅಂಕಿಯ Aadhaar ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.',
  verifyInvalidOtp: 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಫೋನ್‌ಗೆ ಕಳುಹಿಸಲಾದ 6-ಅಂಕಿಯ OTP ಅನ್ನು ನಮೂದಿಸಿ.',
  verifyInvalidMobile: 'ದಯವಿಟ್ಟು ಮಾನ್ಯ 10-ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.',
  verifyFailedGenerate: 'OTP ರಚಿಸುವಲ್ಲಿ ವಿಫಲವಾಗಿದೆ.',
  verifyFailedVerify: 'ಪರಿಶೀಲನೆ ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  verifySpeakHint: 'ಮೈಕ್ ಅನ್ನು ಟ್ಯಾಪ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ Aadhaar ಅಥವಾ OTP ಹೇಳಿ',
  // dashboard
  dashWelcome: 'ಸ್ವಾಗತ',
  dashCitizen: 'ನಾಗರಿಕ',
  dashVerified: 'ಪರಿಶೀಲನಾ ಸ್ಥಿತಿ: ಪರಿಶೀಲಿತ',
  dashPending: 'ಪರಿಶೀಲನಾ ಸ್ಥಿತಿ: ಬಾಕಿ',
  dashVerifyAadhaar: 'Aadhaar ಪರಿಶೀಲಿಸಿ',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'ಸೈನ್ ಔಟ್',
  dashFoodSubsidy: 'ಆಹಾರ ಸಬ್ಸಿಡಿ (PDS)',
  dashDbt: 'ನೇರ ಪ್ರಯೋಜನ ವರ್ಗಾವಣೆ (DBT)',
  dashEducation: 'ಶಿಕ್ಷಣ ಅನುದಾನ',
  dashHealth: 'ಆರೋಗ್ಯ ವ್ಯಾಪ್ತಿ',
  dashNotEnrolled: 'ನೋಂದಾಯಿಸಿಲ್ಲ',
  dashNextSocialAudit: 'ಮುಂದಿನ ಸಾಮಾಜಿಕ ಆಡಿಟ್',
  dashSocialAuditDesc: 'ನಿಮ್ಮ ಹಳ್ಳಿಯ ಸಾರ್ವಜನಿಕ ವೆಚ್ಚ ಪರಿಶೀಲನೆ — ಎಲ್ಲಾ ನಿವಾಸಿಗಳಿಗೆ ತೆರೆದಿದೆ.',
  // admin
  adminAccess: 'ನಿರ್ವಾಹಕ ಪ್ರವೇಶ',
  adminOversightPortal: 'ಮಂತ್ರಾಲಯ ಮೇಲ್ವಿಚಾರಣಾ ಪೋರ್ಟಲ್',
  adminAccessPassword: 'ಪ್ರವೇಶ ಪಾಸ್‌ವರ್ಡ್',
  adminEnterPortal: 'ಪೋರ್ಟಲ್ ಪ್ರವೇಶಿಸಿ',
  adminIncorrect: 'ತಪ್ಪಾದ ಪಾಸ್‌ವರ್ಡ್. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  adminDemoPassword: 'ಡೆಮೋ ಪಾಸ್‌ವರ್ಡ್:',
  adminRegistration: 'ಅಧಿಕೃತ ನೋಂದಣಿ',
  adminRegisterDesc: 'ದೂರು Dashboard ಅನ್ನು ಪ್ರವೇಶಿಸಲು ನಿಮ್ಮ ಮೇಲ್ವಿಚಾರಣಾ ಪಾತ್ರವನ್ನು ನೋಂದಾಯಿಸಿ.',
  adminFullName: 'ಪೂರ್ಣ ಹೆಸರು',
  adminEmail: 'ಅಧಿಕೃತ ಇಮೇಲ್',
  adminPhone: 'ಫೋನ್',
  adminPosition: 'ಹುದ್ದೆ',
  adminState: 'ರಾಜ್ಯ',
  adminDistrict: 'ಜಿಲ್ಲೆ',
  adminSelectState: 'ರಾಜ್ಯ ಆಯ್ಕೆ ಮಾಡಿ',
  adminSelectDistrict: 'ಜಿಲ್ಲೆ ಆಯ್ಕೆ ಮಾಡಿ',
  adminRegisterContinue: 'ನೋಂದಾಯಿಸಿ ಮತ್ತು ಮುಂದುವರಿಯಿರಿ',
  adminOversightDashboard: 'ಮೇಲ್ವಿಚಾರಣಾ Dashboard',
  adminGrievanceIntelligence: 'ದೂರು ಬುದ್ಧಿಮತ್ತೆ',
  adminAllDistricts: 'ಎಲ್ಲಾ ಜಿಲ್ಲೆಗಳು',
  adminExit: 'ನಿರ್ಗಮಿಸಿ',
  adminStatusDistribution: 'ಸ್ಥಿತಿ ವಿತರಣೆ',
  adminByCategory: 'ವರ್ಗದ ಪ್ರಕಾರ ದೂರುಗಳು',
  adminDistrictBreakdown: 'ಜಿಲ್ಲಾ ವಿವರಣೆ',
  adminRecentGrievances: 'ಇತ್ತೀಚಿನ ದೂರುಗಳು',
  adminTotalGrievances: 'ಒಟ್ಟು ದೂರುಗಳು',
  adminOpen: 'ತೆರೆದ',
  adminNoGrievances: 'ಈ ನೋಟದಲ್ಲಿ ಯಾವುದೇ ದೂರುಗಳಿಲ್ಲ.',
  adminAiSummary: 'ಎಐ ವಿಷಯ ಸಾರಾಂಶ',
  adminAiNone: 'ಈ ನೋಟಕ್ಕಾಗಿ ಯಾವುದೇ ದೂರುಗಳು ದಾಖಲಾಗಿಲ್ಲ.',
  adminPosDm: 'ಜಿಲ್ಲಾ ಮ್ಯಾಜಿಸ್ಟ್ರೇಟ್',
  adminPosBdo: 'ಬ್ಲಾಕ್ ಅಭಿವೃದ್ಧಿ ಅಧಿಕಾರಿ',
  adminPosPanchayat: 'ಪಂಚಾಯತ್ ಕಾರ್ಯದರ್ಶಿ',
  adminPosWelfare: 'ಕಲ್ಯಾಣ ಅಧಿಕಾರಿ',
  adminPosAudit: 'ಸಾಮಾಜಿಕ ಆಡಿಟ್ ಸಂಯೋಜಕ',
  adminPosState: 'ರಾಜ್ಯ ನೋಡಲ್ ಅಧಿಕಾರಿ',
  adminPosManager: 'ಕಾರ್ಯಕ್ರಮ ವ್ಯವಸ್ಥಾಪಕ',
  // common
  commonSubmit: 'ಸಲ್ಲಿಸಿ',
  commonCancel: 'ರದ್ದು ಮಾಡಿ',
  commonLoading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ…',
}
