export const _kok = {
  // nav
  navFeatures: 'वैशिष्ट्यां',
  navOversight: 'देखरेख',
  navSignIn: 'सैन इन करात',
  // hero
  heroBadge: 'कल्याण धोरण अंमलबजावणी',
  heroTitle1: 'अचूक राजकारण.',
  heroTitle2: 'पुनर्कल्पना केल्लें.',
  heroSubtitle: 'एक सुरक्षित, नागरिक-प्रथम वेवस्था जिंतून रियल-टाइम डेटा, विकेंद्रित ओळख, आनी थेट हस्तांतरण हांच्यान कल्याण लाभ अचूक त्याच लोकांक मेळतात.',
  heroCta: 'आपलें Dashboard पळयात',
  // features
  featuresBadge: 'क्षमताय',
  featuresTitle: 'आधुनिक कल्याण वेवस्थेक जाय तीं सगळीं.',
  featuresSubtitle: 'एक संयोजित वेवस्था ओळख, लक्ष्यबद्धता, पेमेंट आनी जबाबदारकाय हांची एकी करता.',
  tileDynamicRegistries: 'गतिशील सामाजिक-आर्थिक नोंदणी',
  tileDynamicRegistriesDesc: 'कर, उपयोगिता, आनी नागरी नोंदींतल्यान सतत पात्रता अद्यतनां — लक्ष्यबद्धता जी नेहमीं वास्तव दाखयता, कधींच जुनें शुमारी न्हय.',
  tileBiometrics: 'विकेंद्रित बायोमेट्रिक्स',
  tileBiometricsDesc: 'सुरक्षित, विकेंद्रित बायोमेट्रिक ओळख जी दाराचेरच ओळख फसवणूक आनी दुप्पट लाभ घेवप बंद करता.',
  tileDbt: 'DBT',
  tileDbtDesc: 'रोख आनी अनुदान थेट प्रमाणीत नागरिक खात्यांनी — शून्य मध्यस्थ.',
  tileConditional: 'अटींचेर आदारीत हस्तांतरण',
  tileConditionalDesc: 'शिक्षण आनी आरोग्य टप्प्यांक जोडिल्ले पेमेंट मोजपांत येवपी सामाजिक परिणामां खातीर.',
  tileAudits: 'समुदाय सामाजिक लेखापरीक्षा',
  tileAuditsDesc: 'सार्वजनिक सभा जिंतून नागरिक जमिनीर आशिल्ल्या मालमत्ते विरूद्ध खर्चाची चवकशी करतात.',
  tileAi: 'स्वयंचलित अपवाद अहवाल',
  tileAiDesc: 'AI शंकास्पद नमुने चिन्नांकित करता — जशें एकाच फोन नंबराकडेन अनेक लाभ खातीं जोडिल्लीं — तत्काळ तपासणी खातीर.',
  // oversight
  oversightBadge: 'मंत्रालय देखरेख',
  oversightTitle: 'मंत्रालय चौकट आनी पायाभूत सुविधा',
  oversightSubtitle: 'मंत्रालयां कायदेशीर चौकटी स्थापन करून, देखरेख अर्थसंकल्प नेमून, सुरक्षित डेटा वेवस्था राखून, आनी दंड लागू करून कल्याण धोरण लेखापरीक्षणाची देखरेख करतात.',
  pillarAudit: 'बंधनकारक लेखापरीक्षण मार्गदर्शक तत्त्वां',
  pillarAuditDesc: 'स्टँडर्ड ऑपरेटिंग प्रक्रिया आनी कायदेशीर चौकटी जांच्यान सामाजिक आनी आर्थिक लेखापरीक्षण बंधनकारक जाता.',
  pillarMetrics: 'स्पष्ट कामगिरी मापदंड',
  pillarMetricsDesc: 'मोजपांत येवपी निकष — जशें स्टंटिंग वा बेरोजगारींत विशिष्ट कपात दर.',
  pillarBodies: 'स्वतंत्र संस्था',
  pillarBodiesDesc: 'तृतीय-पक्ष लेखापरीक्षक आनी स्थानिक सामाजिक लेखापरीक्षण युनिटांखातीर राजकीय हस्तक्षेपा विरूद्ध कायदेशीर संरक्षण.',
  pillarDatabases: 'सुरक्षित मास्टर डेटाबेस',
  pillarDatabasesDesc: 'केंद्रीय लाभार्थी नोंदणी स्वच्छ डेटा सयत, जी फकत अधिकृत लेखापरीक्षण संस्थांक पळोवपाक मेळता.',
  // footer
  footerTagline: 'लोक-प्रथम धोरणाखातीर अचूक राजकारण.',
  footerSub: 'गतिशील नोंदणी · विकेंद्रित बायोमेट्रिक्स · थेट लाभ हस्तांतरण',
  // login
  loginTitle: 'परत येवन स्वागत आसा',
  loginSubtitle: 'आपलें सुरक्षित नागरिक Dashboard प्रवेश करपाखातीर सैन इन करात. नवे नागरिक दोन मिनटां भितर ऑनबोर्ड जातात.',
  loginContinueGoogle: 'Google सयत चालू दवरात',
  loginContinueDemo: 'डेमो खात्या सयत चालू दवरात',
  loginDemoHint: 'डेमो खातें',
  loginPresetLabel: 'डेमो नागरिक जल्द भरात:',
  loginOrUse: 'वा आपले तपशील वापरात',
  loginEmail: 'ईमेल',
  loginName: 'नाव',
  loginImage: 'प्रतिमा URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'आपलें Aadhaar प्रमाणीत करात',
  verifySubtitle: 'एकदम ओळख प्रमाणीकरण आपलें कल्याण Dashboard अनलॉक करता.',
  verifyAadhaarLabel: '12-अंकी Aadhaar नंबर',
  verifyMobileLabel: 'OTP मेळपाखातीर मोबाइल नंबर',
  verifyGenerateOtp: 'OTP तयार करात',
  verifySendingOtp: 'OTP धाडपाचें आसा…',
  verifyDemoNote: 'डेमो मोड — OTP विनवणी सिम्युलेट केल्ली. खरें Aadhaar डेटा प्रसारित जायना.',
  verifyOtpSentTo: 'आपल्या नोंदणीकृत मोबाइल नंबराक OTP धाडला:',
  verifyDemoOtpLabel: 'डेमो OTP:',
  verifyDemoOtpNote: 'खरी डिप्लॉयमेंट हें SMS वरवीं धाडटा — चाचणी खातीर हांगा दाखयलां.',
  verifyOtpLabel: '6-अंकी OTP',
  verifyVerifyOtp: 'OTP प्रमाणीत करात',
  verifyVerifying: 'प्रमाणीत करता…',
  verifyChangeAadhaar: 'Aadhaar नंबर बदलात',
  verifyIdentityVerified: 'ओळख प्रमाणीत जाली',
  verifyRedirecting: 'आपल्या Dashboard कडेन वळपाचें…',
  verifyInvalidAadhaar: 'कृपया वैध 12-अंकी Aadhaar नंबर भरात.',
  verifyInvalidOtp: 'कृपया आपल्या फोनाक धाडिल्लो 6-अंकी OTP भरात.',
  verifyInvalidMobile: 'कृपया वैध 10-अंकी मोबाइल नंबर भरात.',
  verifyFailedGenerate: 'OTP तयार करपाक अपेश आयलो.',
  verifyFailedVerify: 'प्रमाणीकरण अयशस्वी. कृपया परत प्रयत्न करात.',
  verifySpeakHint: 'मायक्रोफोनाचेर थाप मारात आनी आपलो Aadhaar वा OTP उलयात',
  // dashboard
  dashWelcome: 'स्वागत',
  dashCitizen: 'नागरिक',
  dashVerified: 'प्रमाणीकरण स्थिती: प्रमाणीत',
  dashPending: 'प्रमाणीकरण स्थिती: प्रलंबित',
  dashVerifyAadhaar: 'Aadhaar प्रमाणीत करात',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'सैन आउट करात',
  dashFoodSubsidy: 'अन्न अनुदान (PDS)',
  dashDbt: 'DBT',
  dashEducation: 'शिक्षण अनुदान',
  dashHealth: 'आरोग्य विमा',
  dashNotEnrolled: 'नोंदणी ना',
  dashNextSocialAudit: 'फुडले सामाजिक लेखापरीक्षण',
  dashSocialAuditDesc: 'आपल्या गांवचो सार्वजनिक खर्च परिक्षण — सगळ्या रहिवाशांक खुल्लें.',
  // admin
  adminAccess: 'प्रशासक प्रवेश',
  adminOversightPortal: 'मंत्रालय देखरेख पोर्टल',
  adminAccessPassword: 'प्रवेश पासवर्ड',
  adminEnterPortal: 'पोर्टल प्रवेश करात',
  adminIncorrect: 'चूक पासवर्ड. परत प्रयत्न करात.',
  adminDemoPassword: 'डेमो पासवर्ड:',
  adminRegistration: 'अधिकृत नोंदणी',
  adminRegisterDesc: 'तक्रार Dashboard प्रवेश करपाखातीर आपली देखरेख भूमिका नोंदणी करात.',
  adminFullName: 'पुराय नाव',
  adminEmail: 'अधिकृत ईमेल',
  adminPhone: 'फोन',
  adminPosition: 'पद',
  adminState: 'राज्य',
  adminDistrict: 'जिल्हो',
  adminSelectState: 'राज्य निवडात',
  adminSelectDistrict: 'जिल्हो निवडात',
  adminRegisterContinue: 'नोंदणी करात आनी चालू दवरात',
  adminOversightDashboard: 'देखरेख Dashboard',
  adminGrievanceIntelligence: 'तक्रार बुद्धिमत्ता',
  adminAllDistricts: 'सगळे जिल्हे',
  adminExit: 'बाहेर पडात',
  adminStatusDistribution: 'स्थिती वितरण',
  adminByCategory: 'श्रेणी प्रमाणें तक्रारी',
  adminDistrictBreakdown: 'जिल्हो विवरण',
  adminRecentGrievances: 'अलीकडींच्यो तक्रारी',
  adminTotalGrievances: 'एकूण तक्रारी',
  adminOpen: 'उक्तें',
  adminNoGrievances: 'ह्या दृश्यांत तक्रारी नात.',
  adminAiSummary: 'AI विषय सारांश',
  adminAiNone: 'ह्या दृश्याखातीर कोणय तक्रार नोंदयल्या नात.',
  adminPosDm: 'जिल्हाधिकारी',
  adminPosBdo: 'ब्लॉक विकास अधिकारी',
  adminPosPanchayat: 'पंचायत सचिव',
  adminPosWelfare: 'कल्याण अधिकारी',
  adminPosAudit: 'सामाजिक लेखापरीक्षण समन्वयक',
  adminPosState: 'राज्य नोडल अधिकारी',
  adminPosManager: 'कार्यक्रम व्यवस्थापक',
  // common
  commonSubmit: 'सादर करात',
  commonCancel: 'रद्द करात',
  commonLoading: 'लोड जाता…',
}
