export const _mni = {
  // nav
  navFeatures: 'ফিচারসমূহ',
  navOversight: 'নিরীক্ষণ',
  navSignIn: 'সাইন ইন',
  // hero
  heroBadge: 'কল্যাণ নীতি কার্যকরীকরণ',
  heroTitle1: 'নিখুঁত শাসন।',
  heroTitle2: 'পুনর্বিন্যাসিত।',
  heroSubtitle: 'একটি সুরক্ষিত, নাগরিক-প্রথম প্ল্যাটফর্ম যেখানে রিয়েল-টাইম ডেটা, বিকেন্দ্রীভূত পরিচয় এবং সরাসরি স্থানান্তর সঠিক ব্যক্তির কাছে কল্যাণ সুবিধা পৌঁছে দেয়।',
  heroCta: 'আপনার ড্যাশবোর্ড অ্যাক্সেস করুন',
  // features
  featuresBadge: 'ক্ষমতাসমূহ',
  featuresTitle: 'একটি আধুনিক কল্যাণ ব্যবস্থার যা প্রয়োজন তার সবকিছু।',
  featuresSubtitle: 'একটি সংযুক্ত প্ল্যাটফর্ম পরিচয়, লক্ষ্যবস্তু, পেমেন্ট এবং জবাবদিহিতাকে একীভূত করে।',
  tileDynamicRegistries: 'গতিশীল সামাজিক-অর্থনৈতিক রেজিস্ট্রি',
  tileDynamicRegistriesDesc: 'কর, ইউটিলিটি এবং সিভিল রেকর্ড থেকে ধারাবাহিক যোগ্যতা আপডেট — এমন লক্ষ্যবস্তু যা সর্বদা বাস্তবতা প্রতিফলিত করে, কখনও পুরানো আদমশুমারি নয়।',
  tileBiometrics: 'বিকেন্দ্রীভূত বায়োমেট্রিকস',
  tileBiometricsDesc: 'নিরাপদ, বিকেন্দ্রীভূত বায়োমেট্রিক পরিচয় যা দরজায় পরিচয় জালিয়াতি এবং ডবল-ডিপিং বন্ধ করে।',
  tileDbt: 'সরাসরি সুবিধা স্থানান্তর (DBT)',
  tileDbtDesc: 'নগদ এবং ভর্তুকি যাচাইকৃত নাগরিক অ্যাকাউন্টে সরাসরি রুট করা হয় — কোনও মধ্যস্থতাকারী নেই।',
  tileConditional: 'শর্তসাপেক্ষ স্থানান্তর',
  tileConditionalDesc: 'পরিমাপযোগ্য সামাজিক ফলাফলের জন্য শিক্ষা এবং স্বাস্থ্য মাইলফলকের সাথে যুক্ত পেআউট।',
  tileAudits: 'কমিউনিটি সামাজিক নিরীক্ষা',
  tileAuditsDesc: 'জনসভা যেখানে নাগরিকরা মাটিতে থাকা সম্পদের বিপরীতে ব্যয় পরীক্ষা করে।',
  tileAi: 'স্বয়ংক্রিয় ব্যতিক্রম রিপোর্ট',
  tileAiDesc: 'AI সন্দেহজনক প্যাটার্ন চিহ্নিত করে — যেমন একাধিক সুবিধা অ্যাকাউন্টের সাথে যুক্ত একটি মোবাইল নম্বর — তাৎক্ষণিক তদন্তের জন্য।',
  // oversight
  oversightBadge: 'মন্ত্রণালয় নিরীক্ষণ',
  oversightTitle: 'মন্ত্রণালয় কাঠামো এবং অবকাঠামো',
  oversightSubtitle: 'মন্ত্রণালয়গুলি আইনি কাঠামো প্রতিষ্ঠা, নিরীক্ষণ বাজেট বরাদ্দ, নিরাপদ ডেটা সিস্টেম বজায় রাখা এবং জরিমানা প্রয়োগ করে কল্যাণ নীতি নিরীক্ষা তত্ত্বাবধান করে।',
  pillarAudit: 'বাধ্যতামূলক নিরীক্ষা নির্দেশিকা',
  pillarAuditDesc: 'সামাজিক এবং আর্থিক নিরীক্ষাকে বাধ্যতামূলক করে এমন স্ট্যান্ডার্ড অপারেটিং পদ্ধতি এবং আইনি কাঠামো।',
  pillarMetrics: 'স্পষ্ট কর্মক্ষমতা মেট্রিক্স',
  pillarMetricsDesc: 'পরিমাপযোগ্য বেঞ্চমার্ক — যেমন স্টান্টিং বা বেকারত্বের নির্দিষ্ট হ্রাস হার।',
  pillarBodies: 'স্বাধীন সংস্থা',
  pillarBodiesDesc: 'তৃতীয়-পক্ষের অডিটর এবং স্থানীয় সামাজিক নিরীক্ষা ইউনিটের বিরুদ্ধে রাজনৈতিক হস্তক্ষেপ থেকে আইনি সুরক্ষা।',
  pillarDatabases: 'নিরাপদ মাস্টার ডেটাবেস',
  pillarDatabasesDesc: 'পরিষ্কার ডেটা সহ কেন্দ্রীয় উপকারভোগী রেজিস্ট্রি, যা শুধুমাত্র অনুমোদিত নিরীক্ষা সংস্থার জন্য অ্যাক্সেসযোগ্য।',
  // footer
  footerTagline: 'মানুষ-প্রথম নীতির জন্য নিখুঁত শাসন।',
  footerSub: 'গতিশীল রেজিস্ট্রি · বিকেন্দ্রীভূত বায়োমেট্রিকস · সরাসরি সুবিধা স্থানান্তর',
  // login
  loginTitle: 'স্বাগতম',
  loginSubtitle: 'আপনার নিরাপদ নাগরিক ড্যাশবোর্ড অ্যাক্সেস করতে সাইন ইন করুন। নতুন নাগরিকরা দুই মিনিটের মধ্যে অনবোর্ড করা হয়।',
  loginContinueGoogle: 'Google দিয়ে চালিয়ে যান',
  loginContinueDemo: 'ডেমো অ্যাকাউন্ট দিয়ে চালিয়ে যান',
  loginDemoHint: 'ডেমো অ্যাকাউন্ট',
  loginPresetLabel: 'দ্রুত একটি ডেমো নাগরিক পূরণ করুন:',
  loginOrUse: 'অথবা আপনার বিবরণ ব্যবহার করুন',
  loginEmail: 'ইমেইল',
  loginName: 'নাম',
  loginImage: 'ছবির URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'আপনার Aadhaar যাচাই করুন',
  verifySubtitle: 'একবারের পরিচয় যাচাইকরণ আপনার কল্যাণ ড্যাশবোর্ড আনলক করে।',
  verifyAadhaarLabel: '১২-সংখ্যার Aadhaar নম্বর',
  verifyMobileLabel: 'OTP পেতে মোবাইল নম্বর',
  verifyGenerateOtp: 'OTP তৈরি করুন',
  verifySendingOtp: 'OTP পাঠানো হচ্ছে…',
  verifyDemoNote: 'ডেমো মোড — OTP অনুরোধটি সিমুলেট করা হয়েছে। কোনও বাস্তব Aadhaar ডেটা প্রেরণ করা হয় না।',
  verifyOtpSentTo: 'আপনার নিবন্ধিত মোবাইল নম্বরে OTP পাঠানো হয়েছে',
  verifyDemoOtpLabel: 'ডেমো OTP:',
  verifyDemoOtpNote: 'প্রকৃত ডিপ্লয়মেন্ট এটি SMS এর মাধ্যমে পাঠায় — পরীক্ষার জন্য এখানে দেখানো হয়েছে।',
  verifyOtpLabel: '৬-সংখ্যার OTP',
  verifyVerifyOtp: 'OTP যাচাই করুন',
  verifyVerifying: 'যাচাই করা হচ্ছে…',
  verifyChangeAadhaar: 'Aadhaar নম্বর পরিবর্তন করুন',
  verifyIdentityVerified: 'পরিচয় যাচাই করা হয়েছে',
  verifyRedirecting: 'আপনার ড্যাশবোর্ডে রিডাইরেক্ট করা হচ্ছে…',
  verifyInvalidAadhaar: 'অনুগ্রহ করে একটি বৈধ ১২-সংখ্যার Aadhaar নম্বর লিখুন।',
  verifyInvalidOtp: 'অনুগ্রহ করে আপনার ফোনে পাঠানো ৬-সংখ্যার OTP লিখুন।',
  verifyInvalidMobile: 'অনুগ্রহ করে একটি বৈধ ১০-সংখ্যার মোবাইল নম্বর লিখুন।',
  verifyFailedGenerate: 'OTP তৈরি করতে ব্যর্থ।',
  verifyFailedVerify: 'যাচাইকরণ ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।',
  verifySpeakHint: 'মাইকে ট্যাপ করুন এবং আপনার Aadhaar বা OTP বলুন',
  // dashboard
  dashWelcome: 'স্বাগতম',
  dashCitizen: 'নাগরিক',
  dashVerified: 'যাচাইকরণ অবস্থা: যাচাইকৃত',
  dashPending: 'যাচাইকরণ অবস্থা: মুলতুবি',
  dashVerifyAadhaar: 'Aadhaar যাচাই করুন',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'সাইন আউট',
  dashFoodSubsidy: 'খাদ্য ভর্তুকি (PDS)',
  dashDbt: 'সরাসরি সুবিধা স্থানান্তর (DBT)',
  dashEducation: 'শিক্ষা অনুদান',
  dashHealth: 'স্বাস্থ্য কভারেজ',
  dashNotEnrolled: 'নাম নিবন্ধিত নয়',
  dashNextSocialAudit: 'পরবর্তী সামাজিক নিরীক্ষা',
  dashSocialAuditDesc: 'আপনার গ্রামের জনসাধারণের ব্যয় পর্যালোচনা — সকল বাসিন্দার জন্য উন্মুক্ত।',
  // admin
  adminAccess: 'অ্যাডমিন অ্যাক্সেস',
  adminOversightPortal: 'মন্ত্রণালয় নিরীক্ষণ পোর্টাল',
  adminAccessPassword: 'অ্যাক্সেস পাসওয়ার্ড',
  adminEnterPortal: 'পোর্টালে প্রবেশ করুন',
  adminIncorrect: 'ভুল পাসওয়ার্ড। আবার চেষ্টা করুন।',
  adminDemoPassword: 'ডেমো পাসওয়ার্ড:',
  adminRegistration: 'অফিসিয়াল নিবন্ধন',
  adminRegisterDesc: 'অভিযোগ ড্যাশবোর্ড অ্যাক্সেস করতে আপনার নিরীক্ষণ ভূমিকা নিবন্ধন করুন।',
  adminFullName: 'পূর্ণ নাম',
  adminEmail: 'অফিসিয়াল ইমেইল',
  adminPhone: 'ফোন',
  adminPosition: 'পদ',
  adminState: 'রাজ্য',
  adminDistrict: 'জেলা',
  adminSelectState: 'রাজ্য নির্বাচন করুন',
  adminSelectDistrict: 'জেলা নির্বাচন করুন',
  adminRegisterContinue: 'নিবন্ধন করুন এবং চালিয়ে যান',
  adminOversightDashboard: 'নিরীক্ষণ ড্যাশবোর্ড',
  adminGrievanceIntelligence: 'অভিযোগ ইন্টেলিজেন্স',
  adminAllDistricts: 'সকল জেলা',
  adminExit: 'প্রস্থান',
  adminStatusDistribution: 'অবস্থা বিতরণ',
  adminByCategory: 'বিভাগ অনুযায়ী অভিযোগ',
  adminDistrictBreakdown: 'জেলা বিভাজন',
  adminRecentGrievances: 'সাম্প্রতিক অভিযোগ',
  adminTotalGrievances: 'মোট অভিযোগ',
  adminOpen: 'খোলা',
  adminNoGrievances: 'এই ভিউতে কোনও অভিযোগ নেই।',
  adminAiSummary: 'AI বিষয় সারাংশ',
  adminAiNone: 'এই ভিউয়ের জন্য কোনও অভিযোগ রেকর্ড করা হয়নি।',
  adminPosDm: 'জেলা ম্যাজিস্ট্রেট',
  adminPosBdo: 'ব্লক ডেভেলপমেন্ট অফিসার',
  adminPosPanchayat: 'পঞ্চায়েত সচিব',
  adminPosWelfare: 'কল্যাণ অফিসার',
  adminPosAudit: 'সামাজিক নিরীক্ষা সমন্বয়ক',
  adminPosState: 'রাজ্য নোডাল অফিসার',
  adminPosManager: 'প্রোগ্রাম ম্যানেজার',
  // common
  commonSubmit: 'জমা দিন',
  commonCancel: 'বাতিল করুন',
  commonLoading: 'লোড হচ্ছে…',
}
