export const _mai = {
  // nav
  navFeatures: 'सुविधासभ',
  navOversight: 'निगरानी',
  navSignIn: 'साइन इन',
  // hero
  heroBadge: 'कल्याण नीति कार्यान्वयन',
  heroTitle1: 'शुद्ध शासन।',
  heroTitle2: 'पुनः कल्पना कएल गेल।',
  heroSubtitle: 'एकटा सुरक्षित, नागरिक-प्रथम मंच जतए वास्तविक-समय डेटा, विकेन्द्रीकृत पहिचान, आओर प्रत्यक्ष अंतरण द्वारा कल्याण लाभ ठीक ओहि लोकधक पहुँचैत अछि जिनका चाही।',
  heroCta: 'अपन डैशबोर्ड एक्सेस करू',
  // features
  featuresBadge: 'क्षमतासभ',
  featuresTitle: 'एकटा आधुनिक कल्याण प्रणाली केर लेल जे किछु आवश्यक अछि।',
  featuresSubtitle: 'एकटा जुड़ल मंच पहिचान, लक्ष्यीकरण, भुगतान, आओर जवाबदेही केँ एकीकृत करैत अछि।',
  tileDynamicRegistries: 'गतिशील सामाजिक-आर्थिक रजिस्ट्री',
  tileDynamicRegistriesDesc: 'कर, उपयोगिता, आओर नागरिक रिकॉर्ड सँ निरंतर पात्रता अद्यतन — एहन लक्ष्यीकरण जे हमेशा वास्तविकता केँ दर्शाबैत अछि, कखनो पुरान जनगणना नहि।',
  tileBiometrics: 'विकेन्द्रीकृत बायोमेट्रिक्स',
  tileBiometricsDesc: 'सुरक्षित, विकेन्द्रीकृत बायोमेट्रिक पहिचान जे द्वार पर ही पहिचान धोखाधड़ी आओर डबल-डिपिंग केँ रोकैत अछि।',
  tileDbt: 'प्रत्यक्ष लाभ अंतरण (DBT)',
  tileDbtDesc: 'नगद आओर सब्सिडी सीधा सत्यापित नागरिक खातासभ मे — कोनो बिचौलिया केर बिना।',
  tileConditional: 'शर्तीय अंतरण',
  tileConditionalDesc: 'शिक्षा आओर स्वास्थ्य माइलस्टोन सँ जुड़ल भुगतान मापनीय सामाजिक परिणाम लेल।',
  tileAudits: 'सामुदायिक सामाजिक लेखा-जोखा',
  tileAuditsDesc: 'सार्वजनिक सभा जतए नागरिक जमीनी संपत्ति कँ खर्च कँ लेल क्रॉस-परीक्षण करैत छथि।',
  tileAi: 'स्वचालित अपवाद रिपोर्ट',
  tileAiDesc: 'AI संदिग्ध पैटर्न केँ झंडा देखाबैत अछि — जहिना एकटा फोन नंबर अनेकौं लाभ खातासभ सँ जुड़ल — तुरंत जाँच लेल।',
  // oversight
  oversightBadge: 'मंत्रालय निगरानी',
  oversightTitle: 'मंत्रालय ढाँचा आओर बुनियादी ढाँचा',
  oversightSubtitle: 'मंत्रालय कानूनी ढाँचा स्थापित कए, निगरानी बजट आवंटित कए, सुरक्षित डेटा प्रणाली बनाबिकए, आओर दंड लागू कए कल्याण नीति लेखा-जोखा कँ देखैत छथि।',
  pillarAudit: 'अनिवार्य लेखा-जोखा दिशानिर्देश',
  pillarAuditDesc: 'मानक संचालन प्रक्रिया आओर कानूनी ढाँचा जे सामाजिक आओर वित्तीय लेखा-जोखा केँ अनिवार्य बनाबैत अछि।',
  pillarMetrics: 'स्पष्ट प्रदर्शन मेट्रिक्स',
  pillarMetricsDesc: 'मापनीय बेंचमार्क — जहिना स्तंभन या बेरोजगारी मे विशिष्ट कमी दर।',
  pillarBodies: 'स्वतंत्र निकाय',
  pillarBodiesDesc: 'तृतीय-पक्ष ऑडिटर आओर स्थानीय सामाजिक लेखा-जोखा इकाई केर लेल राजनीतिक हस्तक्षेप कँ विरुद्ध कानूनी सुरक्षा।',
  pillarDatabases: 'सुरक्षित मास्टर डेटाबेस',
  pillarDatabasesDesc: 'स्वच्छ डेटा केर संग केन्द्रीय लाभार्थी रजिस्ट्री, जे केवल अधिकृत लेखा-जोखा एजेंसी केर लेल उपलब्ध होय।',
  // footer
  footerTagline: 'लोग-प्रथम नीति लेल शुद्ध शासन।',
  footerSub: 'गतिशील रजिस्ट्री · विकेन्द्रीकृत बायोमेट्रिक्स · प्रत्यक्ष लाभ अंतरण',
  // login
  loginTitle: 'फेर स्वागत अछि',
  loginSubtitle: 'अपन सुरक्षित नागरिक डैशबोर्ड एक्सेस करय लेल साइन इन करू। नव नागरिक दू मिनट सँ कम समय मे ऑनबोर्ड होइत छथि।',
  loginContinueGoogle: 'Google सँ जारी राखू',
  loginContinueDemo: 'डेमो खाता सँ जारी राखू',
  loginDemoHint: 'डेमो खाता',
  loginPresetLabel: 'एकटा डेमो नागरिक तेजी सँ भरू:',
  loginOrUse: 'या अपन विवरण उपयोग करू',
  loginEmail: 'ईमेल',
  loginName: 'नाम',
  loginImage: 'छवि URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'अपन Aadhaar सत्यापित करू',
  verifySubtitle: 'एक-बार पहिचान सत्यापन अपन कल्याण डैशबोर्ड खोलैत अछि।',
  verifyAadhaarLabel: '12-अंक क Aadhaar नंबर',
  verifyMobileLabel: 'OTP प्राप्त करय लेल मोबाइल नंबर',
  verifyGenerateOtp: 'OTP उत्पन्न करू',
  verifySendingOtp: 'OTP भेजि रहल अछि…',
  verifyDemoNote: 'डेमो मोड — OTP अनुरोध सिमुलेट कएल गेल अछि। कोनो वास्तविक Aadhaar डेटा प्रसारित नहि होइत अछि।',
  verifyOtpSentTo: 'अहाँक पंजीकृत मोबाइल नंबर पर OTP भेजल गेल, एहि लेल:',
  verifyDemoOtpLabel: 'डेमो OTP:',
  verifyDemoOtpNote: 'वास्तविक तैनाती एहि केँ SMS द्वारा भेजैत अछि — परीक्षण लेल एतय देखाओल गेल अछि।',
  verifyOtpLabel: '6-अंक क OTP',
  verifyVerifyOtp: 'OTP सत्यापित करू',
  verifyVerifying: 'सत्यापित कए रहल अछि…',
  verifyChangeAadhaar: 'Aadhaar नंबर बदलू',
  verifyIdentityVerified: 'पहिचान सत्यापित',
  verifyRedirecting: 'अहाँक डैशबोर्ड पर पुनर्निर्देशित कए रहल अछि…',
  verifyInvalidAadhaar: 'कृपया एकटा वैध 12-अंक क Aadhaar नंबर दाखिल करू।',
  verifyInvalidOtp: 'कृपया अहाँक फोन पर भेजल गेल 6-अंक क OTP दाखिल करू।',
  verifyInvalidMobile: 'कृपया एकटा वैध 10-अंक क मोबाइल नंबर दाखिल करू।',
  verifyFailedGenerate: 'OTP उत्पन्न करय मे विफल।',
  verifyFailedVerify: 'सत्यापन विफल। कृपया फेर प्रयास करू।',
  verifySpeakHint: 'माइक पर टैप करू आओर अपन Aadhaar या OTP कहू',
  // dashboard
  dashWelcome: 'स्वागत',
  dashCitizen: 'नागरिक',
  dashVerified: 'सत्यापन स्थिति: सत्यापित',
  dashPending: 'सत्यापन स्थिति: लंबित',
  dashVerifyAadhaar: 'Aadhaar सत्यापित करू',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'साइन आउट',
  dashFoodSubsidy: 'खाद्य सब्सिडी (PDS)',
  dashDbt: 'प्रत्यक्ष लाभ अंतरण (DBT)',
  dashEducation: 'शिक्षा अनुदान',
  dashHealth: 'स्वास्थ्य कवरेज',
  dashNotEnrolled: 'नामांकित नहि',
  dashNextSocialAudit: 'अगिला सामाजिक लेखा-जोखा',
  dashSocialAuditDesc: 'अहाँक गाम के सार्वजनिक खर्च समीक्षा — सभ निवासी केर लेल खुला।',
  // admin
  adminAccess: 'व्यवस्थापक पहुँच',
  adminOversightPortal: 'मंत्रालय निगरानी पोर्टल',
  adminAccessPassword: 'पहुँच पासवर्ड',
  adminEnterPortal: 'पोर्टल मे प्रवेश करू',
  adminIncorrect: 'गलत पासवर्ड। फेर प्रयास करू।',
  adminDemoPassword: 'डेमो पासवर्ड:',
  adminRegistration: 'आधिकारिक पंजीकरण',
  adminRegisterDesc: 'शिकायत डैशबोर्ड एक्सेस करय लेल अपन निगरानी भूमिका पंजीकृत करू।',
  adminFullName: 'पूरा नाम',
  adminEmail: 'आधिकारिक ईमेल',
  adminPhone: 'फोन',
  adminPosition: 'पद',
  adminState: 'राज्य',
  adminDistrict: 'जिला',
  adminSelectState: 'राज्य चुनू',
  adminSelectDistrict: 'जिला चुनू',
  adminRegisterContinue: 'पंजीकृत करू आओर जारी राखू',
  adminOversightDashboard: 'निगरानी डैशबोर्ड',
  adminGrievanceIntelligence: 'शिकायत इंटेलिजेंस',
  adminAllDistricts: 'सभ जिला',
  adminExit: 'बाहर निकलू',
  adminStatusDistribution: 'स्थिति वितरण',
  adminByCategory: 'श्रेणी अनुसार शिकायत',
  adminDistrictBreakdown: 'जिलावार विवरण',
  adminRecentGrievances: 'हाल के शिकायत',
  adminTotalGrievances: 'कुल शिकायत',
  adminOpen: 'खुला',
  adminNoGrievances: 'एहि दृश्य मे कोनो शिकायत नहि।',
  adminAiSummary: 'AI विषय सारांश',
  adminAiNone: 'एहि दृश्य लेल कोनो शिकायत दर्ज नहि।',
  adminPosDm: 'जिला मजिस्ट्रेट',
  adminPosBdo: 'ब्लॉक विकास अधिकारी',
  adminPosPanchayat: 'पंचायत सचिव',
  adminPosWelfare: 'कल्याण अधिकारी',
  adminPosAudit: 'सामाजिक लेखा-जोखा समन्वयक',
  adminPosState: 'राज्य नोडल अधिकारी',
  adminPosManager: 'कार्यक्रम प्रबंधक',
  // common
  commonSubmit: 'जमा करू',
  commonCancel: 'रद्द करू',
  commonLoading: 'लोड होइत अछि…',
}
