export const _mr = {
  // nav
  navFeatures: 'वैशिष्ट्ये',
  navOversight: 'देखरेख',
  navSignIn: 'साइन इन',
  // hero
  heroBadge: 'कल्याण धोरण अंमलबजावणी',
  heroTitle1: 'अचूक राज्यशास्त्र.',
  heroTitle2: 'पुनर्कल्पित.',
  heroSubtitle: 'एक सुरक्षित, नागरिक-केंद्रित व्यासपीठ जेथे वास्तविक-वेळेतील डेटा, विकेंद्रित ओळख आणि थेट हस्तांतरणे योग्य त्या व्यक्तींपर्यंत कल्याण लाभ पोहोचवतात.',
  heroCta: 'आपले डॅशबोर्ड प्रविष्ट करा',
  // features
  featuresBadge: 'क्षमता',
  featuresTitle: 'आधुनिक कल्याण प्रणालीसाठी आवश्यक सर्व काही.',
  featuresSubtitle: 'एकाच जोडलेल्या व्यासपीठावर ओळख, लक्ष्यीकरण, देयके आणि जबाबदारी यांची एकत्रित व्यवस्था आहे.',
  tileDynamicRegistries: 'डायनॅमिक सामाजिक-आर्थिक नोंदी',
  tileDynamicRegistriesDesc: 'कर, उपयुक्तता आणि नागरी नोंदींवरून सतत पात्रता अद्यतने — असे लक्ष्यीकरण जे नेहमी वास्तव दर्शवते, कधीही कालबाह्य जनगणना नाही.',
  tileBiometrics: 'विकेंद्रित बायोमेट्रिक्स',
  tileBiometricsDesc: 'सुरक्षित, विकेंद्रित बायोमेट्रिक ओळख जी ओळख फसवणूक आणि दुहेरी लाभ घेणे दारावरच थांबवते.',
  tileDbt: 'थेट लाभ हस्तांतरणे',
  tileDbtDesc: 'रोख आणि अनुदाने थेट सत्यापित नागरिक खात्यांमध्ये वळवली जातात — कोणतेही मध्यस्थ नाहीत.',
  tileConditional: 'अटींवर आधारित हस्तांतरणे',
  tileConditionalDesc: 'शिक्षण व आरोग्य टप्प्यांशी जोडलेली देयके, मोजता येणाऱ्या सामाजिक परिणामांसाठी.',
  tileAudits: 'सामुदायिक सामाजिक लेखापरीक्षणे',
  tileAuditsDesc: 'सार्वजनिक सभा जेथे नागरिक जमिनीवरील मालमत्तेविरुद्ध खर्चाची चौकशी करतात.',
  tileAi: 'स्वयंचलित अपवाद अहवाल',
  tileAiDesc: 'AI संशयास्पद नमुने ओळखते — जसे की अनेक लाभ खात्यांशी जोडलेला एकच फोन नंबर — तात्काळ तपासणीसाठी.',
  // oversight
  oversightBadge: 'मंत्रालय देखरेख',
  oversightTitle: 'मंत्रालय चौकट आणि पायाभूत सुविधा',
  oversightSubtitle: 'मंत्रालये कायदेशीर चौकटी तयार करून, देखरेख अर्थसंकल्प वाटप करून, सुरक्षित डेटा प्रणाली राखून आणि दंड लागू करून कल्याण धोरण लेखापरीक्षणावर देखरेख ठेवतात.',
  pillarAudit: 'अनिवार्य लेखापरीक्षण मार्गदर्शक',
  pillarAuditDesc: 'सामाजिक व वित्तीय लेखापरीक्षणे अनिवार्य बनवणारी मानक कार्यपद्धती व कायदेशीर चौकटी.',
  pillarMetrics: 'स्पष्ट कामगिरी मापदंड',
  pillarMetricsDesc: 'मोजता येणारी निर्धारके — जसे की खड्ड्यात पडण्यात किंवा बेरोजगारीत विशिष्ट घट दर.',
  pillarBodies: 'स्वतंत्र संस्था',
  pillarBodiesDesc: 'तृतीय-पक्ष लेखापरीक्षकांसाठी व स्थानिक सामाजिक लेखापरीक्षण युनिट्ससाठी राजकीय हस्तक्षेपाविरुद्ध कायदेशीर संरक्षण.',
  pillarDatabases: 'सुरक्षित मास्टर डेटाबेसेस',
  pillarDatabasesDesc: 'स्वच्छ डेटासह केंद्रीय लाभार्थी नोंदी, ज्यामध्ये फक्त अधिकृत लेखापरीक्षण संस्थांनाच प्रवेश.',
  // footer
  footerTagline: 'नागरिक-केंद्रित धोरणासाठी अचूक राज्यशास्त्र.',
  footerSub: 'डायनॅमिक नोंदी · विकेंद्रित बायोमेट्रिक्स · थेट लाभ हस्तांतरणे',
  // login
  loginTitle: 'पुन्हा स्वागत आहे',
  loginSubtitle: 'आपले सुरक्षित नागरिक डॅशबोर्ड प्रविष्ट करण्यासाठी साइन इन करा. नवीन नागरिक दोन मिनिटांपेक्षा कमी वेळात समाविष्ट केले जातात.',
  loginContinueGoogle: 'Google सहित पुढे जा',
  loginContinueDemo: 'डेमो खात्यासह पुढे जा',
  loginDemoHint: 'डेमो खाते',
  loginPresetLabel: 'डेमो नागरिक त्वरित भरा:',
  loginOrUse: 'किंवा आपला तपशील वापरा',
  loginEmail: 'ईमेल',
  loginName: 'नाव',
  loginImage: 'प्रतिमा URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'आपले Aadhaar सत्यापित करा',
  verifySubtitle: 'एकदाच वापरायची ओळख सत्यापन आपले कल्याण डॅशबोर्ड उघडते.',
  verifyAadhaarLabel: '12-अंकी Aadhaar क्रमांक',
  verifyMobileLabel: 'OTP प्राप्त करण्यासाठी मोबाइल क्रमांक',
  verifyGenerateOtp: 'OTP तयार करा',
  verifySendingOtp: 'OTP पाठवत आहे…',
  verifyDemoNote: 'डेमो मोड — OTP विनंतीचे सिम्युलेशन केले जाते. कोणताही वास्तविक Aadhaar डेटा प्रसारित होत नाही.',
  verifyOtpSentTo: 'आपल्या नोंदणीकृत मोबाइल क्रमांकावर OTP पाठवला:',
  verifyDemoOtpLabel: 'डेमो OTP:',
  verifyDemoOtpNote: 'वास्तविक डेप्लॉयमेंट हे SMS द्वारे पाठवते — चाचणीसाठी येथे दाखवले आहे.',
  verifyOtpLabel: '6-अंकी OTP',
  verifyVerifyOtp: 'OTP सत्यापित करा',
  verifyVerifying: 'सत्यापित करत आहे…',
  verifyChangeAadhaar: 'Aadhaar क्रमांक बदला',
  verifyIdentityVerified: 'ओळख सत्यापित झाली',
  verifyRedirecting: 'आपल्या डॅशबोर्डवर पुनर्निर्देशित करत आहे…',
  verifyInvalidAadhaar: 'कृपया वैध 12-अंकी Aadhaar क्रमांक प्रविष्ट करा.',
  verifyInvalidOtp: 'कृपया आपल्या फोनवर पाठवलेला 6-अंकी OTP प्रविष्ट करा.',
  verifyInvalidMobile: 'कृपया वैध 10-अंकी मोबाइल क्रमांक प्रविष्ट करा.',
  verifyFailedGenerate: 'OTP तयार करण्यात अयशस्वी.',
  verifyFailedVerify: 'सत्यापन अयशस्वी. कृपया पुन्हा प्रयत्न करा.',
  verifySpeakHint: 'माइकवर टॅप करा आणि आपला Aadhaar किंवा OTP म्हणा',
  // dashboard
  dashWelcome: 'स्वागत',
  dashCitizen: 'नागरिक',
  dashVerified: 'सत्यापन स्थिती: सत्यापित',
  dashPending: 'सत्यापन स्थिती: प्रलंबित',
  dashVerifyAadhaar: 'Aadhaar सत्यापित करा',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'साइन आउट',
  dashFoodSubsidy: 'अन्न अनुदान (PDS)',
  dashDbt: 'थेट लाभ हस्तांतरण',
  dashEducation: 'शिक्षण अनुदान',
  dashHealth: 'आरोग्य विमा',
  dashNotEnrolled: 'नोंदणीकृत नाही',
  dashNextSocialAudit: 'पुढील सामाजिक लेखापरीक्षण',
  dashSocialAuditDesc: 'आपल्या गावातील सार्वजनिक खर्चाचे पुनरावलोकन — सर्व रहिवाश्यांसाठी खुले.',
  // admin
  adminAccess: 'ॲडमिन प्रवेश',
  adminOversightPortal: 'मंत्रालय देखरेख पोर्टल',
  adminAccessPassword: 'प्रवेश संकेतशब्द',
  adminEnterPortal: 'पोर्टलमध्ये प्रविष्ट करा',
  adminIncorrect: 'चुकीचा संकेतशब्द. पुन्हा प्रयत्न करा.',
  adminDemoPassword: 'डेमो संकेतशब्द:',
  adminRegistration: 'अधिकृत नोंदणी',
  adminRegisterDesc: 'तक्रार डॅशबोर्डमध्ये प्रवेश करण्यासाठी आपली देखरेख भूमिका नोंदणी करा.',
  adminFullName: 'पूर्ण नाव',
  adminEmail: 'अधिकृत ईमेल',
  adminPhone: 'फोन',
  adminPosition: 'पद',
  adminState: 'राज्य',
  adminDistrict: 'जिल्हा',
  adminSelectState: 'राज्य निवडा',
  adminSelectDistrict: 'जिल्हा निवडा',
  adminRegisterContinue: 'नोंदणी करा व पुढे जा',
  adminOversightDashboard: 'देखरेख डॅशबोर्ड',
  adminGrievanceIntelligence: 'तक्रार बुद्धिमत्ता',
  adminAllDistricts: 'सर्व जिल्हे',
  adminExit: 'बाहेर पडा',
  adminStatusDistribution: 'स्थिती वितरण',
  adminByCategory: 'श्रेणीनुसार तक्रारी',
  adminDistrictBreakdown: 'जिल्हा विभाजन',
  adminRecentGrievances: 'अलीकडील तक्रारी',
  adminTotalGrievances: 'एकूण तक्रारी',
  adminOpen: 'उघडे',
  adminNoGrievances: 'या दृश्यात कोणतीही तक्रार नाही.',
  adminAiSummary: 'AI विषय सारांश',
  adminAiNone: 'या दृश्यासाठी कोणतीही तक्रार नोंदवलेली नाही.',
  adminPosDm: 'जिल्हाधिकारी',
  adminPosBdo: 'ब्लॉक विकास अधिकारी',
  adminPosPanchayat: 'पंचायत सचिव',
  adminPosWelfare: 'कल्याण अधिकारी',
  adminPosAudit: 'सामाजिक लेखापरीक्षण समन्वयक',
  adminPosState: 'राज्य नोडल अधिकारी',
  adminPosManager: 'कार्यक्रम व्यवस्थापक',
  // common
  commonSubmit: 'सबमिट करा',
  commonCancel: 'रद्द करा',
  commonLoading: 'लोड होत आहे…',
}
