export const _ml = {
  // nav
  navFeatures: 'സവിശേഷതകൾ',
  navOversight: 'മേൽനോട്ടം',
  navSignIn: 'സൈൻ ഇൻ ചെയ്യുക',
  // hero
  heroBadge: 'ക്ഷേമ നയ നടത്തിപ്പ്',
  heroTitle1: 'കൃത്യതയോടെയുള്ള ഭരണം.',
  heroTitle2: 'വീണ്ടും സൃഷ്ടിച്ചു.',
  heroSubtitle: 'സുരക്ഷിതവും പൗരന്റെ ആദ്യമായുള്ളതുമായ പ്ലാറ്റ്ഫോമിൽ റിയൽ ടൈം ഡാറ്റ, വികേന്ദ്രീകൃത ഐഡന്റിറ്റി, നേരിട്ടുള്ള കൈമാറ്റങ്ങൾ എന്നിവ വഴി ക്ഷേമ പ്രയോജനങ്ങൾ കൃത്യമായ വ്യക്തികളിലേക്ക് എത്തിക്കുന്നു.',
  heroCta: 'നിങ്ങളുടെ ഡാഷ്ബോർഡ് ആക്സസ് ചെയ്യുക',
  // features
  featuresBadge: 'ശേഷികൾ',
  featuresTitle: 'ആധുനിക ക്ഷേമ വ്യവസ്ഥയ്ക്ക് ആവശ്യമായതെല്ലാം.',
  featuresSubtitle: 'ഒരു ബന്ധിത പ്ലാറ്റ്ഫോം ഐഡന്റിറ്റി, ലക്ഷ്യം നിശ്ചയിക്കൽ, പേയ്മന്റ്, ഉത്തരവാദിത്തം എന്നിവ ഏകോപിപ്പിക്കുന്നു.',
  tileDynamicRegistries: 'ചലനാത്മക സാമൂഹിക-സാമ്പത്തിക രജിസ്ട്രികൾ',
  tileDynamicRegistriesDesc: 'നികുതി, യൂട്ടിലിറ്റി, സിവിൽ രേഖകളിൽ നിന്നുള്ള തുടർച്ചയായ യോഗ്യതാ പുതുക്കലുകൾ — എപ്പോഴും യാഥാർത്ഥ്യം പ്രതിഫലിപ്പിക്കുന്ന, പഴയ സെൻസസ് അല്ലാത്ത ലക്ഷ്യസ്ഥാനീകരണം.',
  tileBiometrics: 'വികേന്ദ്രീകൃത ബയോമെട്രിക്സ്',
  tileBiometricsDesc: 'ഐഡന്റിറ്റി തട്ടിപ്പും ഇരട്ട നേട്ടവും വാതിലിൽ തടയുന്ന സുരക്ഷിതവും വികേന്ദ്രീകൃതവുമായ ബയോമെട്രിക് ഐഡുകൾ.',
  tileDbt: 'നേരിട്ടുള്ള പ്രയോജന കൈമാറ്റങ്ങൾ',
  tileDbtDesc: 'പണവും സബ്സിഡികളും മധ്യവർത്തികളില്ലാതെ സ്ഥിരീകരിച്ച പൗര അക്കൗണ്ടുകളിലേക്ക് നേരിട്ട് എത്തിക്കുന്നു.',
  tileConditional: 'ഉപാധിയുള്ള കൈമാറ്റങ്ങൾ',
  tileConditionalDesc: 'അളക്കാവുന്ന സാമൂഹിക ഫലങ്ങൾക്കായി വിദ്യാഭ്യാസ, ആരോഗ്യ നിലവാരങ്ങളുമായി ബന്ധിപ്പിച്ച പേയ്മെന്റുകൾ.',
  tileAudits: 'സമൂഹ സാമൂഹിക ഓഡിറ്റുകൾ',
  tileAuditsDesc: 'നാട്ടിലെ ആസ്തികൾക്കെതിരെ ചെലവ് പൗരന്മാർ പരസ്പരം പരിശോധിക്കുന്ന പൊതു യോഗങ്ങൾ.',
  tileAi: 'സ്വയംപ്രേരിത അസാധാരണ റിപ്പോർട്ടുകൾ',
  tileAiDesc: 'ഒരൊറ്റ ഫോൺ നമ്പർ ഒന്നിലധികം പ്രയോജന അക്കൗണ്ടുകളുമായി ബന്ധിപ്പിച്ചിരിക്കുന്നതുപോലുള്ള സംശയാസ്പദ പാറ്റേണുകൾ AI കണ്ടെത്തി ഉടൻ അന്വേഷണത്തിന് വിധേയമാക്കുന്നു.',
  // oversight
  oversightBadge: 'മന്ത്രാലയ മേൽനോട്ടം',
  oversightTitle: 'മന്ത്രാലയ ചട്ടക്കൂടും അടിസ്ഥാന സൗകര്യങ്ങളും',
  oversightSubtitle: 'നിയമ ചട്ടക്കൂടുകൾ സ്ഥാപിക്കുക, മേൽനോട്ട ബജറ്റ് നീക്കിവയ്ക്കുക, സുരക്ഷിത ഡാറ്റാ സംവിധാനങ്ങൾ പരിപാലിക്കുക, ശിക്ഷകൾ നടപ്പാക്കുക എന്നിവ വഴി ക്ഷേമ നയ ഓഡിറ്റുകൾ മന്ത്രാലയങ്ങൾ മേൽനോക്കുന്നു.',
  pillarAudit: 'നിർബന്ധിത ഓഡിറ്റ് മാർഗ്ഗനിർദ്ദേശങ്ങൾ',
  pillarAuditDesc: 'സാമൂഹിക, സാമ്പത്തിക ഓഡിറ്റുകൾ നിർബന്ധമാക്കുന്ന സ്റ്റാൻഡേർഡ് ഓപ്പറേറ്റിംഗ് നടപടിക്രമങ്ങളും നിയമ ചട്ടക്കൂടുകളും.',
  pillarMetrics: 'വ്യക്തമായ പ്രകടന മാനദണ്ഡങ്ങൾ',
  pillarMetricsDesc: 'അളക്കാവുന്ന ബെഞ്ച്മാർക്കുകൾ — ഉദാഹരണത്തിന് മാന്ദ്യത്തിലോ തൊഴിലില്ലായ്മയിലോ നിർദ്ദിഷ്ട കുറവ് നിരക്കുകൾ.',
  pillarBodies: 'സ്വതന്ത്ര സംഘടനകൾ',
  pillarBodiesDesc: 'രാഷ്ട്രീയ ഇടപെടലിൽ നിന്ന് മൂന്നാം കക്ഷി ഓഡിറ്റർമാർക്കും പ്രാദേശിക സാമൂഹിക ഓഡിറ്റ് യൂണിറ്റുകൾക്കുമുള്ള നിയമ സംരക്ഷണം.',
  pillarDatabases: 'സുരക്ഷിത മാസ്റ്റർ ഡാറ്റാബേസുകൾ',
  pillarDatabasesDesc: 'അധികൃത ഓഡിറ്റ് ഏജൻസികൾക്ക് മാത്രം ആക്സസ് ചെയ്യാവുന്ന വൃത്തിയുള്ള ഡാറ്റയുള്ള കേന്ദ്ര ഗുണഭോക്തൃ രജിസ്ട്രികൾ.',
  // footer
  footerTagline: 'ജനകേന്ദ്രിത നയത്തിനായുള്ള കൃത്യതയോടെയുള്ള ഭരണം.',
  footerSub: 'ചലനാത്മക രജിസ്ട്രികൾ · വികേന്ദ്രീകൃത ബയോമെട്രിക്സ് · നേരിട്ടുള്ള പ്രയോജന കൈമാറ്റങ്ങൾ',
  // login
  loginTitle: 'വീണ്ടും സ്വാഗതം',
  loginSubtitle: 'നിങ്ങളുടെ സുരക്ഷിത പൗര ഡാഷ്ബോർഡ് ആക്സസ് ചെയ്യാൻ സൈൻ ഇൻ ചെയ്യുക. പുതിയ പൗരന്മാരെ രണ്ട് മിനിറ്റിനുള്ളിൽ ഓൺബോർഡ് ചെയ്യുന്നു.',
  loginContinueGoogle: 'Google വഴി തുടരുക',
  loginContinueDemo: 'ഡെമോ അക്കൗണ്ട് വഴി തുടരുക',
  loginDemoHint: 'ഡെമോ അക്കൗണ്ട്',
  loginPresetLabel: 'ഒരു ഡെമോ പൗരനെ പെട്ടെന്ന് നിറയ്ക്കുക:',
  loginOrUse: 'അല്ലെങ്കിൽ നിങ്ങളുടെ വിവരങ്ങൾ ഉപയോഗിക്കുക',
  loginEmail: 'ഇമെയിൽ',
  loginName: 'പേര്',
  loginImage: 'ചിത്ര URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'നിങ്ങളുടെ Aadhaar സ്ഥിരീകരിക്കുക',
  verifySubtitle: 'ഒരിക്കൽ മാത്രമുള്ള ഐഡന്റിറ്റി പരിശോധന നിങ്ങളുടെ ക്ഷേമ ഡാഷ്ബോർഡ് തുറക്കുന്നു.',
  verifyAadhaarLabel: '12 അക്ക Aadhaar നമ്പർ',
  verifyMobileLabel: 'OTP ലഭിക്കാനുള്ള മൊബൈൽ നമ്പർ',
  verifyGenerateOtp: 'OTP സൃഷ്ടിക്കുക',
  verifySendingOtp: 'OTP അയയ്ക്കുന്നു…',
  verifyDemoNote: 'ഡെമോ മോഡ് — OTP അഭ്യർത്ഥന സിമുലേറ്റ് ചെയ്യപ്പെടുന്നു. യഥാർത്ഥ Aadhaar ഡാറ്റ കൈമാറ്റം ചെയ്യപ്പെടുന്നില്ല.',
  verifyOtpSentTo: 'നിങ്ങളുടെ രജിസ്റ്റർ ചെയ്ത മൊബൈൽ നമ്പറിലേക്ക് OTP അയച്ചു:',
  verifyDemoOtpLabel: 'ഡെമോ OTP:',
  verifyDemoOtpNote: 'യഥാർത്ഥ വിന്യാസം ഇത് SMS വഴി അയയ്ക്കും — പരീക്ഷണത്തിനായി ഇവിടെ കാണിച്ചിരിക്കുന്നു.',
  verifyOtpLabel: '6 അക്ക OTP',
  verifyVerifyOtp: 'OTP സ്ഥിരീകരിക്കുക',
  verifyVerifying: 'സ്ഥിരീകരിക്കുന്നു…',
  verifyChangeAadhaar: 'Aadhaar നമ്പർ മാറ്റുക',
  verifyIdentityVerified: 'ഐഡന്റിറ്റി സ്ഥിരീകരിച്ചു',
  verifyRedirecting: 'നിങ്ങളുടെ ഡാഷ്ബോർഡിലേക്ക് റീഡയറക്ട് ചെയ്യുന്നു…',
  verifyInvalidAadhaar: 'ദയവായി സാധുവായ 12 അക്ക Aadhaar നമ്പർ നൽകുക.',
  verifyInvalidOtp: 'ദയവായി നിങ്ങളുടെ ഫോണിലേക്ക് അയച്ച 6 അക്ക OTP നൽകുക.',
  verifyInvalidMobile: 'ദയവായി സാധുവായ 10 അക്ക മൊബൈൽ നമ്പർ നൽകുക.',
  verifyFailedGenerate: 'OTP സൃഷ്ടിക്കുന്നതിൽ പരാജയപ്പെട്ടു.',
  verifyFailedVerify: 'സ്ഥിരീകരണം പരാജയപ്പെട്ടു. വീണ്ടും ശ്രമിക്കുക.',
  verifySpeakHint: 'മൈക്കിൽ ടാപ്പ് ചെയ്ത് നിങ്ങളുടെ Aadhaar അല്ലെങ്കിൽ OTP പറയുക',
  // dashboard
  dashWelcome: 'സ്വാഗതം',
  dashCitizen: 'പൗരൻ',
  dashVerified: 'സ്ഥിരീകരണ നില: സ്ഥിരീകരിച്ചു',
  dashPending: 'സ്ഥിരീകരണ നില: തീരുമാനം കാത്തിരിക്കുന്നു',
  dashVerifyAadhaar: 'Aadhaar സ്ഥിരീകരിക്കുക',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'സൈൻ ഔട്ട് ചെയ്യുക',
  dashFoodSubsidy: 'ഭക്ഷ്യ സബ്സിഡി (PDS)',
  dashDbt: 'നേരിട്ടുള്ള പ്രയോജന കൈമാറ്റം',
  dashEducation: 'വിദ്യാഭ്യാസ ഗ്രാന്റ്',
  dashHealth: 'ആരോഗ്യ പരിരക്ഷ',
  dashNotEnrolled: 'ചേർത്തിട്ടില്ല',
  dashNextSocialAudit: 'അടുത്ത സാമൂഹിക ഓഡിറ്റ്',
  dashSocialAuditDesc: 'നിങ്ങളുടെ ഗ്രാമത്തിലെ പൊതു ചെലവ് അവലോകനം — എല്ലാ നിവാസികൾക്കും തുറന്നിരിക്കുന്നു.',
  // admin
  adminAccess: 'അഡ്മിൻ ആക്സസ്',
  adminOversightPortal: 'മന്ത്രാലയ മേൽനോട്ട പോർട്ടൽ',
  adminAccessPassword: 'ആക്സസ് പാസ്‌വേഡ്',
  adminEnterPortal: 'പോർട്ടലിൽ പ്രവേശിക്കുക',
  adminIncorrect: 'തെറ്റായ പാസ്‌വേഡ്. വീണ്ടും ശ്രമിക്കുക.',
  adminDemoPassword: 'ഡെമോ പാസ്‌വേഡ്:',
  adminRegistration: 'ഔദ്യോഗിക രജിസ്ട്രേഷൻ',
  adminRegisterDesc: 'പരാതി ഡാഷ്ബോർഡ് ആക്സസ് ചെയ്യാൻ നിങ്ങളുടെ മേൽനോട്ട റോൾ രജിസ്റ്റർ ചെയ്യുക.',
  adminFullName: 'പൂർണ്ണ നാമം',
  adminEmail: 'ഔദ്യോഗിക ഇമെയിൽ',
  adminPhone: 'ഫോൺ',
  adminPosition: 'സ്ഥാനം',
  adminState: 'സംസ്ഥാനം',
  adminDistrict: 'ജില്ല',
  adminSelectState: 'സംസ്ഥാനം തിരഞ്ഞെടുക്കുക',
  adminSelectDistrict: 'ജില്ല തിരഞ്ഞെടുക്കുക',
  adminRegisterContinue: 'രജിസ്റ്റർ ചെയ്ത് തുടരുക',
  adminOversightDashboard: 'മേൽനോട്ട ഡാഷ്ബോർഡ്',
  adminGrievanceIntelligence: 'പരാതി ഇൻറലിജൻസ്',
  adminAllDistricts: 'എല്ലാ ജില്ലകളും',
  adminExit: 'പുറത്തുകടക്കുക',
  adminStatusDistribution: 'നില വിതരണം',
  adminByCategory: 'വിഭാഗം അനുസരിച്ചുള്ള പരാതികൾ',
  adminDistrictBreakdown: 'ജില്ല തിരിച്ചുള്ള വിവരങ്ങൾ',
  adminRecentGrievances: 'സമീപകാല പരാതികൾ',
  adminTotalGrievances: 'മൊത്തം പരാതികൾ',
  adminOpen: 'തുറന്നത്',
  adminNoGrievances: 'ഈ വ്യൂവിൽ പരാതികളൊന്നുമില്ല.',
  adminAiSummary: 'AI വിഷയ സംഗ്രഹം',
  adminAiNone: 'ഈ വ്യൂവിനായി പരാതികളൊന്നും രേഖപ്പെടുത്തിയിട്ടില്ല.',
  adminPosDm: 'ജില്ലാ മജിസ്ട്രേറ്റ്',
  adminPosBdo: 'ബ്ലോക്ക് ഡെവലപ്മെന്റ് ഓഫീസർ',
  adminPosPanchayat: 'പഞ്ചായത്ത് സെക്രട്ടറി',
  adminPosWelfare: 'ക്ഷേമ ഓഫീസർ',
  adminPosAudit: 'സാമൂഹിക ഓഡിറ്റ് കോർഡിനേറ്റർ',
  adminPosState: 'സംസ്ഥാന നോഡൽ ഓഫീസർ',
  adminPosManager: 'പ്രോഗ്രാം മാനേജർ',
  // common
  commonSubmit: 'സമർപ്പിക്കുക',
  commonCancel: 'റദ്ദാക്കുക',
  commonLoading: 'ലോഡ് ചെയ്യുന്നു…',
}
