export const _ne = {
  // nav
  navFeatures: 'सुविधाहरू',
  navOversight: 'अनुगमन',
  navSignIn: 'साइन इन',
  // hero
  heroBadge: 'कल्याणकारी नीति कार्यान्वयन',
  heroTitle1: 'निर्भुल शासन।',
  heroTitle2: 'पुनःकल्पना गरिएको।',
  heroSubtitle: 'एक सुरक्षित, नागरिक-प्राथमिक मञ्च जहाँ वास्तविक समयको डाटा, विकेन्द्रीकृत पहिचान, र प्रत्यक्ष हस्तान्तरणले कल्याणकारी लाभ ठीकै व्यक्तिहरूमा पुर्‍याउँछ।',
  heroCta: 'आफ्नो ड्यासबोर्ड हेर्नुहोस्',
  // features
  featuresBadge: 'क्षमताहरू',
  featuresTitle: 'आधुनिक कल्याणकारी प्रणालीलाई आवश्यक सबै कुरा।',
  featuresSubtitle: 'एक जडित मञ्चले पहिचान, लक्ष्यीकरण, भुक्तानी, र जवाफदेहितालाई एकीकृत गर्छ।',
  tileDynamicRegistries: 'गतिशील सामाजिक-आर्थिक दर्ता',
  tileDynamicRegistriesDesc: 'कर, उपयोगिता, र नागरिक रेकर्डबाट निरन्तर योग्यता अद्यावधिक — त्यस्तो लक्ष्यीकरण जसले सधैं वास्तविकतालाई प्रतिबिम्बित गर्छ, कहिल्यै पुरानो जनगणनालाई होइन।',
  tileBiometrics: 'विकेन्द्रीकृत बायोमेट्रिक्स',
  tileBiometricsDesc: 'सुरक्षित, विकेन्द्रीकृत बायोमेट्रिक पहिचान जसले ढोकैमा पहिचान ठगी र दोहोरो लाभ लिने क्रियाकलाप रोक्छ।',
  tileDbt: 'प्रत्यक्ष लाभ हस्तान्तरण',
  tileDbtDesc: 'नगद र अनुदान प्रमाणित नागरिक खातामा सिधै पठाइन्छ — कुनै बिचौलिया छैनन्।',
  tileConditional: 'सर्तबद्ध हस्तान्तरण',
  tileConditionalDesc: 'शिक्षा र स्वास्थ्यका माइलढुङ्गासँग जोडिएको भुक्तानीले मापन योग्य सामाजिक परिणाम दिन्छ।',
  tileAudits: 'सामुदायिक सामाजिक लेखापरीक्षण',
  tileAuditsDesc: 'सार्वजनिक सभाहरू जहाँ नागरिकहरूले जमिनमा रहेका सम्पत्तिविरुद्ध खर्चको क्रस-परीक्षण गर्छन्।',
  tileAi: 'स्वचालित अपवाद प्रतिवेदन',
  tileAiDesc: 'AI ले शंकास्पद ढाँचाहरू — जस्तै धेरै लाभ खातासँग जोडिएको एउटै फोन नम्बर — तत्काल छानबिनका लागि छाप्छ।',
  // oversight
  oversightBadge: 'मन्त्रालय अनुगमन',
  oversightTitle: 'मन्त्रालय ढाँचा र पूर्वाधार',
  oversightSubtitle: 'मन्त्रालयहरूले कानुनी ढाँचा स्थापना गरेर, अनुगमन बजेट विनियोजन गरेर, सुरक्षित डाटा प्रणाली कायम गरेर, र जरिबाना लागू गरेर कल्याणकारी नीति लेखापरीक्षणको अनुगमन गर्छन्।',
  pillarAudit: 'अनिवार्य लेखापरीक्षण दिशानिर्देश',
  pillarAuditDesc: 'त्यस्ता मापदण्ड सञ्चालन कार्यविधि र कानुनी ढाँचा जसले सामाजिक र वित्तीय लेखापरीक्षणलाई अनिवार्य बनाउँछन्।',
  pillarMetrics: 'स्पष्ट प्रदर्शन मापदण्ड',
  pillarMetricsDesc: 'मापन योग्य मापदण्ड — जस्तै बाल कुपोषण वा बेरोजगारीमा विशिष्ट कमी दर।',
  pillarBodies: 'स्वतन्त्र निकाय',
  pillarBodiesDesc: 'तेस्रो पक्षका अडिटर र स्थानीय सामाजिक लेखापरीक्षण एकाइहरूलाई राजनीतिक हस्तक्षेपबाट कानुनी सुरक्षा।',
  pillarDatabases: 'सुरक्षित मास्टर डाटाबेस',
  pillarDatabasesDesc: 'सफा डाटा भएको केन्द्रीय लाभार्थी दर्ता, जुन अधिकृत लेखापरीक्षण एजेन्सीहरूलाई मात्र पहुँचयोग्य छ।',
  // footer
  footerTagline: 'जनता-प्राथमिक नीतिका लागि निर्भुल शासन।',
  footerSub: 'गतिशील दर्ता · विकेन्द्रीकृत बायोमेट्रिक्स · प्रत्यक्ष लाभ हस्तान्तरण',
  // login
  loginTitle: 'फर्कनु भएकोमा स्वागत छ',
  loginSubtitle: 'आफ्नो सुरक्षित नागरिक ड्यासबोर्ड पहुँच गर्न साइन इन गर्नुहोस्। नयाँ नागरिकहरू दुई मिनेटभित्रमा दर्ता हुन्छन्।',
  loginContinueGoogle: 'Google बाट जारी राख्नुहोस्',
  loginContinueDemo: 'डेमो खाताबाट जारी राख्नुहोस्',
  loginDemoHint: 'डेमो खाता',
  loginPresetLabel: 'एउटा डेमो नागरिक छिटो भर्नुहोस्:',
  loginOrUse: 'वा आफ्नो विवरण प्रयोग गर्नुहोस्',
  loginEmail: 'इमेल',
  loginName: 'नाम',
  loginImage: 'तस्वीर URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'आफ्नो Aadhaar प्रमाणित गर्नुहोस्',
  verifySubtitle: 'एकपटकको पहिचान प्रमाणीकरणले तपाईंको कल्याणकारी ड्यासबोर्ड अनलक गर्छ।',
  verifyAadhaarLabel: '१२-अंकको Aadhaar नम्बर',
  verifyMobileLabel: 'OTP प्राप्त गर्ने मोबाइल नम्बर',
  verifyGenerateOtp: 'OTP उत्पन्न गर्नुहोस्',
  verifySendingOtp: 'OTP पठाउँदै…',
  verifyDemoNote: 'डेमो मोड — OTP अनुरोध नक्कली हो। कुनै वास्तविक Aadhaar डाटा प्रसारित हुँदैन।',
  verifyOtpSentTo: 'OTP तपाईंको दर्ता गरिएको मोबाइल नम्बरमा पठाइयो',
  verifyDemoOtpLabel: 'डेमो OTP:',
  verifyDemoOtpNote: 'वास्तविक डिप्लोयमेन्टले यो SMS मार्फत पठाउँछ — परीक्षणका लागि यहाँ देखाइएको।',
  verifyOtpLabel: '६-अंकको OTP',
  verifyVerifyOtp: 'OTP प्रमाणित गर्नुहोस्',
  verifyVerifying: 'प्रमाणित गर्दै…',
  verifyChangeAadhaar: 'Aadhaar नम्बर परिवर्तन गर्नुहोस्',
  verifyIdentityVerified: 'पहिचान प्रमाणित भयो',
  verifyRedirecting: 'तपाईंको ड्यासबोर्डमा रिडाइरेक्ट गर्दै…',
  verifyInvalidAadhaar: 'कृपया वैध १२-अंकको Aadhaar नम्बर प्रविष्ट गर्नुहोस्।',
  verifyInvalidOtp: 'कृपया आफ्नो फोनमा पठाइएको ६-अंकको OTP प्रविष्ट गर्नुहोस्।',
  verifyInvalidMobile: 'कृपया वैध १०-अंकको मोबाइल नम्बर प्रविष्ट गर्नुहोस्।',
  verifyFailedGenerate: 'OTP उत्पन्न गर्न असफल भयो।',
  verifyFailedVerify: 'प्रमाणीकरण असफल भयो। कृपया पुनः प्रयास गर्नुहोस्।',
  verifySpeakHint: 'माइक थिचेर आफ्नो Aadhaar वा OTP भन्नुहोस्',
  // dashboard
  dashWelcome: 'स्वागत छ',
  dashCitizen: 'नागरिक',
  dashVerified: 'प्रमाणीकरण स्थिति: प्रमाणित',
  dashPending: 'प्रमाणीकरण स्थिति: विचाराधीन',
  dashVerifyAadhaar: 'Aadhaar प्रमाणित गर्नुहोस्',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'साइन आउट',
  dashFoodSubsidy: 'खाद्य अनुदान (PDS)',
  dashDbt: 'प्रत्यक्ष लाभ हस्तान्तरण',
  dashEducation: 'शिक्षा अनुदान',
  dashHealth: 'स्वास्थ्य सुरक्षा',
  dashNotEnrolled: 'दर्ता नभएको',
  dashNextSocialAudit: 'अर्को सामाजिक लेखापरीक्षण',
  dashSocialAuditDesc: 'तपाईंको गाउँको सार्वजनिक खर्च समीक्षा — सबै बासिन्दाका लागि खुला।',
  // admin
  adminAccess: 'व्यवस्थापक पहुँच',
  adminOversightPortal: 'मन्त्रालय अनुगमन पोर्टल',
  adminAccessPassword: 'पहुँच पासवर्ड',
  adminEnterPortal: 'पोर्टल प्रवेश',
  adminIncorrect: 'गलत पासवर्ड। पुनः प्रयास गर्नुहोस्।',
  adminDemoPassword: 'डेमो पासवर्ड:',
  adminRegistration: 'आधिकारिक दर्ता',
  adminRegisterDesc: 'गुनासो ड्यासबोर्ड पहुँच गर्न आफ्नो अनुगमन भूमिका दर्ता गर्नुहोस्।',
  adminFullName: 'पूरा नाम',
  adminEmail: 'आधिकारिक इमेल',
  adminPhone: 'फोन',
  adminPosition: 'पद',
  adminState: 'राज्य',
  adminDistrict: 'जिल्ला',
  adminSelectState: 'राज्य छान्नुहोस्',
  adminSelectDistrict: 'जिल्ला छान्नुहोस्',
  adminRegisterContinue: 'दर्ता गरी जारी राख्नुहोस्',
  adminOversightDashboard: 'अनुगमन ड्यासबोर्ड',
  adminGrievanceIntelligence: 'गुनासो इन्टेलिजेन्स',
  adminAllDistricts: 'सबै जिल्लाहरू',
  adminExit: 'बाहिर निस्कनुहोस्',
  adminStatusDistribution: 'स्थिति वितरण',
  adminByCategory: 'वर्ग अनुसार गुनासोहरू',
  adminDistrictBreakdown: 'जिल्लागत विवरण',
  adminRecentGrievances: 'हालका गुनासोहरू',
  adminTotalGrievances: 'कुल गुनासो',
  adminOpen: 'खुला',
  adminNoGrievances: 'यस दृश्यमा कुनै गुनासो छैन।',
  adminAiSummary: 'AI विषय सारांश',
  adminAiNone: 'यस दृश्यका लागि कुनै गुनासो रेकर्ड गरिएको छैन।',
  adminPosDm: 'जिल्ला म्याजिस्ट्रेट',
  adminPosBdo: 'ब्लक विकास अधिकृत',
  adminPosPanchayat: 'पञ्चायत सचिव',
  adminPosWelfare: 'कल्याण अधिकृत',
  adminPosAudit: 'सामाजिक लेखापरीक्षण संयोजक',
  adminPosState: 'राज्य नोडल अधिकृत',
  adminPosManager: 'कार्यक्रम व्यवस्थापक',
  // common
  commonSubmit: 'पेश गर्नुहोस्',
  commonCancel: 'रद्द गर्नुहोस्',
  commonLoading: 'लोड हुँदै…',
}
