export const _or = {
  // nav
  navFeatures: 'ସୁବିଧାସମୂହ',
  navOversight: 'ନିରୀକ୍ଷଣ',
  navSignIn: 'ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
  // hero
  heroBadge: 'କଲ୍ୟାଣ ନୀତି କାର୍ଯ୍ୟକାରିତା',
  heroTitle1: 'ନିର୍ଭୁଲ ଶାସନ।',
  heroTitle2: 'ପୁନଃ କଳ୍ପନା କରାଯାଇଛି।',
  heroSubtitle: 'ଏକ ସୁରକ୍ଷିତ, ନାଗରିକ-ପ୍ରଥମ ମଞ୍ଚ ଯେଉଁଠାରେ ବାସ୍ତବ ସମୟ ତଥ୍ୟ, ବିକେନ୍ଦ୍ରୀକୃତ ପରିଚୟ ଏବଂ ପ୍ରତ୍ୟକ୍ଷ ପ୍ରଦାନ ସଠିକ୍ ବ୍ୟକ୍ତିଙ୍କ ନିକଟକୁ କଲ୍ୟାଣ ସୁବିଧା ପହଞ୍ଚାଏ।',
  heroCta: 'ଆପଣଙ୍କ ଡ୍ୟାଶବୋର୍ଡ୍ ଆକ୍ସେସ୍ କରନ୍ତୁ',
  // features
  featuresBadge: 'କ୍ଷମତାସମୂହ',
  featuresTitle: 'ଏକ ଆଧୁନିକ କଲ୍ୟାଣ ବ୍ୟବସ୍ଥା ପାଇଁ ଆବଶ୍ୟକ ସବୁ କିଛି।',
  featuresSubtitle: 'ଏକ ସଂଯୁକ୍ତ ମଞ୍ଚ ପରିଚୟ, ଲକ୍ଷ୍ୟବସ୍ତୁ, ପେମେଣ୍ଟ ଏବଂ ଜବାବଦେହିତାକୁ ଏକତ୍ର କରେ।',
  tileDynamicRegistries: 'ଗତିଶୀଳ ସାମାଜିକ-ଅର୍ଥନୈତିକ ରେଜିଷ୍ଟ୍ରୀ',
  tileDynamicRegistriesDesc: 'କର, ଉପଯୋଗିତା ଏବଂ ନାଗରିକ ରେକର୍ଡ଼ରୁ ନିରନ୍ତର ଯୋଗ୍ୟତା ଅଦ୍ୟତନ — ଯଥାର୍ଥକୁ ପ୍ରତିବିମ୍ବିତ କରୁଥିବା ଲକ୍ଷ୍ୟବସ୍ତୁ, କେବେ ପୁରୁଣା ଜନଗଣନା ନୁହେଁ।',
  tileBiometrics: 'ବିକେନ୍ଦ୍ରୀକୃତ ବାୟୋମେଟ୍ରିକ୍ସ',
  tileBiometricsDesc: 'ସୁରକ୍ଷିତ, ବିକେନ୍ଦ୍ରୀକୃତ ବାୟୋମେଟ୍ରିକ୍ ପରିଚୟ ଯାହା ଦ୍ୱାର ଦ୍ୱାରେ ପରିଚୟ ଜାଲିଆତି ଏବଂ ଦ୍ୱିଗୁଣ ଲାଭ ବନ୍ଦ ହୁଏ।',
  tileDbt: 'ପ୍ରତ୍ୟକ୍ଷ ଲାଭ ପ୍ରଦାନ (DBT)',
  tileDbtDesc: 'ନଗଦ ଏବଂ ଭରତୁକି ସିଧାସଳଖ ଯାଞ୍ଚକୃତ ନାଗରିକ ଖାତାକୁ — କୌଣସି ମଧ୍ୟସ୍ଥୀ ନାହିଁ।',
  tileConditional: 'ସର୍ତ୍ତାଧୀନ ପ୍ରଦାନ',
  tileConditionalDesc: 'ପରିମେୟ ସାମାଜିକ ଫଳାଫଳ ପାଇଁ ଶିକ୍ଷା ଏବଂ ସ୍ୱାସ୍ଥ୍ୟ ମାଇଲଖୁଁଟରେ ଆବଦ୍ଧ ଅର୍ଥ ପ୍ରଦାନ।',
  tileAudits: 'ସମୁଦାୟ ସାମାଜିକ ନିରୀକ୍ଷଣ',
  tileAuditsDesc: 'ସାର୍ବଜନୀକ ସଭା ଯେଉଁଠାରେ ନାଗରିକମାନେ ଭୂମିରେ ଥିବା ସମ୍ପତ୍ତି ବିରୁଦ୍ଧରେ ବ୍ୟୟରେ ପ୍ରଶ୍ନ କରନ୍ତି।',
  tileAi: 'ସ୍ୱୟଂଚାଳିତ ବ୍ୟତିକ୍ରମ ରିପୋର୍ଟ',
  tileAiDesc: 'AI ସନ୍ଦେହଜନକ ପ୍ୟାଟର୍ନ ଚିହ୍ନିତ କରେ — ଯଥା ଏକାଧିକ ଲାଭ ଖାତା ସହିତ ଜଡ଼ିତ ଏକ ଫୋନ୍ ନମ୍ବର — ତତ୍କ୍ଷଣ ତଦନ୍ତ ପାଇଁ।',
  // oversight
  oversightBadge: 'ମନ୍ତ୍ରାଳୟ ନିରୀକ୍ଷଣ',
  oversightTitle: 'ମନ୍ତ୍ରାଳୟ କାଢ଼ାକାଠି ଏବଂ ପାଟିଭୂମି',
  oversightSubtitle: 'ମନ୍ତ୍ରାଳୟଗୁଡ଼ିକ ଆଇନଗତ କାଢ଼ାକାଠି ସ୍ଥାପନ କରି, ନିରୀକ୍ଷଣ ବଜେଟ୍ ବଣ୍ଟନ କରି, ସୁରକ୍ଷିତ ତଥ୍ୟ ବ୍ୟବସ୍ଥା ରକ୍ଷଣାବେକ୍ଷଣ କରି ଏବଂ ଦଣ୍ଡ କାର୍ଯ୍ୟକାରୀ କରି କଲ୍ୟାଣ ନୀତି ନିରୀକ୍ଷଣ ତଦାରଖ କରନ୍ତି।',
  pillarAudit: 'ବାଧ୍ୟତାମୂଳକ ନିରୀକ୍ଷଣ ନିର୍ଦ୍ଦେଶାବଳୀ',
  pillarAuditDesc: 'ମାନକ ପ୍ରଚାଳନ ପ୍ରଣାଳୀ ଏବଂ ଆଇନଗତ କାଢ଼ାକାଠି ଯାହା ସାମାଜିକ ଏବଂ ଆର୍ଥିକ ନିରୀକ୍ଷଣକୁ ବାଧ୍ୟତାମୂଳକ କରେ।',
  pillarMetrics: 'ସ୍ପଷ୍ଟ କାର୍ୟକ୍ଷମତା ମାପଦଣ୍ଡ',
  pillarMetricsDesc: 'ପରିମେୟ ମାପଦଣ୍ଡ — ଯଥା ଖରାପ ପୁଷ୍ଟି କିମ୍ବା ବେରୋଜଗାରୀରେ ନିର୍ଦ୍ଦିଷ୍ଟ ହ୍ରାସ ହାର।',
  pillarBodies: 'ସ୍ୱାଧୀନ ସଂସ୍ଥା',
  pillarBodiesDesc: 'ରାଜନୈତିକ ହସ୍ତକ୍ଷେପ ବିରୁଦ୍ଧରେ ତୃତୀୟ ପକ୍ଷ ଅଡିଟର ଏବଂ ସ୍ଥାନୀୟ ସାମାଜିକ ନିରୀକ୍ଷଣ ଏକକ ପାଇଁ ଆଇନଗତ ସୁରକ୍ଷା।',
  pillarDatabases: 'ସୁରକ୍ଷିତ ପ୍ରଧାନ ତଥ୍ୟାଗାର',
  pillarDatabasesDesc: 'କେବଳ ଅଧିକୃତ ନିରୀକ୍ଷଣ ସଂସ୍ଥାଙ୍କ ପାଇଁ ପ୍ରବେଶଯୋଗ୍ୟ ପରିଷ୍କାର ତଥ୍ୟ ସହିତ କେନ୍ଦ୍ରୀୟ ଲାଭାର୍ଥୀ ରେଜିଷ୍ଟ୍ରୀ।',
  // footer
  footerTagline: 'ଲୋକ-ପ୍ରଥମ ନୀତି ପାଇଁ ନିର୍ଭୁଲ ଶାସନ।',
  footerSub: 'ଗତିଶୀଳ ରେଜିଷ୍ଟ୍ରୀ · ବିକେନ୍ଦ୍ରୀକୃତ ବାୟୋମେଟ୍ରିକ୍ସ · ପ୍ରତ୍ୟକ୍ଷ ଲାଭ ପ୍ରଦାନ',
  // login
  loginTitle: 'ପୁନର୍ବାର ସ୍ୱାଗତ',
  loginSubtitle: 'ଆପଣଙ୍କ ସୁରକ୍ଷିତ ନାଗରିକ ଡ୍ୟାଶବୋର୍ଡ୍ ଆକ୍ସେସ୍ କରିବା ପାଇଁ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ। ନୂଆ ନାଗରିକମାନେ ଦୁଇ ମିନିଟ୍ ରୁ କମ୍ ସମୟରେ ଅନବୋର୍ଡ୍ ହୁଅନ୍ତି।',
  loginContinueGoogle: 'Google ସହିତ ଆଗେଇ ଯାନ୍ତୁ',
  loginContinueDemo: 'Demo Account ସହିତ ଆଗେଇ ଯାନ୍ତୁ',
  loginDemoHint: 'Demo Account',
  loginPresetLabel: 'ଏକ ଡେମୋ ନାଗରିକ ଶୀଘ୍ର ପୂରଣ କରନ୍ତୁ:',
  loginOrUse: 'କିମ୍ବା ଆପଣଙ୍କ ବିବରଣୀ ବ୍ୟବହାର କରନ୍ତୁ',
  loginEmail: 'ଇମେଲ୍',
  loginName: 'ନାମ',
  loginImage: 'ପ୍ରତିଛବି URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'ଆପଣଙ୍କ Aadhaar ଯାଞ୍ଚ କରନ୍ତୁ',
  verifySubtitle: 'ଏକ ଥରିଆ ପରିଚୟ ଯାଞ୍ଚ ଆପଣଙ୍କ କଲ୍ୟାଣ ଡ୍ୟାଶବୋର୍ଡ୍ ଖୋଲେ।',
  verifyAadhaarLabel: '୧୨-ଅଙ୍କର Aadhaar ନମ୍ବର',
  verifyMobileLabel: 'OTP ପାଇବା ପାଇଁ ମୋବାଇଲ୍ ନମ୍ବର',
  verifyGenerateOtp: 'OTP ସୃଷ୍ଟି କରନ୍ତୁ',
  verifySendingOtp: 'OTP ପଠାଯାଉଛି…',
  verifyDemoNote: 'ଡେମୋ ମୋଡ୍ — OTP ଅନୁରୋଧ ଅନୁକରଣ କରାଯାଇଛି। କୌଣସି ପ୍ରକୃତ Aadhaar ତଥ୍ୟ ପ୍ରେରିତ ହେଉନାହିଁ।',
  verifyOtpSentTo: 'ଆପଣଙ୍କ ରଜିଷ୍ଟର୍ଡ ମୋବାଇଲ୍ ନମ୍ବରକୁ ପଠାଯାଇଥିବା OTP',
  verifyDemoOtpLabel: 'Demo OTP:',
  verifyDemoOtpNote: 'ପ୍ରକୃତ ଡିପ୍ଲଏମେଣ୍ଟ୍ ଏହା SMS ମାଧ୍ୟମରେ ପଠାଏ — ଏଠାରେ ପରୀକ୍ଷା ପାଇଁ ଦେଖାଯାଉଛି।',
  verifyOtpLabel: '୬-ଅଙ୍କର OTP',
  verifyVerifyOtp: 'OTP ଯାଞ୍ଚ କରନ୍ତୁ',
  verifyVerifying: 'ଯାଞ୍ଚ କରାଯାଉଛି…',
  verifyChangeAadhaar: 'Aadhaar ନମ୍ବର ପରିବର୍ତ୍ତନ କରନ୍ତୁ',
  verifyIdentityVerified: 'ପରିଚୟ ଯାଞ୍ଚ ହୋଇଛି',
  verifyRedirecting: 'ଆପଣଙ୍କ ଡ୍ୟାଶବୋର୍ଡ୍ କୁ ରିଡାଇରେକ୍ଟ୍ କରାଯାଉଛି…',
  verifyInvalidAadhaar: 'ଦୟାକରି ଏକ ବୈଧ ୧୨-ଅଙ୍କର Aadhaar ନମ୍ବର ପ୍ରବେଶ କରନ୍ତୁ।',
  verifyInvalidOtp: 'ଦୟାକରି ଆପଣଙ୍କ ଫୋନ୍କୁ ପଠାଯାଇଥିବା ୬-ଅଙ୍କର OTP ପ୍ରବେଶ କରନ୍ତୁ।',
  verifyInvalidMobile: 'ଦୟାକରି ଏକ ବୈଧ ୧୦-ଅଙ୍କର ମୋବାଇଲ୍ ନମ୍ବର ପ୍ରବେଶ କରନ୍ତୁ।',
  verifyFailedGenerate: 'OTP ସୃଷ୍ଟି କରିବାରେ ବିଫଳ।',
  verifyFailedVerify: 'ଯାଞ୍ଚ ବିଫଳ ହୋଇଛି। ଦୟାକରି ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ।',
  verifySpeakHint: 'ମାଇକ୍ ଟିପ୍ କରନ୍ତୁ ଏବଂ ଆପଣଙ୍କ Aadhaar କିମ୍ବା OTP କହନ୍ତୁ',
  // dashboard
  dashWelcome: 'ସ୍ୱାଗତ',
  dashCitizen: 'ନାଗରିକ',
  dashVerified: 'ଯାଞ୍ଚ ସ୍ଥିତି: ଯାଞ୍ଚ ହୋଇଛି',
  dashPending: 'ଯାଞ୍ଚ ସ୍ଥିତି: ବିଚାରାଧୀନ',
  dashVerifyAadhaar: 'Aadhaar ଯାଞ୍ଚ କରନ୍ତୁ',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'ସାଇନ୍ ଆଉଟ୍ କରନ୍ତୁ',
  dashFoodSubsidy: 'ଖାଦ୍ୟ ଭରତୁକି (PDS)',
  dashDbt: 'ପ୍ରତ୍ୟକ୍ଷ ଲାଭ ପ୍ରଦାନ',
  dashEducation: 'ଶିକ୍ଷା ଅନୁଦାନ',
  dashHealth: 'ସ୍ୱାସ୍ଥ୍ୟ କଭରେଜ୍',
  dashNotEnrolled: 'ନାମ ଲେଖାଯାଇନାହିଁ',
  dashNextSocialAudit: 'ପରବର୍ତ୍ତୀ ସାମାଜିକ ନିରୀକ୍ଷଣ',
  dashSocialAuditDesc: 'ଆପଣଙ୍କ ଗ୍ରାମର ସାର୍ବଜନୀକ ବ୍ୟୟ ସମୀକ୍ଷା — ସମସ୍ତ ବାସିନ୍ଦାଙ୍କ ପାଇଁ ଉମ୍ମୁକ୍ତ।',
  // admin
  adminAccess: 'ପ୍ରଶାସକ ଆକ୍ସେସ୍',
  adminOversightPortal: 'ମନ୍ତ୍ରାଳୟ ନିରୀକ୍ଷଣ ପୋର୍ଟାଲ୍',
  adminAccessPassword: 'ଆକ୍ସେସ୍ ପାସୱାର୍ଡ୍',
  adminEnterPortal: 'ପୋର୍ଟାଲ୍ ପ୍ରବେଶ କରନ୍ତୁ',
  adminIncorrect: 'ଭୁଲ୍ ପାସୱାର୍ଡ୍। ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ।',
  adminDemoPassword: 'Demo password:',
  adminRegistration: 'ଅଫିସିଆଲ୍ ରଜିଷ୍ଟ୍ରେସନ୍',
  adminRegisterDesc: 'ଅଭିଯୋଗ ଡ୍ୟାଶବୋର୍ଡ୍ ଆକ୍ସେସ୍ କରିବା ପାଇଁ ଆପଣଙ୍କ ନିରୀକ୍ଷଣ ଭୂମିକା ରଜିଷ୍ଟର୍ କରନ୍ତୁ।',
  adminFullName: 'ପୂର୍ଣ୍ଣ ନାମ',
  adminEmail: 'ଅଫିସିଆଲ୍ ଇମେଲ୍',
  adminPhone: 'ଫୋନ୍',
  adminPosition: 'ପଦ',
  adminState: 'ରାଜ୍ୟ',
  adminDistrict: 'ଜିଲ୍ଲା',
  adminSelectState: 'ରାଜ୍ୟ ବାଛନ୍ତୁ',
  adminSelectDistrict: 'ଜିଲ୍ଲା ବାଛନ୍ତୁ',
  adminRegisterContinue: 'ରଜିଷ୍ଟର୍ କରନ୍ତୁ ଏବଂ ଆଗେଇ ଯାନ୍ତୁ',
  adminOversightDashboard: 'ନିରୀକ୍ଷଣ ଡ୍ୟାଶବୋର୍ଡ୍',
  adminGrievanceIntelligence: 'ଅଭିଯୋଗ ଗୋୟେନ୍ଦାଗିରି',
  adminAllDistricts: 'ସମସ୍ତ ଜିଲ୍ଲା',
  adminExit: 'ପ୍ରସ୍ଥାନ',
  adminStatusDistribution: 'ସ୍ଥିତି ବିତରଣ',
  adminByCategory: 'ବିଭାଗ ଅନୁଯାୟୀ ଅଭିଯୋଗ',
  adminDistrictBreakdown: 'ଜିଲ୍ଲା ବିଭାଜନ',
  adminRecentGrievances: 'ସାମ୍ପ୍ରତିକ ଅଭିଯୋଗ',
  adminTotalGrievances: 'ମୋଟ ଅଭିଯୋଗ',
  adminOpen: 'ଖୋଲା',
  adminNoGrievances: 'ଏହି ଦୃଶ୍ୟରେ କୌଣସି ଅଭିଯୋଗ ନାହିଁ।',
  adminAiSummary: 'AI ବିଷୟ ସାରାଂଶ',
  adminAiNone: 'ଏହି ଦୃଶ୍ୟ ପାଇଁ କୌଣସି ଅଭିଯୋଗ ରେକର୍ଡ୍ କରାଯାଇନାହିଁ।',
  adminPosDm: 'ଜିଲ୍ଲା ମେଜିଷ୍ଟ୍ରେଟ୍',
  adminPosBdo: 'ବ୍ଲକ୍ ଡେଭେଲପମେଣ୍ଟ ଅଫିସର୍',
  adminPosPanchayat: 'ପଞ୍ଚାୟତ ସଚିବ',
  adminPosWelfare: 'କଲ୍ୟାଣ ଅଫିସର୍',
  adminPosAudit: 'ସାମାଜିକ ନିରୀକ୍ଷଣ ସମନ୍ୱୟକର୍ତ୍ତା',
  adminPosState: 'ରାଜ୍ୟ ନୋଡାଲ୍ ଅଫିସର୍',
  adminPosManager: 'ପ୍ରୋଗ୍ରାମ୍ ମ୍ୟାନେଜର୍',
  // common
  commonSubmit: 'ଦାଖଲ କରନ୍ତୁ',
  commonCancel: 'ବାତିଲ୍ କରନ୍ତୁ',
  commonLoading: 'ଲୋଡ୍ ହେଉଛି…',
}
