export const _pa = {
  // nav
  navFeatures: 'ਸੁਵਿਧਾਵਾਂ',
  navOversight: 'ਨਿਗਰਾਨੀ',
  navSignIn: 'ਸਾਈਨ ਇਨ',
  // hero
  heroBadge: 'ਕਲਿਆਣ ਨੀਤੀ ਲਾਗੂਕਰਨ',
  heroTitle1: 'ਸ਼ੁੱਧ ਸਾਸ਼ਨ।',
  heroTitle2: 'ਮੁੜ ਕਲਪੀ।',
  heroSubtitle: 'ਇੱਕ ਸੁਰੱਖਿਅਤ, ਨਾਗਰਿਕ-ਪਹਿਲ ਪਲੇਟਫਾਰਮ ਜਿੱਥੇ ਰੀਅਲ-ਟਾਈਮ ਡੇਟਾ, ਵਿਕੇਂਦਰਿਤ ਪਛਾਣ, ਅਤੇ ਸਿੱਧੀਆਂ ਟ੍ਰਾਂਸਫਰਾਂ ਕਲਿਆਣ ਲਾਭਾਂ ਨੂੰ ਬਿਲਕੁਲ ਸਹੀ ਲੋਕਾਂ ਤੱਕ ਪਹੁੰਚਾਉਂਦੀਆਂ ਹਨ।',
  heroCta: 'ਆਪਣਾ Dashboard ਐਕਸੈਸ ਕਰੋ',
  // features
  featuresBadge: 'ਸਮਰੱਥਾਵਾਂ',
  featuresTitle: 'ਇੱਕ ਆਧੁਨਿਕ ਕਲਿਆਣ ਪ੍ਰਣਾਲੀ ਨੂੰ ਲੋੜੀਂਦੀ ਹਰ ਚੀਜ਼।',
  featuresSubtitle: 'ਇੱਕ ਜੁੜਿਆ ਪਲੇਟਫਾਰਮ ਪਛਾਣ, ਲਕ੍ਸ਼ਿਤੀਕਰਨ, ਭੁਗਤਾਨ, ਅਤੇ ਜਵਾਬਦੇਹੀ ਨੂੰ ਇੱਕਜੁੱਟ ਕਰਦਾ ਹੈ।',
  tileDynamicRegistries: 'ਗਤੀਸ਼ੀਲ ਸਮਾਜਿਕ-ਆਰਥਿਕ ਰਜਿਸਟਰੀਆਂ',
  tileDynamicRegistriesDesc: 'ਟੈਕਸ, ਉਪਯੋਗਿਤਾ, ਅਤੇ ਨਾਗਰਿਕ ਰਿਕਾਰਡਾਂ ਤੋਂ ਲਗਾਤਾਰ ਯੋਗਤਾ ਅੱਪਡੇਟ — ਲਕ੍ਸ਼ਿਤੀਕਰਨ ਜੋ ਹਮੇਸ਼ਾ ਹਕੀਕਤ ਨੂੰ ਦਰਸਾਉਂਦਾ ਹੈ, ਕਦੇ ਵੀ ਪੁਰਾਣੀ ਜਨਗਣਨਾ ਨਹੀਂ।',
  tileBiometrics: 'ਵਿਕੇਂਦਰਿਤ ਬਾਇਓਮੈਟ੍ਰਿਕਸ',
  tileBiometricsDesc: 'ਸੁਰੱਖਿਅਤ, ਵਿਕੇਂਦਰਿਤ ਬਾਇਓਮੈਟ੍ਰਿਕ ਆਈਡੀਆਂ ਜੋ ਦਰਵਾਜ਼ੇ ’ਤੇ ਪਛਾਣ ਧੋਖਾਧੜੀ ਅਤੇ ਦੋਹਰੀ ਵਸੂਲੀ ਨੂੰ ਰੋਕਦੀਆਂ ਹਨ।',
  tileDbt: 'ਸਿੱਧੇ ਲਾਭ ਟ੍ਰਾਂਸਫਰ (DBT)',
  tileDbtDesc: 'ਨਕਦ ਅਤੇ ਸਬਸਿਡੀਆਂ ਸਤਿਆਪਿਤ ਨਾਗਰਿਕ ਖਾਤਿਆਂ ਵਿੱਚ ਸਿੱਧੀਆਂ ਭੇਜੀਆਂ ਜਾਂਦੀਆਂ ਹਨ — ਕੋਈ ਵਿਚੋਲਾ ਨਹੀਂ।',
  tileConditional: 'ਸ਼ਰਤੀਆ ਟ੍ਰਾਂਸਫਰ',
  tileConditionalDesc: 'ਸਿੱਖਿਆ ਅਤੇ ਸਿਹਤ ਦੇ ਮੀਲ ਪੱਥਰਾਂ ਨਾਲ ਜੁੜੀਆਂ ਅਦਾਇਗੀਆਂ ਨਾਪੇ ਜਾ ਸਕਣ ਯੋਗ ਸਮਾਜਿਕ ਨਤੀਜਿਆਂ ਲਈ।',
  tileAudits: 'ਭਾਈਚਾਰਕ ਸਮਾਜਿਕ ਆਡਿਟ',
  tileAuditsDesc: 'ਜਨਤਕ ਇਕੱਠ ਜਿੱਥੇ ਨਾਗਰਿਕ ਜ਼ਮੀਨੀ ਸੰਪਤੀਆਂ ਦੇ ਖਿਲਾਫ ਖਰਚੇ ਦੀ ਜਾਂਚ ਕਰਦੇ ਹਨ।',
  tileAi: 'ਸਵੈਚਲਿਤ ਅਪਵਾਦ ਰਿਪੋਰਟਾਂ',
  tileAiDesc: 'AI ਸ਼ੱਕੀ ਪੈਟਰਨਾਂ ਨੂੰ ਫਲੈਗ ਕਰਦਾ ਹੈ — ਜਿਵੇਂ ਕਈ ਲਾਭ ਖਾਤਿਆਂ ਨਾਲ ਜੁੜਾ ਇੱਕ ਹੀ ਫ਼ੋਨ ਨੰਬਰ — ਤੁਰੰਤ ਜਾਂਚ ਲਈ।',
  // oversight
  oversightBadge: 'ਮੰਤਰਾਲਾ ਨਿਗਰਾਨੀ',
  oversightTitle: 'ਮੰਤਰਾਲਾ ਢਾਂਚਾ ਅਤੇ ਬੁਨਿਆਦੀ ਢਾਂਚਾ',
  oversightSubtitle: 'ਮੰਤਰਾਲੇ ਕਾਨੂੰਨੀ ਢਾਂਚੇ ਸਥਾਪਿਤ ਕਰਕੇ, ਨਿਗਰਾਨੀ ਬਜਟ ਨਿਰਧਾਰਤ ਕਰਕੇ, ਸੁਰੱਖਿਅਤ ਡੇਟਾ ਪ੍ਰਣਾਲੀਆਂ ਬਣਾਈ ਰੱਖ ਕੇ, ਅਤੇ ਜੁਰਮਾਨੇ ਲਾਗੂ ਕਰਕੇ ਕਲਿਆਣ ਨੀਤੀ ਆਡਿਟਾਂ ਦੀ ਨਿਗਰਾਨੀ ਕਰਦੇ ਹਨ।',
  pillarAudit: 'ਲਾਜ਼ਮੀ ਆਡਿਟ ਦਿਸ਼ਾ-ਨਿਰਦੇਸ਼',
  pillarAuditDesc: 'ਮਿਆਰੀ ਕਾਰਵਾਈ ਵਿਧੀਆਂ ਅਤੇ ਕਾਨੂੰਨੀ ਢਾਂਚੇ ਜੋ ਸਮਾਜਿਕ ਅਤੇ ਵਿੱਤੀ ਆਡਿਟਾਂ ਨੂੰ ਲਾਜ਼ਮੀ ਬਣਾਉਂਦੇ ਹਨ।',
  pillarMetrics: 'ਸਪੱਸ਼ਟ ਪ੍ਰਦਰਸ਼ਨ ਮੈਟ੍ਰਿਕ',
  pillarMetricsDesc: 'ਨਾਪੇ ਜਾ ਸਕਣ ਯੋਗ ਬੈਂਚਮਾਰਕ — ਜਿਵੇਂ ਸੱਟ ਜਾਂ ਬੇਰੋਜ਼ਗਾਰੀ ਵਿੱਚ ਖਾਸ ਘਟਾਓ ਦਰਾਂ।',
  pillarBodies: 'ਸੁਤੰਤਰ ਸੰਸਥਾਵਾਂ',
  pillarBodiesDesc: 'ਤੀਜੀ ਧਿਰ ਦੇ ਆਡੀਟਰਾਂ ਅਤੇ ਸਥਾਨਕ ਸਮਾਜਿਕ ਆਡਿਟ ਇਕਾਈਆਂ ਲਈ ਸਿਆਸੀ ਦਖ਼ਲੰਦਾਜ਼ੀ ਵਿਰੁੱਧ ਕਾਨੂੰਨੀ ਸੁਰੱਖਿਆ।',
  pillarDatabases: 'ਸੁਰੱਖਿਅਤ ਮਾਸਟਰ ਡੇਟਾਬੇਸ',
  pillarDatabasesDesc: 'ਕੇਂਦਰੀ ਲਾਭਾਰਥੀ ਰਜਿਸਟਰੀਆਂ ਸਾਫ਼ ਡੇਟਾ ਨਾਲ, ਜੋ ਸਿਰਫ਼ ਅਧਿਕਾਰਤ ਆਡਿਟ ਏਜੰਸੀਆਂ ਲਈ ਸੁਲੱਭ ਹਨ।',
  // footer
  footerTagline: 'ਲੋਕ-ਪਹਿਲ ਨੀਤੀ ਲਈ ਸ਼ੁੱਧ ਸਾਸ਼ਨ।',
  footerSub: 'ਗਤੀਸ਼ੀਲ ਰਜਿਸਟਰੀਆਂ · ਵਿਕੇਂਦਰਿਤ ਬਾਇਓਮੈਟ੍ਰਿਕਸ · ਸਿੱਧੇ ਲਾਭ ਟ੍ਰਾਂਸਫਰ (DBT)',
  // login
  loginTitle: 'ਫਿਰ ਜੀ ਆਇਆਂ ਨੂੰ',
  loginSubtitle: 'ਆਪਣਾ ਸੁਰੱਖਿਅਤ ਨਾਗਰਿਕ Dashboard ਐਕਸੈਸ ਕਰਨ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ। ਨਵੇਂ ਨਾਗਰਿਕ ਦੋ ਮਿੰਟ ਤੋਂ ਘੱਟ ਸਮੇਂ ਵਿੱਚ ਆਨਬੋਰਡ ਕੀਤੇ ਜਾਂਦੇ ਹਨ।',
  loginContinueGoogle: 'Google ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
  loginContinueDemo: 'Demo Account ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
  loginDemoHint: 'Demo Account',
  loginPresetLabel: 'ਤੇਜ਼ੀ ਨਾਲ ਇੱਕ ਡੈਮੋ ਨਾਗਰਿਕ ਭਰੋ:',
  loginOrUse: 'ਜਾਂ ਆਪਣੀਆਂ ਜਾਣਕਾਰੀਆਂ ਵਰਤੋ:',
  loginEmail: 'ਈਮੇਲ',
  loginName: 'ਨਾਮ',
  loginImage: 'ਚਿੱਤਰ URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'ਆਪਣਾ Aadhaar ਸਤਿਆਪਿਤ ਕਰੋ',
  verifySubtitle: 'ਇੱਕ ਵਾਰੀ ਪਛਾਣ ਸਤਿਆਪਨ ਤੁਹਾਡਾ ਕਲਿਆਣ Dashboard ਖੋਲ੍ਹਦਾ ਹੈ।',
  verifyAadhaarLabel: '12-ਅੰਕੀ Aadhaar ਨੰਬਰ',
  verifyMobileLabel: 'OTP ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਮੋਬਾਈਲ ਨੰਬਰ',
  verifyGenerateOtp: 'OTP ਬਣਾਓ',
  verifySendingOtp: 'OTP ਭੇਜੀ ਜਾ ਰਹੀ ਹੈ…',
  verifyDemoNote: 'ਡੈਮੋ ਮੋਡ — OTP ਬੇਨਤੀ ਦੀ ਨਕਲ ਕੀਤੀ ਜਾਂਦੀ ਹੈ। ਕੋਈ ਅਸਲੀ Aadhaar ਡੇਟਾ ਪ੍ਰਸਾਰਿਤ ਨਹੀਂ ਹੁੰਦਾ।',
  verifyOtpSentTo: 'ਤੁਹਾਡੇ ਰਜਿਸਟਰਡ ਮੋਬਾਈਲ ਨੰਬਰ ’ਤੇ OTP ਭੇਜਿਆ ਗਿਆ',
  verifyDemoOtpLabel: 'ਡੈਮੋ OTP:',
  verifyDemoOtpNote: 'ਅਸਲੀ ਤੈਨਾਤੀ ਇਹ SMS ਰਾਹੀਂ ਭੇਜਦੀ ਹੈ — ਟੈਸਟਿੰਗ ਲਈ ਇੱਥੇ ਦਿਖਾਇਆ ਗਿਆ।',
  verifyOtpLabel: '6-ਅੰਕੀ OTP',
  verifyVerifyOtp: 'OTP ਸਤਿਆਪਿਤ ਕਰੋ',
  verifyVerifying: 'ਸਤਿਆਪਿਤ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ…',
  verifyChangeAadhaar: 'Aadhaar ਨੰਬਰ ਬਦਲੋ',
  verifyIdentityVerified: 'ਪਛਾਣ ਸਤਿਆਪਿਤ',
  verifyRedirecting: 'ਤੁਹਾਡੇ Dashboard ’ਤੇ ਰੀਡਾਇਰੈਕਟ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ…',
  verifyInvalidAadhaar: 'ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ 12-ਅੰਕੀ Aadhaar ਨੰਬਰ ਦਾਖਲ ਕਰੋ।',
  verifyInvalidOtp: 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਫ਼ੋਨ ’ਤੇ ਭੇਜੀ 6-ਅੰਕੀ OTP ਦਾਖਲ ਕਰੋ।',
  verifyInvalidMobile: 'ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ 10-ਅੰਕੀ ਮੋਬਾਈਲ ਨੰਬਰ ਦਾਖਲ ਕਰੋ।',
  verifyFailedGenerate: 'OTP ਬਣਾਉਣ ਵਿੱਚ ਅਸਫਲ।',
  verifyFailedVerify: 'ਸਤਿਆਪਨ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
  verifySpeakHint: 'ਮਾਈਕ ’ਤੇ ਟੈਪ ਕਰੋ ਅਤੇ ਆਪਣਾ Aadhaar ਜਾਂ OTP ਬੋਲੋ',
  // dashboard
  dashWelcome: 'ਜੀ ਆਇਆਂ ਨੂੰ',
  dashCitizen: 'ਨਾਗਰਿਕ',
  dashVerified: 'ਸਤਿਆਪਨ ਸਥਿਤੀ: ਸਤਿਆਪਿਤ',
  dashPending: 'ਸਤਿਆਪਨ ਸਥਿਤੀ: ਬਾਕੀ',
  dashVerifyAadhaar: 'Aadhaar ਸਤਿਆਪਿਤ ਕਰੋ',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'ਸਾਈਨ ਆਉਟ',
  dashFoodSubsidy: 'ਭੋਜਨ ਸਬਸਿਡੀ (PDS)',
  dashDbt: 'ਸਿੱਧਾ ਲਾਭ ਟ੍ਰਾਂਸਫਰ (DBT)',
  dashEducation: 'ਸਿੱਖਿਆ ਗ੍ਰਾਂਟ',
  dashHealth: 'ਸਿਹਤ ਕਵਰੇਜ',
  dashNotEnrolled: 'ਦਾਖਲ ਨਹੀਂ',
  dashNextSocialAudit: 'ਅਗਲਾ ਸਮਾਜਿਕ ਆਡਿਟ',
  dashSocialAuditDesc: 'ਤੁਹਾਡੇ ਪਿੰਡ ਦੀ ਜਨਤਕ ਖਰਚ ਸਮੀਖਿਆ — ਸਾਰੇ ਵਾਸੀਆਂ ਲਈ ਖੁੱਲ੍ਹੀ।',
  // admin
  adminAccess: 'ਐਡਮਿਨ ਪਹੁੰਚ',
  adminOversightPortal: 'ਮੰਤਰਾਲਾ ਨਿਗਰਾਨੀ ਪੋਰਟਲ',
  adminAccessPassword: 'ਪਹੁੰਚ ਪਾਸਵਰਡ',
  adminEnterPortal: 'ਪੋਰਟਲ ਵਿੱਚ ਦਾਖਲ ਹੋਵੋ',
  adminIncorrect: 'ਗਲਤ ਪਾਸਵਰਡ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
  adminDemoPassword: 'ਡੈਮੋ ਪਾਸਵਰਡ:',
  adminRegistration: 'ਅਧਿਕਾਰਤ ਰਜਿਸਟ੍ਰੇਸ਼ਨ',
  adminRegisterDesc: 'ਆਪਣੀ ਨਿਗਰਾਨੀ ਭੂਮਿਕਾ ਰਜਿਸਟਰ ਕਰੋ ਤਾਂ ਜੋ ਸ਼ਿਕਾਇਤ Dashboard ਤੱਕ ਪਹੁੰਚ ਮਿਲੇ।',
  adminFullName: 'ਪੂਰਾ ਨਾਮ',
  adminEmail: 'ਅਧਿਕਾਰਤ ਈਮੇਲ',
  adminPhone: 'ਫ਼ੋਨ',
  adminPosition: 'ਅਹੁਦਾ',
  adminState: 'ਰਾਜ',
  adminDistrict: 'ਜ਼ਿਲ੍ਹਾ',
  adminSelectState: 'ਰਾਜ ਚੁਣੋ',
  adminSelectDistrict: 'ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ',
  adminRegisterContinue: 'ਰਜਿਸਟਰ ਕਰੋ ਅਤੇ ਜਾਰੀ ਰੱਖੋ',
  adminOversightDashboard: 'ਨਿਗਰਾਨੀ Dashboard',
  adminGrievanceIntelligence: 'ਸ਼ਿਕਾਇਤ ਇੰਟੈਲੀਜੈਂਸ',
  adminAllDistricts: 'ਸਾਰੇ ਜ਼ਿਲ੍ਹੇ',
  adminExit: 'ਬਾਹਰ ਜਾਓ',
  adminStatusDistribution: 'ਸਥਿਤੀ ਵੰਡ',
  adminByCategory: 'ਸ਼੍ਰੇਣੀ ਅਨੁਸਾਰ ਸ਼ਿਕਾਇਤਾਂ',
  adminDistrictBreakdown: 'ਜ਼ਿਲ੍ਹਾ ਵਾਰ ਵਿਵਰਣ',
  adminRecentGrievances: 'ਹਾਲੀਆ ਸ਼ਿਕਾਇਤਾਂ',
  adminTotalGrievances: 'ਕੁੱਲ ਸ਼ਿਕਾਇਤਾਂ',
  adminOpen: 'ਖੁੱਲ੍ਹੀਆਂ',
  adminNoGrievances: 'ਇਸ ਵਿਊ ਵਿੱਚ ਕੋਈ ਸ਼ਿਕਾਇਤ ਨਹੀਂ।',
  adminAiSummary: 'AI ਵਿਸ਼ਾ ਸਾਰਾਂਸ਼',
  adminAiNone: 'ਇਸ ਵਿਊ ਲਈ ਕੋਈ ਸ਼ਿਕਾਇਤ ਦਰਜ ਨਹੀਂ।',
  adminPosDm: 'ਜ਼ਿਲ੍ਹਾ ਮੈਜਿਸਟ੍ਰੇਟ',
  adminPosBdo: 'ਬਲਾਕ ਵਿਕਾਸ ਅਧਿਕਾਰੀ',
  adminPosPanchayat: 'ਪੰਚਾਇਤ ਸੈਕਟਰੀ',
  adminPosWelfare: 'ਕਲਿਆਣ ਅਧਿਕਾਰੀ',
  adminPosAudit: 'ਸਮਾਜਿਕ ਆਡਿਟ ਕੋਆਰਡੀਨੇਟਰ',
  adminPosState: 'ਰਾਜ ਨੋਡਲ ਅਧਿਕਾਰੀ',
  adminPosManager: 'ਪ੍ਰੋਗਰਾਮ ਮੈਨੇਜਰ',
  // common
  commonSubmit: 'ਜਮਾ ਕਰੋ',
  commonCancel: 'ਰੱਦ ਕਰੋ',
  commonLoading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…',
}
