export const _sat = {
  // nav
  navFeatures: 'ᱵᱤᱥᱮᱥᱚᱛᱟ',
  navOversight: 'ᱩᱱᱩᱥᱩᱢ',
  navSignIn: 'ᱥᱟᱹᱜᱩᱱ',
  // hero
  heroBadge: 'ᱨᱟᱹᱥᱠᱟᱹ ᱱᱤᱛᱤ ᱵᱟᱥᱱᱟᱣ',
  heroTitle1: 'ᱱᱤᱨᱚᱲ ᱥᱟᱥᱚᱱ᱾',
  heroTitle2: 'ᱯᱩᱱᱟᱹᱣ ᱟᱠᱟᱱ᱾',
  heroSubtitle: 'ᱢᱤᱫ ᱥᱩᱨᱠᱷᱤᱛ, ᱱᱟᱜᱟᱨᱤᱭᱟᱹ-ᱯᱟᱹᱦᱤᱞ ᱯᱞᱮᱴᱯᱷᱚᱨᱢ ᱡᱟᱦᱟᱸ ᱨᱮ ᱥᱚᱡᱚᱜ ᱥᱚᱢᱚᱭ ᱮᱞ, ᱵᱷᱮᱜᱟᱨ ᱥᱟᱹᱜᱩᱱ, ᱟᱨ ᱥᱚᱡᱷᱟ ᱛᱷᱟᱱ ᱠᱚ ᱨᱟᱹᱥᱠᱟᱹ ᱞᱟᱵᱷ ᱠᱚ ᱡᱚᱛᱚᱱ ᱦᱚᱲ ᱠᱷᱚᱱ ᱥᱚᱡᱷᱟ ᱛᱮ ᱥᱟᱲᱦᱟᱣᱟ᱾',
  heroCta: 'ᱟᱢᱟᱜ Dashboard ᱡᱚᱲᱟᱣ ᱢᱮ',
  // features
  featuresBadge: 'ᱥᱚᱢᱚᱨᱛᱷᱚᱱ',
  featuresTitle: 'ᱱᱟᱶᱟ ᱨᱟᱹᱥᱠᱟᱹ ᱥᱤᱥᱴᱚᱢ ᱞᱟᱹᱜᱤᱫ ᱡᱚᱛᱚ ᱞᱟᱠᱛᱤᱭᱟᱱ ᱪᱤᱡ᱾',
  featuresSubtitle: 'ᱢᱤᱫ ᱡᱚᱲᱟᱣ ᱯᱞᱮᱴᱯᱷᱚᱨᱢ ᱥᱟᱹᱜᱩᱱ, ᱯᱟᱱᱛᱷᱟ, ᱫᱟᱲᱮ ᱟᱨ ᱡᱚᱥ ᱛᱷᱟᱯᱚᱱ ᱠᱚ ᱢᱤᱫ ᱠᱚᱨᱟᱣᱟ᱾',
  tileDynamicRegistries: 'ᱥᱚᱡᱚᱜ ᱥᱚᱢᱟᱡᱤᱠ-ᱠᱟᱹᱣᱰᱤ ᱯᱚᱧᱡᱤᱠᱚᱨᱚᱱ',
  tileDynamicRegistriesDesc: 'ᱠᱚᱨ ᱟᱹᱠᱤᱞ, ᱤᱣᱴᱤᱞᱤᱴᱤ, ᱟᱨ ᱥᱤᱣᱤᱞ ᱨᱮᱠᱚᱰ ᱠᱷᱚᱱ ᱥᱟᱹᱨᱟᱹᱭ ᱞᱟᱹᱜᱤᱫ ᱟᱹᱯᱟᱲᱟᱣ — ᱡᱟᱦᱟᱸ ᱯᱟᱱᱛᱷᱟ ᱫᱚ ᱡᱤᱣᱤ ᱥᱟᱶ ᱡᱚᱲᱟᱣ ᱛᱟᱦᱮᱸᱱᱟ, ᱵᱟᱝ ᱢᱤᱫ ᱪᱷᱟᱹᱲᱣᱟᱹ ᱞᱮᱠᱷᱟ᱾',
  tileBiometrics: 'ᱵᱷᱮᱜᱟᱨ ᱵᱟᱭᱳᱢᱮᱴᱨᱤᱠ',
  tileBiometricsDesc: 'ᱥᱩᱨᱠᱷᱤᱛ, ᱵᱷᱮᱜᱟᱨ ᱵᱟᱭᱳᱢᱮᱴᱨᱤᱠ ᱥᱟᱹᱜᱩᱱ ᱡᱟᱦᱟᱸ ᱫᱚ ᱵᱷᱤᱛᱨᱤ ᱫᱷᱚᱠᱟ ᱟᱨ ᱵᱟᱨ ᱫᱷᱟᱣ ᱞᱟᱵᱷ ᱠᱚ ᱫᱩᱣᱟᱹᱨ ᱨᱮ ᱛᱷᱚᱯ ᱮᱫᱟ᱾',
  tileDbt: 'DBT',
  tileDbtDesc: 'ᱠᱟᱹᱣᱰᱤ ᱟᱨ ᱥᱚᱵᱥᱤᱰᱤ ᱥᱚᱡᱷᱟ ᱛᱮ ᱯᱨᱚᱢᱟᱬ ᱱᱟᱜᱟᱨᱤᱭᱟᱹ ᱮᱠᱟᱣᱩᱱᱴ ᱨᱮ — ᱢᱚᱸᱡᱮ ᱵᱤᱱᱟ ᱾',
  tileConditional: 'ᱥᱚᱨᱚᱛ ᱥᱟᱶ ᱛᱷᱟᱱ',
  tileConditionalDesc: 'ᱥᱮᱪᱮᱫ ᱟᱨ ᱥᱟᱥᱛᱷᱭᱚ ᱢᱤᱞ ᱥᱟᱶ ᱡᱚᱲᱟᱣ ᱯᱟᱱᱛᱷᱟ ᱞᱟᱹᱜᱤᱫ ᱮᱞᱠᱷᱟ ᱛᱮ ᱥᱟᱡᱟᱣ ᱥᱟᱶᱦᱮᱫ ᱯᱷᱚᱞ ᱾',
  tileAudits: 'ᱥᱟᱶᱦᱮᱫ ᱥᱟᱶᱟᱡᱽ ᱚᱰᱤᱴ',
  tileAuditsDesc: 'ᱥᱟᱶᱦᱮᱫ ᱵᱟᱯᱞᱟ ᱡᱟᱦᱟᱸ ᱨᱮ ᱱᱟᱜᱟᱨᱤᱭᱟᱹ ᱠᱚ ᱵᱷᱩᱭᱤ ᱨᱮ ᱢᱤᱞ ᱥᱟᱶ ᱠᱷᱚᱨᱪ ᱠᱚ ᱯᱨᱚᱥᱱ ᱠᱚᱨᱟᱣᱟ ᱾',
  tileAi: 'ᱚᱴᱚᱢᱮᱴᱮᱰ ᱮᱠᱥᱮᱯᱥᱚᱱ ᱨᱤᱯᱚᱴ',
  tileAiDesc: 'AI ᱫᱩᱱᱫᱩᱢ ᱥᱚᱱᱚᱫᱚ ᱯᱟᱹᱛᱤ — ᱡᱮᱞᱮᱠᱟ ᱢᱤᱫ ᱯᱷᱚᱱ ᱱᱚᱢᱵᱚᱨ ᱟᱭᱢᱟ ᱞᱟᱵᱷ ᱮᱠᱟᱣᱩᱱᱴ ᱥᱟᱶ ᱡᱚᱲᱟᱣ — ᱥᱚᱡᱷᱟ ᱛᱚᱞᱟᱥ ᱞᱟᱹᱜᱤᱫ ᱾',
  // oversight
  oversightBadge: 'ᱢᱚᱱᱛᱨᱤ ᱢᱚᱱᱰᱚᱲᱤ ᱩᱱᱩᱥᱩᱢ',
  oversightTitle: 'ᱢᱚᱱᱛᱨᱤ ᱢᱚᱱᱰᱚᱲᱤ ᱯᱷᱨᱮᱢᱣᱚᱨᱠ ᱟᱨ ᱤᱱᱯᱷᱨᱟᱥᱴᱨᱚᱠᱪᱚᱨ',
  oversightSubtitle: 'ᱢᱚᱱᱛᱨᱤ ᱢᱚᱱᱰᱚᱲᱤ ᱠᱚ ᱨᱟᱹᱥᱠᱟᱹ ᱱᱤᱛᱤ ᱚᱰᱤᱴ ᱠᱚ ᱩᱱᱩᱥᱩᱢ ᱠᱚᱨᱟᱣᱟ ᱟᱹᱨᱤ ᱯᱷᱨᱮᱢᱣᱚᱨᱠ ᱛᱷᱟᱯᱚᱱ, ᱩᱱᱩᱥᱩᱢ ᱵᱟᱡᱮᱴ ᱮᱢ, ᱥᱩᱨᱠᱷᱤᱛ ᱮᱞ ᱥᱤᱥᱴᱚᱢ ᱫᱚᱦᱚ, ᱟᱨ ᱥᱟᱡᱟ ᱠᱟᱹᱢᱤ ᱛᱟᱞᱟ ᱛᱮ ᱾',
  pillarAudit: 'ᱵᱟᱹᱲᱤᱡ ᱚᱰᱤᱴ ᱱᱤᱭᱚᱢ',
  pillarAuditDesc: 'ᱥᱚᱢᱟᱡᱤᱠ ᱟᱨ ᱠᱟᱹᱣᱰᱤ ᱚᱰᱤᱴ ᱵᱟᱹᱲᱤᱡ ᱠᱚᱨᱟᱣ ᱞᱟᱹᱜᱤᱫ ᱥᱴᱟᱱᱰᱟᱨᱰ ᱚᱯᱨᱮᱴᱤᱝ ᱯᱨᱚᱥᱤᱡᱚᱨ ᱟᱨ ᱟᱹᱨᱤ ᱯᱷᱨᱮᱢᱣᱚᱨᱠ ᱾',
  pillarMetrics: 'ᱥᱟᱯᱷ ᱯᱟᱨᱯᱷᱚᱨᱢᱮᱱᱥ ᱢᱤᱴᱨᱤᱠ',
  pillarMetricsDesc: 'ᱮᱞᱠᱷᱟ ᱛᱮ ᱱᱟᱯᱟᱭ ᱢᱟᱱ — ᱡᱮᱞᱮᱠᱟ ᱥᱴᱟᱱᱴᱤᱝ ᱟᱨ ᱠᱟᱹᱢᱤ ᱵᱤᱱ ᱨᱮ ᱡᱚᱛᱚᱨ ᱠᱚᱢᱚᱜ ᱫᱚᱨ ᱾',
  pillarBodies: 'ᱯᱷᱩᱨᱜᱟᱹᱞ ᱵᱚᱰᱤ',
  pillarBodiesDesc: 'ᱯᱚᱞᱤᱴᱤᱠᱟᱞ ᱫᱩᱠᱟᱱ ᱵᱤᱨᱩᱫᱷ ᱛᱮ ᱛᱮᱥᱟᱨ-ᱯᱟᱠᱷᱭᱟ ᱚᱰᱤᱴᱚᱨ ᱟᱨ ᱟᱹᱛᱩ ᱥᱟᱶᱦᱮᱫ ᱚᱰᱤᱴ ᱭᱩᱱᱤᱴ ᱞᱟᱹᱜᱤᱫ ᱟᱹᱨᱤ ᱥᱩᱨᱠᱷᱤᱭᱟ ᱾',
  pillarDatabases: 'ᱥᱩᱨᱠᱷᱤᱛ ᱢᱟᱥᱴᱚᱨ ᱮᱴᱮᱵᱟᱥ',
  pillarDatabasesDesc: 'ᱛᱟᱞᱢᱟ ᱞᱟᱵᱷᱤᱭᱟ ᱯᱚᱧᱡᱤᱠᱚᱨᱚᱱ ᱥᱟᱶ ᱥᱟᱯᱷ ᱮᱞ, ᱡᱟᱦᱟᱸ ᱠᱷᱚᱱ ᱠᱮᱵᱚᱞ ᱚᱫᱷᱤᱠᱟᱨ ᱟᱱ ᱚᱰᱤᱴ ᱮᱡᱮᱱᱥᱤ ᱠᱚ ᱧᱮᱞ ᱫᱟᱲᱮᱭᱟᱜ-ᱟ ᱾',
  // footer
  footerTagline: 'ᱦᱚᱲ-ᱯᱟᱹᱦᱤᱞ ᱱᱤᱛᱤ ᱞᱟᱹᱜᱤᱫ ᱱᱤᱨᱚᱲ ᱥᱟᱥᱚᱱ ᱾',
  footerSub: 'ᱥᱚᱡᱚᱜ ᱯᱚᱧᱡᱤᱠᱚᱨᱚᱱ · ᱵᱷᱮᱜᱟᱨ ᱵᱟᱭᱳᱢᱮᱴᱨᱤᱠ · DBT',
  // login
  loginTitle: 'ᱟᱨᱦᱚᱸ ᱦᱮᱡ ᱟᱠᱟᱱ',
  loginSubtitle: 'ᱟᱢᱟᱜ ᱥᱩᱨᱠᱷᱤᱛ ᱱᱟᱜᱟᱨᱤᱭᱟᱹ Dashboard ᱡᱚᱲᱟᱣ ᱞᱟᱹᱜᱤᱫ ᱥᱟᱹᱜᱩᱱ ᱢᱮ ᱾ ᱱᱟᱶᱟ ᱱᱟᱜᱟᱨᱤᱭᱟᱹ ᱠᱚ ᱵᱟᱨ ᱢᱤᱱᱤᱴ ᱠᱷᱚᱱ ᱠᱚᱢ ᱨᱮ ᱥᱟᱹᱜᱩᱱ ᱠᱚᱜ-ᱟ ᱾',
  loginContinueGoogle: 'Google ᱥᱟᱶ ᱛᱟᱭᱚᱢ ᱛᱮ ᱮᱫᱟᱭ ᱢᱮ',
  loginContinueDemo: 'Demo Account ᱥᱟᱶ ᱛᱟᱭᱚᱢ ᱛᱮ ᱮᱫᱟᱭ ᱢᱮ',
  loginDemoHint: 'Demo Account',
  loginPresetLabel: 'ᱢᱤᱫ ᱫᱷᱟᱨᱟ ᱱᱟᱜᱟᱨᱤᱭᱟᱹ ᱪᱟᱹᱠᱤ ᱯᱩᱨᱟᱹᱣ ᱢᱮ:',
  loginOrUse: 'ᱟᱨᱵᱟᱝ ᱟᱢᱟᱜ ᱡᱟᱱᱟᱢ ᱵᱤᱵᱚᱨ ᱵᱮᱵᱷᱟᱨ ᱢᱮ',
  loginEmail: 'ᱤᱢᱮᱞ',
  loginName: 'ᱧᱩᱛᱩᱢ',
  loginImage: 'ᱪᱤᱛᱟᱹᱨ URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'ᱟᱢᱟᱜ Aadhaar ᱯᱨᱚᱢᱟᱬ ᱢᱮ',
  verifySubtitle: 'ᱢᱤᱫ ᱫᱷᱟᱣ ᱥᱟᱹᱜᱩᱱ ᱯᱨᱚᱢᱟᱬ ᱟᱢᱟᱜ ᱨᱟᱹᱥᱠᱟᱹ Dashboard ᱩᱠᱷᱟᱹᱲ ᱮᱫᱟ ᱾',
  verifyAadhaarLabel: 'ᱡᱚᱛᱚ ᱑᱒ ᱚᱱᱚᱞ Aadhaar ᱱᱚᱢᱵᱚᱨ',
  verifyMobileLabel: 'OTP ᱧᱟᱢ ᱞᱟᱹᱜᱤᱫ ᱢᱚᱵᱟᱭᱤᱞ ᱱᱚᱢᱵᱚᱨ',
  verifyGenerateOtp: 'OTP ᱛᱮᱭᱟᱨ ᱢᱮ',
  verifySendingOtp: 'OTP ᱠᱩᱞᱤ ᱠᱟᱛᱮ ᱢᱮ…',
  verifyDemoNote: 'Demo mode — ᱱᱚᱣᱟ OTP ᱠᱩᱞᱤ ᱫᱚ ᱥᱤᱢᱩᱞᱮᱴ ᱠᱚᱜ-ᱟ ᱾ ᱥᱚᱪᱚ Aadhaar ᱮᱞ ᱵᱟᱝ ᱠᱩᱞᱤᱚᱜ-ᱟ ᱾',
  verifyOtpSentTo: 'OTP ᱠᱩᱞᱤ ᱥᱟᱹᱛ ᱮᱱᱟ ᱟᱢᱟᱜ ᱚᱞ ᱢᱚᱵᱟᱭᱤᱞ ᱱᱚᱢᱵᱚᱨ ᱨᱮ',
  verifyDemoOtpLabel: 'Demo OTP:',
  verifyDemoOtpNote: 'ᱥᱚᱪᱚ ᱠᱟᱹᱢᱤ ᱨᱮ ᱱᱚᱣᱟ SMS ᱛᱮ ᱠᱩᱞᱤᱚᱜ-ᱟ — ᱱᱚᱰᱮ ᱴᱮᱥᱴ ᱞᱟᱹᱜᱤᱫ ᱫᱮᱠᱷᱟᱣ ᱮᱢ ᱟᱠᱟᱱᱟ ᱾',
  verifyOtpLabel: 'ᱡᱚᱛᱚ ᱖-ᱚᱱᱚᱞ OTP',
  verifyVerifyOtp: 'OTP ᱯᱨᱚᱢᱟᱬ ᱢᱮ',
  verifyVerifying: 'ᱯᱨᱚᱢᱟᱬ ᱠᱟᱛᱮ ᱢᱮ…',
  verifyChangeAadhaar: 'Aadhaar ᱱᱚᱢᱵᱚᱨ ᱵᱚᱫᱚᱞ ᱢᱮ',
  verifyIdentityVerified: 'ᱥᱟᱹᱜᱩᱱ ᱯᱨᱚᱢᱟᱬ ᱮᱱᱟ',
  verifyRedirecting: 'ᱟᱢᱟᱜ Dashboard ᱨᱮ ᱯᱟᱨᱟᱹᱲ ᱠᱟᱛᱮ ᱢᱮ…',
  verifyInvalidAadhaar: 'ᱫᱟᱭᱟᱠ ᱢᱤᱫ ᱥᱚᱪᱚ ᱑᱒-ᱚᱱᱚᱞ Aadhaar ᱱᱚᱢᱵᱚᱨ ᱮᱢ ᱢᱮ ᱾',
  verifyInvalidOtp: 'ᱟᱢᱟᱜ ᱯᱷᱚᱱ ᱨᱮ ᱠᱩᱞᱤ ᱟᱠᱟᱱ ᱖-ᱚᱱᱚᱞ OTP ᱮᱢ ᱢᱮ ᱾',
  verifyInvalidMobile: 'ᱢᱤᱫ ᱥᱚᱪᱚ ᱑᱐-ᱚᱱᱚᱞ ᱢᱚᱵᱟᱭᱤᱞ ᱱᱚᱢᱵᱚᱨ ᱮᱢ ᱢᱮ ᱾',
  verifyFailedGenerate: 'OTP ᱛᱮᱭᱟᱨ ᱵᱟᱝ ᱜᱟᱱᱟᱜ ᱠᱟᱱᱟ ᱾',
  verifyFailedVerify: 'ᱯᱨᱚᱢᱟᱬ ᱵᱟᱝ ᱮᱱᱟ ᱾ ᱫᱩᱦᱲᱟᱹ ᱨᱮᱫᱟᱭ ᱢᱮ ᱾',
  verifySpeakHint: 'ᱢᱟᱭᱠ ᱪᱟᱹᱯ ᱢᱮ ᱟᱨ ᱟᱢᱟᱜ Aadhaar ᱟᱨᱵᱟᱝ OTP ᱞᱟᱹᱭ ᱢᱮ',
  // dashboard
  dashWelcome: 'ᱥᱣᱟᱜᱚᱛ',
  dashCitizen: 'ᱱᱟᱜᱟᱨᱤᱭᱟᱹ',
  dashVerified: 'ᱯᱨᱚᱢᱟᱬ ᱚᱵᱚᱥᱛᱟ: ᱯᱨᱚᱢᱟᱬ',
  dashPending: 'ᱯᱨᱚᱢᱟᱬ ᱚᱵᱚᱥᱛᱟ: ᱵᱟᱹᱠᱤ',
  dashVerifyAadhaar: 'Aadhaar ᱯᱨᱚᱢᱟᱬ ᱢᱮ',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'ᱵᱟᱦᱨᱮ ᱥᱮᱱ ᱢᱮ',
  dashFoodSubsidy: 'ᱡᱚᱢ ᱥᱚᱵᱥᱤᱰᱤ (PDS)',
  dashDbt: 'DBT',
  dashEducation: 'ᱥᱮᱪᱮᱫ ᱜᱽᱨᱟᱱᱴ',
  dashHealth: 'ᱥᱟᱥᱛᱷᱭᱚ ᱠᱚᱵᱷᱚᱨᱮᱡ',
  dashNotEnrolled: 'ᱵᱟᱝ ᱚᱞ ᱟᱠᱟᱱ',
  dashNextSocialAudit: 'ᱟᱜᱟᱢ ᱥᱟᱶᱦᱮᱫ ᱚᱰᱤᱴ',
  dashSocialAuditDesc: 'ᱟᱢᱟᱜ ᱟᱹᱛᱩ ᱥᱚᱨᱠᱟᱨᱤ ᱠᱷᱚᱨᱪ ᱨᱤᱫ-ᱧᱮᱞ — ᱡᱚᱛᱚ ᱛᱮᱫ ᱞᱟᱹᱜᱤᱫ ᱡᱷᱤᱡ ᱾',
  // admin
  adminAccess: 'Admin Access',
  adminOversightPortal: 'ᱢᱚᱱᱛᱨᱤ ᱢᱚᱱᱰᱚᱲᱤ ᱩᱱᱩᱥᱩᱢ ᱯᱚᱨᱴᱟᱞ',
  adminAccessPassword: 'Admin ᱯᱟᱥᱣᱚᱨᱰ',
  adminEnterPortal: 'Portal ᱨᱮ ᱥᱮᱱ ᱢᱮ',
  adminIncorrect: 'ᱵᱷᱩᱞ ᱯᱟᱥᱣᱚᱨᱰ ᱾ ᱫᱩᱦᱲᱟᱹ ᱨᱮᱫᱟᱭ ᱢᱮ ᱾',
  adminDemoPassword: 'Demo ᱯᱟᱥᱣᱚᱨᱰ:',
  adminRegistration: 'ᱚᱯᱷᱤᱥᱤᱭᱟᱞ ᱨᱮᱡᱤᱥᱴᱨᱮᱥᱚᱱ',
  adminRegisterDesc: 'ᱟᱢᱟᱜ ᱩᱱᱩᱥᱩᱢ ᱨᱚᱞ ᱨᱮᱡᱤᱥᱴᱚᱨ ᱢᱮ ᱜᱨᱤᱣᱮᱱᱥ Dashboard ᱡᱚᱲᱟᱣ ᱞᱟᱹᱜᱤᱫ ᱾',
  adminFullName: 'ᱯᱩᱨᱟᱹ ᱧᱩᱛᱩᱢ',
  adminEmail: 'ᱚᱯᱷᱤᱥᱤᱭᱟᱞ ᱤᱢᱮᱞ',
  adminPhone: 'ᱯᱷᱚᱱ',
  adminPosition: 'ᱯᱚᱫᱽ',
  adminState: 'ᱯᱚᱱᱚᱛ',
  adminDistrict: 'ᱦᱚᱱᱚᱛ',
  adminSelectState: 'ᱯᱚᱱᱚᱛ ᱵᱟᱪᱷᱟᱣ ᱢᱮ',
  adminSelectDistrict: 'ᱦᱚᱱᱚᱛ ᱵᱟᱪᱷᱟᱣ ᱢᱮ',
  adminRegisterContinue: 'ᱨᱮᱡᱤᱥᱴᱚᱨ ᱟᱨ ᱛᱟᱭᱚᱢ ᱛᱮ ᱮᱫᱟᱭ ᱢᱮ',
  adminOversightDashboard: 'ᱩᱱᱩᱥᱩᱢ Dashboard',
  adminGrievanceIntelligence: 'ᱜᱨᱤᱣᱮᱱᱥ ᱤᱱᱴᱮᱞᱤᱡᱮᱱᱥ',
  adminAllDistricts: 'ᱡᱚᱛᱚ ᱦᱚᱱᱚᱛ',
  adminExit: 'ᱵᱟᱦᱨᱮ ᱥᱮᱱ ᱢᱮ',
  adminStatusDistribution: 'ᱚᱵᱚᱥᱛᱟ ᱵᱟᱲᱟᱣ',
  adminByCategory: 'ᱠᱮᱴᱮᱜᱚᱨᱤ ᱞᱮᱠᱟᱛᱮ ᱜᱨᱤᱣᱮᱱᱥ',
  adminDistrictBreakdown: 'ᱦᱚᱱᱚᱛ ᱦᱤᱥᱟᱹᱵ',
  adminRecentGrievances: 'ᱱᱟᱶᱟ ᱜᱨᱤᱣᱮᱱᱥ',
  adminTotalGrievances: 'ᱡᱚᱛᱚ ᱜᱨᱤᱣᱮᱱᱥ',
  adminOpen: 'ᱡᱷᱤᱡ',
  adminNoGrievances: 'ᱱᱚᱣᱟ ᱧᱮᱞ ᱨᱮ ᱠᱚᱱᱚ ᱜᱨᱤᱣᱮᱱᱥ ᱵᱟᱹᱱᱩᱜ-ᱟ ᱾',
  adminAiSummary: 'AI ᱛᱚᱞ ᱥᱟᱨᱟᱥ',
  adminAiNone: 'ᱱᱚᱣᱟ ᱧᱮᱞ ᱞᱟᱹᱜᱤᱫ ᱠᱚᱱᱚ ᱜᱨᱤᱣᱮᱱᱥ ᱵᱟᱝ ᱢᱮᱱᱟᱜ-ᱟ ᱾',
  adminPosDm: 'District Magistrate',
  adminPosBdo: 'Block Development Officer',
  adminPosPanchayat: 'Panchayat Secretary',
  adminPosWelfare: 'ᱨᱟᱹᱥᱠᱟᱹ ᱚᱯᱷᱤᱥᱟᱨ',
  adminPosAudit: 'Social Audit Coordinator',
  adminPosState: 'ᱯᱚᱱᱚᱛ ᱱᱚᱰᱟᱞ ᱚᱯᱷᱤᱥᱟᱨ',
  adminPosManager: 'Program Manager',
  // common
  commonSubmit: 'ᱡᱚᱢᱟ ᱢᱮ',
  commonCancel: 'ᱵᱟᱹᱜᱤ ᱢᱮ',
  commonLoading: 'ᱞᱚᱰ ᱠᱟᱛᱮ ᱢᱮ…',
}
