export const _sa = {
  // nav
  navFeatures: 'सुविधाः',
  navOversight: 'पर्यवेक्षणम्',
  navSignIn: 'प्रवेशः',
  // hero
  heroBadge: 'कल्याणनीतेः कार्यान्वयनम्',
  heroTitle1: 'यथार्थशासनम्।',
  heroTitle2: 'पुनर्कल्पितम्।',
  heroSubtitle: 'एकं सुरक्षितं नागरिकप्रथमं मञ्चं यत्र वास्तविककालस्य दत्तांशः, विकेन्द्रीकृतं अस्मितापत्रं, प्रत्यक्षस्थानान्तरणं च यथायोग्यं जनं प्रति कल्याणलाभं प्रापयति।',
  heroCta: 'स्वं Dashboard प्रविशन्तु',
  // features
  featuresBadge: 'सामर्थ्यानि',
  featuresTitle: 'आधुनिककल्याणप्रणाल्यै आवश्यकं सर्वम्।',
  featuresSubtitle: 'एकः संयोजितः मञ्चः अस्मितां, लक्ष्यनिर्धारणं, भुगतानं, उत्तरदायित्वं चैकीकरोति।',
  tileDynamicRegistries: 'गतिशीलाः सामाजिक-आर्थिक पञ्जिकाः',
  tileDynamicRegistriesDesc: 'कर-, उपयोगिता-, नागरिक-अभिलेखेभ्यः निरन्तरं पात्रतायाः अद्यतनम् — यत् वास्तविकताम् एव प्रतिबिम्बते, न च स्थगितां जनगणनाम्।',
  tileBiometrics: 'विकेन्द्रीकृताः जैवमितीय अस्मिताः',
  tileBiometricsDesc: 'सुरक्षिताः विकेन्द्रीकृताः जैवमितीय अस्मितापत्राः ये अस्मिताप्रपञ्चं द्विगुणलाभं च द्वारे एव निवारयन्ति।',
  tileDbt: 'प्रत्यक्षलाभस्थानान्तरणम् (DBT)',
  tileDbtDesc: 'नगदं सहायताधनं च सत्यापितनागरिकखातेषु साक्षात् प्रेष्यते — मध्यस्थाः शून्याः।',
  tileConditional: 'सशर्तस्थानान्तरणम्',
  tileConditionalDesc: 'शिक्षा-स्वास्थ्य-मापदण्डैः संयुक्ताः भुगतानाः माप्यसामाजिकफलार्थम्।',
  tileAudits: 'सामुदायिकसामाजिकलेखापरीक्षाः',
  tileAuditsDesc: 'लोकसभाः यत्र नागरिकाः भूमिस्थसम्पत्तिभिः व्ययं परीक्षन्ते।',
  tileAi: 'स्वचालितानि अपवादप्रतिवेदनानि',
  tileAiDesc: 'AI बहुभिः लाभखातैः सम्बद्धस्य एकस्य दूरभाषसङ्ख्यायाः इव सन्दिग्धप्रतिरूपाणि चिह्नयति तत्क्षणतदन्वेषणार्थम्।',
  // oversight
  oversightBadge: 'मन्त्रालयपर्यवेक्षणम्',
  oversightTitle: 'मन्त्रालयकार्याचरणं पायाभूतसंरचना च',
  oversightSubtitle: 'मन्त्रालयानि कल्याणनीतिलेखापरीक्षां पर्यवेक्षन्ते — वैधानिकीनां कार्याचरणानां स्थापनया, पर्यवेक्षणबजेटविनियोगेन, सुरक्षितदत्तांशप्रणालीरक्षणेन, दण्डविधानेन च।',
  pillarAudit: 'अनिवार्यलेखापरीक्षणदिशानिर्देशाः',
  pillarAuditDesc: 'मानकसञ्चालनप्रक्रियाः वैधानिकी च ये सामाजिक-आर्थिकलेखापरीक्षणे अनिवार्ये कुरुतः।',
  pillarMetrics: 'स्पष्टाः निष्पादनमापदण्डाः',
  pillarMetricsDesc: 'माप्यमापदण्डाः — यथा बालविन्यासे बेरोजगार्यां वा विशिष्टन्यूनीकरणदराः।',
  pillarBodies: 'स्वतन्त्रसंस्थाः',
  pillarBodiesDesc: 'तृतीयपक्षलेखापरीक्षकाणां स्थानीयसामाजिकलेखापरीक्षणैककानां च राजनैतिकहस्तक्षेपात् वैधानिकसंरक्षणम्।',
  pillarDatabases: 'सुरक्षिताः मुख्यसञ्चयाः',
  pillarDatabasesDesc: 'केन्द्रीयलाभार्थिपञ्जिकाः शुद्धदत्तांशैः सह, अधिकृतलेखापरीक्षासंस्थाभ्यः एव प्राप्याः।',
  // footer
  footerTagline: 'नागरिकप्रथमनीत्यर्थं यथार्थशासनम्।',
  footerSub: 'गतिशीलाः पञ्जिकाः · विकेन्द्रीकृताः जैवमितीयाः · प्रत्यक्षलाभस्थानान्तरणम्',
  // login
  loginTitle: 'पुनरागमनं स्वागतम्',
  loginSubtitle: 'स्वं सुरक्षितं नागरिकं Dashboard प्राप्तुं प्रविशन्तु। नूतनाः नागरिकाः द्विमिनटाभ्यन्तरे प्रवेश्यन्ते।',
  loginContinueGoogle: 'Google द्वारा प्रविशन्तु',
  loginContinueDemo: 'डेमो खातेन सह प्रविशन्तु',
  loginDemoHint: 'डेमो खातम्',
  loginPresetLabel: 'एकं डेमो नागरिकं शीघ्रं पूरयन्तु:',
  loginOrUse: 'अथवा स्वविवरणैः प्रयुञ्जत',
  loginEmail: 'अधिकृतविद्युत्सञ्चारः',
  loginName: 'नाम',
  loginImage: 'चित्रसङ्केतः',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'स्व Aadhaar सत्यापयन्तु',
  verifySubtitle: 'एकवारिका अस्मितासत्यापना स्वकल्याणं Dashboard उन्मीलयति।',
  verifyAadhaarLabel: '१२-अङ्कीयः Aadhaar सङ्ख्या',
  verifyMobileLabel: 'OTP प्राप्तुं दूरभाषसङ्ख्या',
  verifyGenerateOtp: 'OTP जनयन्तु',
  verifySendingOtp: 'OTP प्रेष्यते…',
  verifyDemoNote: 'डेमो विधिः — OTP निवेदनं सादृश्यीकृतम्। कोऽपि वास्तविकः Aadhaar दत्तांशः न प्रेष्यते।',
  verifyOtpSentTo: 'OTP भवतः पञ्जीकृतदूरभाषसङ्ख्यायां प्रेषितम्',
  verifyDemoOtpLabel: 'डेमो OTP:',
  verifyDemoOtpNote: 'वास्तविकविन्यासः एतत् SMS द्वारा प्रेषयति — परीक्षणार्थम् अत्र दर्शितम्।',
  verifyOtpLabel: '६-अङ्कीयः OTP',
  verifyVerifyOtp: 'OTP सत्यापयन्तु',
  verifyVerifying: 'सत्याप्यते…',
  verifyChangeAadhaar: 'Aadhaar सङ्ख्यां परिवर्तयन्तु',
  verifyIdentityVerified: 'अस्मिता सत्यापिता',
  verifyRedirecting: 'स्वं Dashboard प्रति पुनर्निर्दिश्यते…',
  verifyInvalidAadhaar: 'कृपया वैधं १२-अङ्कीयं Aadhaar सङ्ख्यां प्रविशन्तु।',
  verifyInvalidOtp: 'कृपया भवतः दूरभाषे प्रेषितं ६-अङ्कीयं OTP प्रविशन्तु।',
  verifyInvalidMobile: 'कृपया वैधं १०-अङ्कीयं दूरभाषसङ्ख्यां प्रविशन्तु।',
  verifyFailedGenerate: 'OTP जनयितुं असफलम्।',
  verifyFailedVerify: 'सत्यापनं असफलम्। पुनः प्रयतन्ताम्।',
  verifySpeakHint: 'ध्वनिग्राहकं स्पृशत मचं स्व Aadhaar अथवा OTP उच्चारयन्तु',
  // dashboard
  dashWelcome: 'स्वागतम्',
  dashCitizen: 'नागरिकः',
  dashVerified: 'सत्यापनस्थितिः — सत्यापितम्',
  dashPending: 'सत्यापनस्थितिः — प्रतीक्षमाणम्',
  dashVerifyAadhaar: 'Aadhaar सत्यापयन्तु',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'निर्गमनम्',
  dashFoodSubsidy: 'अन्नसहायता (PDS)',
  dashDbt: 'प्रत्यक्षलाभस्थानान्तरणम् (DBT)',
  dashEducation: 'शिक्षादानम्',
  dashHealth: 'स्वास्थ्यसंरक्षणम्',
  dashNotEnrolled: 'न पञ्जीकृतम्',
  dashNextSocialAudit: 'अग्रिमः सामाजिकलेखापरीक्षणम्',
  dashSocialAuditDesc: 'भवतः ग्रामस्य सार्वजनिकव्ययपरीक्षणम् — सर्वेभ्यः निवासिभ्यः खुलम्।',
  // admin
  adminAccess: 'प्रशासकप्रवेशः',
  adminOversightPortal: 'मन्त्रालयपर्यवेक्षणद्वारम्',
  adminAccessPassword: 'प्रवेशकूटम्',
  adminEnterPortal: 'द्वारं प्रविशन्तु',
  adminIncorrect: 'अयुक्तं कूटम्। पुनः प्रयतन्ताम्।',
  adminDemoPassword: 'डेमो कूटम्:',
  adminRegistration: 'अधिकृतपञ्जीकरणम्',
  adminRegisterDesc: 'स्वं पर्यवेक्षणपदं पञ्जीकृत्य शिकायतं Dashboard प्राप्नुवन्तु।',
  adminFullName: 'पूर्णं नाम',
  adminEmail: 'अधिकृतविद्युत्सञ्चारः',
  adminPhone: 'दूरभाषः',
  adminPosition: 'पदम्',
  adminState: 'राज्यम्',
  adminDistrict: 'जिला',
  adminSelectState: 'राज्यं चिनुत',
  adminSelectDistrict: 'जिलां चिनुत',
  adminRegisterContinue: 'पञ्जीकृत्य प्रविशन्तु',
  adminOversightDashboard: 'पर्यवेक्षण Dashboard',
  adminGrievanceIntelligence: 'शिकायतबुद्धिमत्ता',
  adminAllDistricts: 'सर्वे जिलाः',
  adminExit: 'निर्गमनम्',
  adminStatusDistribution: 'स्थितिवितरणम्',
  adminByCategory: 'वर्गानुसारं शिकायताः',
  adminDistrictBreakdown: 'जिलाविभाजनम्',
  adminRecentGrievances: 'नवीनतमाः शिकायताः',
  adminTotalGrievances: 'कुलं शिकायताः',
  adminOpen: 'मुक्तम्',
  adminNoGrievances: 'अस्मिन् दृश्ये काचित् शिकायता नास्ति।',
  adminAiSummary: 'AI विषयसारांशः',
  adminAiNone: 'अस्मिन् दृश्ये काचिदपि शिकायता न लिखिता।',
  adminPosDm: 'जिलाधिकारी',
  adminPosBdo: 'ब्लॉक-विकासाधिकारी',
  adminPosPanchayat: 'पञ्चायतसचिवः',
  adminPosWelfare: 'कल्याणाधिकारी',
  adminPosAudit: 'सामाजिकलेखापरीक्षणसमन्वयकः',
  adminPosState: 'राज्यनोडलाधिकारी',
  adminPosManager: 'कार्यक्रमप्रबन्धकः',
  // common
  commonSubmit: 'समर्पयन्तु',
  commonCancel: 'निरस्तयन्तु',
  commonLoading: 'लोडयते…',
}
