export const _sd = {
  // nav
  navFeatures: 'خاصيتون',
  navOversight: 'نگراني',
  navSignIn: 'داخل ٿيو',
  // hero
  heroBadge: 'فلاحي پاليسي جو نفاذ',
  heroTitle1: 'عمدگي سان حڪمراني.',
  heroTitle2: 'ٻيهر تصور ڪيو.',
  heroSubtitle: 'هڪ محفوظ، شهري-اول پليٽفارم جتي حقيقي وقت جي ڊيٽا، غيرمرڪزي شناخت، ۽ سڌي منتقليون فلاحي فائدن کي عين صحيح ماڻهن تائين پهچائين.',
  heroCta: 'پنهنجو ڊيش بورڊ کوليو',
  // features
  featuresBadge: 'صلاحيتون',
  featuresTitle: 'جديد فلاحي نظام جي ضرورت سڀ ڪجهه.',
  featuresSubtitle: 'هڪ ڄانڻايل پليٽفارم شناخت، نشانديھي، ادائگيون ۽ جوابديهي کي متحد ڪري ٿو.',
  tileDynamicRegistries: 'متحرڪ سماجي-معاشي رجسٽريون',
  tileDynamicRegistriesDesc: 'ٽيڪس، سهولتن ۽ شهري رڪارڊن مان مسلسل اهلیت اپڊيٽون — اهڙي نشانديھي جيڪا هميشه حقيقت کي ظاهر ڪري، ڪڏهن به پراڻي مردم شماري نه.',
  tileBiometrics: 'غيرمرڪزي بائيو ميٽرڪس',
  tileBiometricsDesc: 'محفوظ، غيرمرڪزي بائيو ميٽرڪ شناخت جيڪي دروازي تي شناختي ڌوڪا ۽ ٻٽي وصولي روڪين.',
  tileDbt: 'سڌي فائده منتقليون',
  tileDbtDesc: 'نقد ۽ سبسڊيون سڌيون تصديق ٿيل شهري اڪائونٽن ۾ — ڪوبه وچڙو نه.',
  tileConditional: 'مشروط منتقليون',
  tileConditionalDesc: 'تعليم ۽ صحت جي سنگ ميل تي منحصر ادائگيون قابل پيمائش سماجي نتيجن لاء.',
  tileAudits: 'ڪميونٽي سماجي آڊٽ',
  tileAuditsDesc: 'عوامي مجلسون جتي شهرين خرچ کي زميني اثاثن خلاف کوڙ پڪڙ ڪندا آهن.',
  tileAi: 'خودڪار استثناء رپورٽون',
  tileAiDesc: 'AI شڪي نمونن کي نشان ڪري ٿو — جهڙوڪ هڪ ئي فون نمبر جيڪو ڪيترن فائده اڪائونٽن سان جڙيل آهي — فوري تحقيق لاء.',
  // oversight
  oversightBadge: 'وزارت نگراني',
  oversightTitle: 'وزارت جو ڊانچو ۽ بنياد',
  oversightSubtitle: 'وزارتون فلاحي پاليسي آڊٽن جي نگراني قانوني ڊانچا قائم ڪرڻ، نگراني بجٽ مختص ڪرڻ، محفوظ ڊيٽا سسٽم برقرار رکڻ، ۽ سزائون نافذ ڪرڻ ذريعي ڪن ٿيون.',
  pillarAudit: 'لازمي آڊٽ رهنما اصول',
  pillarAuditDesc: 'معياري آپريشنل طريقا ۽ قانوني ڊانچا جيڪي سماجي ۽ مالي آڊٽ لازمي بنائين.',
  pillarMetrics: 'واضح ڪارڪردگي ميٽرڪس',
  pillarMetricsDesc: 'قابل پيمائش ميچ — جهڙوڪ قد جي واڌ ۾ خاص ڪمي يا بيروزگاري.',
  pillarBodies: 'آزاد ادارا',
  pillarBodiesDesc: 'ٽيون پارٽي آڊٽرن ۽ مقامي سماجي آڊٽ يونٽن لاء قانوني تحفظ سياسي مداخلت خلاف.',
  pillarDatabases: 'محفوظ ماسٽر ڊيٽابيس',
  pillarDatabasesDesc: 'مرڪزي فائدہ يافتہ رجسٽريون صاف ڊيٽا سان، صرف مجاز آڊٽ ايجنسين کي دستياب.',
  // footer
  footerTagline: 'ماڻهن-اول پاليسي لاء عمدگي سان حڪمراني.',
  footerSub: 'متحرڪ رجسٽريون · غيرمرڪزي بائيو ميٽرڪس · سڌي فائده منتقليون',
  // login
  loginTitle: 'ڀلي آيا',
  loginSubtitle: 'پنهنجو محفوظ شهري ڊيش بورڊ کولڻ لاء داخل ٿيو. نئين شهرين کي ٻن منٽن کان گهٽ ۾ آن بورڊ ڪيو وڃي ٿو.',
  loginContinueGoogle: 'Google سان جاري رکيو',
  loginContinueDemo: 'ڊيمو اڪائونٽ سان جاري رکيو',
  loginDemoHint: 'ڊيمو اڪائونٽ',
  loginPresetLabel: 'هڪ ڊيمو شهري جلدي پر ڪريو:',
  loginOrUse: 'يا پنهنجي تفصيل استعمال ڪريو',
  loginEmail: 'اي ميل',
  loginName: 'نالو',
  loginImage: 'تصوير URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'پنهنجو Aadhaar تصديق ڪريو',
  verifySubtitle: 'هڪ ڀيري شناخت جي تصديق توهانجو فلاحي ڊيش بورڊ کولي ٿي.',
  verifyAadhaarLabel: '12 انگن وارو Aadhaar نمبر',
  verifyMobileLabel: 'OTP وصول ڪرڻ لاء موبائيل نمبر',
  verifyGenerateOtp: 'OTPٺيو',
  verifySendingOtp: 'OTP موڪلي رهيا آهيون…',
  verifyDemoNote: 'ڊيمو موڊ — OTP جي درخواست محاكاتي آهي. ڪابه حقيقي Aadhaar ڊيٽا نه موڪلي وڃي ٿو.',
  verifyOtpSentTo: 'OTP توهانجي رجسٽرڊ موبائيل نمبر تي موڪليو ويو',
  verifyDemoOtpLabel: 'ڊيمو OTP:',
  verifyDemoOtpNote: 'حقيقي تعيناتي هن کي SMS ذريعي موڪلي ٿي — هتي جانچ لاء ڏيکاريو ويو آهي.',
  verifyOtpLabel: '6 انگن وارو OTP',
  verifyVerifyOtp: 'OTP تصديق ڪريو',
  verifyVerifying: 'تصديق ڪري رهيا آهيون…',
  verifyChangeAadhaar: 'Aadhaar نمبر تبديل ڪريو',
  verifyIdentityVerified: 'شناخت تصديق ٿي',
  verifyRedirecting: 'پنهنجي ڊيش بورڊ ڏانهن موڙيندا…',
  verifyInvalidAadhaar: 'مهرباني ڪري هڪ درست 12 انگن وارو Aadhaar نمبر داخل ڪريو.',
  verifyInvalidOtp: 'مهرباني ڪري پنهنجي فون تي موڪليل 6 انگن وارو OTP داخل ڪريو.',
  verifyInvalidMobile: 'مهرباني ڪري هڪ درست 10 انگن وارو موبائيل نمبر داخل ڪريو.',
  verifyFailedGenerate: 'OTPٺڻ ۾ ناڪامي.',
  verifyFailedVerify: 'تصديق ناڪام ٿي. مهرباني ڪري ٻيهر ڪوشش ڪريو.',
  verifySpeakHint: 'مائڪ کي هٿ هڻو ۽ پنهنجو Aadhaar يا OTP چيو',
  // dashboard
  dashWelcome: 'ڀلي آيا',
  dashCitizen: 'شهري',
  dashVerified: 'تصديق جي حالت: تصديق ٿيل',
  dashPending: 'تصديق جي حالت: زير التواء',
  dashVerifyAadhaar: 'Aadhaar تصديق ڪريو',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'خارج ٿيو',
  dashFoodSubsidy: 'کاڌي جي سبسڊي (PDS)',
  dashDbt: 'سڌي فائده منتقلي',
  dashEducation: 'تعليمي گرانٽ',
  dashHealth: 'صحت جو احاطو',
  dashNotEnrolled: 'داخل نه ٿيل',
  dashNextSocialAudit: 'اڳين سماجي آڊٽ',
  dashSocialAuditDesc: 'توهانجي ڳوٺ جي عوامي خرچ جو جائزو — سڀني رهاڪن لاء کليل.',
  // admin
  adminAccess: 'ايڊمن رسائي',
  adminOversightPortal: 'وزارت نگراني پورٽل',
  adminAccessPassword: 'رسائي جو پاسورڊ',
  adminEnterPortal: 'پورٽل ۾ داخل ٿيو',
  adminIncorrect: 'غلط پاسورڊ. ٻيهر ڪوشش ڪريو.',
  adminDemoPassword: 'ڊيمو پاسورڊ:',
  adminRegistration: 'سرڪاري رجسٽريشن',
  adminRegisterDesc: 'شڪايت ڊيش بورڊ تائين رسائي لاء پنهنجو نگراني وارو ڪردار رجسٽر ڪريو.',
  adminFullName: 'پورو نالو',
  adminEmail: 'سرڪاري اي ميل',
  adminPhone: 'فون',
  adminPosition: 'عہدو',
  adminState: 'رياست',
  adminDistrict: 'ضلعو',
  adminSelectState: 'رياست چونڊيو',
  adminSelectDistrict: 'ضلعو چونڊيو',
  adminRegisterContinue: 'رجسٽر ڪريو ۽ جاري رکيو',
  adminOversightDashboard: 'نگراني ڊيش بورڊ',
  adminGrievanceIntelligence: 'شڪايت انٽيليجنس',
  adminAllDistricts: 'سڀ ضلعا',
  adminExit: 'خارج',
  adminStatusDistribution: 'حالت جي ورهاست',
  adminByCategory: 'زمرو جي حساب سان شڪايتون',
  adminDistrictBreakdown: 'ضلعي جي تفصيل',
  adminRecentGrievances: 'حالي شڪايتون',
  adminTotalGrievances: 'ڪل شڪايتون',
  adminOpen: 'کليل',
  adminNoGrievances: 'هن نظارے ۾ ڪوبه شڪايت نه آهي.',
  adminAiSummary: 'AI موضوع خلاصو',
  adminAiNone: 'هن نظارے لاء ڪوبه شڪايت رڪارڊ نه ٿي.',
  adminPosDm: 'ضلعي مئجسٽريٽ',
  adminPosBdo: 'بلاڪ اڀياس آفيسر',
  adminPosPanchayat: 'پنچائت سيڪريٽري',
  adminPosWelfare: 'فلاحي آفيسر',
  adminPosAudit: 'سماجي آڊٽ ڪوآرڊينيٽر',
  adminPosState: 'رياست نوڊل آفيسر',
  adminPosManager: 'پروگرام مئنيجر',
  // common
  commonSubmit: 'جمع ڪرايو',
  commonCancel: 'رد ڪريو',
  commonLoading: 'لوڊ ٿي رهيو آهي…',
}
