export const _ta = {
  // nav
  navFeatures: 'அம்சங்கள்',
  navOversight: 'மேற்பார்வை',
  navSignIn: 'உள்நுழைக',
  // hero
  heroBadge: 'நலத் திட்டச் செயலாக்கம்',
  heroTitle1: 'துல்லிய ஆட்சி.',
  heroTitle2: 'மறுவடிவம்.',
  heroSubtitle: 'பாதுகாப்பான, குடிமக்களை முதன்மைப்படுத்தும் தளம். இதில் நிகழ்நேரத் தரவு, பரவலாக்கப்பட்ட அடையாளம் மற்றும் நேரடிப் பரிமாற்றங்கள் நலன்புரி பயன்களைச் சரியான நபர்களுக்கு வழங்குகின்றன.',
  heroCta: 'உங்கள் Dashboard-ஐ அணுகவும்',
  // features
  featuresBadge: 'திறன்கள்',
  featuresTitle: 'நவீன நல அமைப்புக்குத் தேவையான அனைத்தும்.',
  featuresSubtitle: 'ஒரே இணைக்கப்பட்ட தளம் அடையாளம், இலக்கு நிர்ணயம், கட்டணம் மற்றும் பொறுப்புக்கூறலை ஒருங்கிணைக்கிறது.',
  tileDynamicRegistries: 'மாறும் சமூகப் பொருளாதாரப் பதிவேடுகள்',
  tileDynamicRegistriesDesc: 'வரி, பயன்பாட்டுக் கட்டணம் மற்றும் குடிமைப் பதிவுகளிலிருந்து தொடர்ச்சியான தகுதிப் புதுப்பிப்புகள் — தற்போதைய நிலையைப் பிரதிபலிக்கும் இலக்கு நிர்ணயம், பழைய மக்கள்தொகைக் கணக்கெடுப்பு அல்ல.',
  tileBiometrics: 'பரவலாக்கப்பட்ட உயிரளவைகள்',
  tileBiometricsDesc: 'அடையாள மோசடியையும் இரட்டைப் பயன்பாட்டையும் வாயிலிலேயே தடுக்கும் பாதுகாப்பான, பரவலாக்கப்பட்ட உயிரளவை அடையாளங்கள்.',
  tileDbt: 'நேரடி நன்மைப் பரிமாற்றங்கள்',
  tileDbtDesc: 'பணமும் மானியங்களும் சரிபார்க்கப்பட்ட குடிமக்கள் கணக்குகளுக்கு நேரடியாக வழங்கப்படுகின்றன — இடைத்தரகர்கள் இல்லை.',
  tileConditional: 'நிபந்தனைக்குட்பட்ட பரிமாற்றங்கள்',
  tileConditionalDesc: 'அளவிடக்கூடிய சமூக விளைவுகளுக்காகக் கல்வி மற்றும் சுகாதார இலக்குகளுடன் இணைக்கப்பட்ட கொடுப்பனவுகள்.',
  tileAudits: 'சமூகத் தணிக்கைகள்',
  tileAuditsDesc: 'குடிமக்கள் நிலப்புலச் சொத்துகளுக்கு எதிராகச் செலவினங்களைக் குறுக்கு விசாரணை செய்யும் பொது சபைகள்.',
  tileAi: 'தானியக்க விதிவிலக்குப் புகாரளிப்புகள்',
  tileAiDesc: 'பலன் கணக்குகள் பலவற்றுடன் இணைக்கப்பட்ட ஒரே தொலைபேசி எண் போன்ற சந்தேகத்திற்கிடமான வடிவங்களை AI குறிக்கிறது — உடனடி விசாரணைக்காக.',
  // oversight
  oversightBadge: 'அமைச்சக மேற்பார்வை',
  oversightTitle: 'அமைச்சகக் கட்டமைப்பும் உள்கட்டமைப்பும்',
  oversightSubtitle: 'சட்டக் கட்டமைப்புகளை உருவாக்குதல், மேற்பார்வை நிதியை ஒதுக்குதல், பாதுகாப்பான தரவு முறைகளைப் பராமரித்தல் மற்றும் தண்டனைகளைச் செயல்படுத்துதல் ஆகியவற்றின் மூலம் நலக் கொள்கைத் தணிக்கைகளை அமைச்சகங்கள் மேற்பார்வை செய்கின்றன.',
  pillarAudit: 'கட்டாயத் தணிக்கை வழிகாட்டுதல்கள்',
  pillarAuditDesc: 'சமூக மற்றும் நிதித் தணிக்கைகளைக் கட்டாயமாக்கும் செயல்நெறிகளும் சட்டக் கட்டமைப்புகளும்.',
  pillarMetrics: 'தெளிவான செயல்திறன் அளவுகோல்கள்',
  pillarMetricsDesc: 'அளவிடக்கூடிய தரநிலைகள் — எடுத்துக்காட்டாக, குன்றிய வளர்ச்சி அல்லது வேலையின்மையில் குறிப்பிட்டக் குறைப்பு விகிதங்கள்.',
  pillarBodies: 'சுயேச்சை அமைப்புகள்',
  pillarBodiesDesc: 'மூன்றாம் தரப்புத் தணிக்கையாளர்கள் மற்றும் உள்ளூர் சமூகத் தணிக்கைக் குழுக்களுக்கு அரசியல் தலையீட்டிலிருந்து சட்டப் பாதுகாப்புகள்.',
  pillarDatabases: 'பாதுகாப்பான முதன்மைத் தரவுத்தளங்கள்',
  pillarDatabasesDesc: 'சுத்தமான தரவுடன் கூடிய மையப் பயனாளர் பதிவேடுகள், அங்கீகரிக்கப்பட்ட தணிக்கை முகமைகளுக்கு மட்டுமே அணுகக்கூடியவை.',
  // footer
  footerTagline: 'மக்களை முதன்மைப்படுத்தும் கொள்கைக்கான துல்லிய ஆட்சி.',
  footerSub: 'மாறும் பதிவேடுகள் · பரவலாக்கப்பட்ட உயிரளவைகள் · நேரடி நன்மைப் பரிமாற்றங்கள்',
  // login
  loginTitle: 'மீண்டும் வரவேற்கிறோம்',
  loginSubtitle: 'உங்கள் பாதுகாப்பான குடிமக்கள் Dashboard-ஐ அணுக உள்நுழையவும். புதிய குடிமக்கள் இரண்டு நிமிடங்களுக்குள் இணைக்கப்படுகிறார்கள்.',
  loginContinueGoogle: 'Google மூலம் தொடரவும்',
  loginContinueDemo: 'டெமோ கணக்குடன் தொடரவும்',
  loginDemoHint: 'டெமோ கணக்கு',
  loginPresetLabel: 'ஒரு டெமோ குடிமகனை விரைவாக நிரப்பவும்:',
  loginOrUse: 'அல்லது உங்கள் விவரங்களைப் பயன்படுத்தவும்',
  loginEmail: 'மின்னஞ்சல்',
  loginName: 'பெயர்',
  loginImage: 'பட URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'உங்கள் Aadhaar-ஐ சரிபார்க்கவும்',
  verifySubtitle: 'ஒருமுறை அடையாளச் சரிபார்ப்பு உங்கள் நல Dashboard-ஐத் திறக்கிறது.',
  verifyAadhaarLabel: '12-இலக்க Aadhaar எண்',
  verifyMobileLabel: 'OTP பெற மொபைல் எண்',
  verifyGenerateOtp: 'OTP உருவாக்கவும்',
  verifySendingOtp: 'OTP அனுப்பப்படுகிறது…',
  verifyDemoNote: 'டெமோ பயன்முறை — OTP கோரிக்கை உருவகப்படுத்தப்படுகிறது. உண்மையான Aadhaar தரவு எதுவும் அனுப்பப்படவில்லை.',
  verifyOtpSentTo: 'உங்கள் பதிவுசெய்யப்பட்ட மொபைல் எண்ணுக்கு OTP அனுப்பப்பட்டது:',
  verifyDemoOtpLabel: 'டெமோ OTP:',
  verifyDemoOtpNote: 'உண்மையான வரவேற்பு இதை SMS வழியாக அனுப்பும் — சோதனைக்காக இங்கு காட்டப்படுகிறது.',
  verifyOtpLabel: '6-இலக்க OTP',
  verifyVerifyOtp: 'OTP சரிபார்க்கவும்',
  verifyVerifying: 'சரிபார்க்கப்படுகிறது…',
  verifyChangeAadhaar: 'Aadhaar எண்ணை மாற்றவும்',
  verifyIdentityVerified: 'அடையாளம் சரிபார்க்கப்பட்டது',
  verifyRedirecting: 'உங்கள் Dashboard-க்கு திருப்பிவிடப்படுகிறது…',
  verifyInvalidAadhaar: 'சரியான 12-இலக்க Aadhaar எண்ணை உள்ளிடவும்.',
  verifyInvalidOtp: 'உங்கள் தொலைபேசிக்கு அனுப்பப்பட்ட 6-இலக்க OTP-ஐ உள்ளிடவும்.',
  verifyInvalidMobile: 'சரியான 10-இலக்க மொபைல் எண்ணை உள்ளிடவும்.',
  verifyFailedGenerate: 'OTP உருவாக்கம் தோல்வியடைந்தது.',
  verifyFailedVerify: 'சரிபார்ப்பு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.',
  verifySpeakHint: 'மைக்கைத் தட்டி உங்கள் Aadhaar அல்லது OTP-ஐச் சொல்லுங்கள்',
  // dashboard
  dashWelcome: 'வரவேற்கிறோம்',
  dashCitizen: 'குடிமகன்',
  dashVerified: 'சரிபார்ப்பு நிலை: சரிபார்க்கப்பட்டது',
  dashPending: 'சரிபார்ப்பு நிலை: நிலுவையில்',
  dashVerifyAadhaar: 'Aadhaar சரிபார்க்கவும்',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'வெளியேறு',
  dashFoodSubsidy: 'உணவு மானியம் (PDS)',
  dashDbt: 'நேரடி நன்மைப் பரிமாற்றம்',
  dashEducation: 'கல்வி மானியம்',
  dashHealth: 'சுகாதாரப் பாதுகாப்பு',
  dashNotEnrolled: 'சேர்க்கப்படவில்லை',
  dashNextSocialAudit: 'அடுத்த சமூகத் தணிக்கை',
  dashSocialAuditDesc: 'உங்கள் கிராமத்தின் பொது செலவின மீளாய்வு — அனைத்துக் குடியிருப்பாளர்களுக்கும் திறந்தது.',
  // admin
  adminAccess: 'நிர்வாக அணுகல்',
  adminOversightPortal: 'அமைச்சக மேற்பார்வைத் தளம்',
  adminAccessPassword: 'அணுகல் கடவுச்சொல்',
  adminEnterPortal: 'தளத்திற்குச் செல்லவும்',
  adminIncorrect: 'தவறான கடவுச்சொல். மீண்டும் முயற்சிக்கவும்.',
  adminDemoPassword: 'டெமோ கடவுச்சொல்:',
  adminRegistration: 'அதிகாரப்பூர்வப் பதிவு',
  adminRegisterDesc: 'புகார் டாஷ்போர்டை அணுக உங்கள் மேற்பார்வைப் பங்கைப் பதிவுசெய்யவும்.',
  adminFullName: 'முழுப்பெயர்',
  adminEmail: 'அதிகாரப்பூர்வ மின்னஞ்சல்',
  adminPhone: 'தொலைபேசி',
  adminPosition: 'பதவி',
  adminState: 'மாநிலம்',
  adminDistrict: 'மாவட்டம்',
  adminSelectState: 'மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
  adminSelectDistrict: 'மாவட்டத்தைத் தேர்ந்தெடுக்கவும்',
  adminRegisterContinue: 'பதிவுசெய்து தொடரவும்',
  adminOversightDashboard: 'மேற்பார்வை Dashboard',
  adminGrievanceIntelligence: 'புகார் நுண்ணறிவு',
  adminAllDistricts: 'அனைத்து மாவட்டங்களும்',
  adminExit: 'வெளியேறு',
  adminStatusDistribution: 'நிலைப் பரவல்',
  adminByCategory: 'பிரிவுவாரியான புகார்கள்',
  adminDistrictBreakdown: 'மாவட்டப் பிரிவு',
  adminRecentGrievances: 'சமீபத்திய புகார்கள்',
  adminTotalGrievances: 'மொத்த புகார்கள்',
  adminOpen: 'திறந்த',
  adminNoGrievances: 'இந்தக் காட்சியில் புகார்கள் இல்லை.',
  adminAiSummary: 'AI தலைப்புச் சுருக்கம்',
  adminAiNone: 'இந்தக் காட்சிக்குப் புகார்கள் எதுவும் பதிவு செய்யப்படவில்லை.',
  adminPosDm: 'மாவட்ட ஆட்சியர்',
  adminPosBdo: 'வட்டார வளர்ச்சி அலுவலர்',
  adminPosPanchayat: 'பஞ்சாயத்து செயலர்',
  adminPosWelfare: 'நல அலுவலர்',
  adminPosAudit: 'சமூகத் தணிக்கை ஒருங்கிணைப்பாளர்',
  adminPosState: 'மாநில நோடல் அலுவலர்',
  adminPosManager: 'திட்ட மேலாளர்',
  // common
  commonSubmit: 'சமர்ப்பிக்கவும்',
  commonCancel: 'ரத்துசெய்',
  commonLoading: 'ஏற்றப்படுகிறது…',
}
