export const _te = {
  // nav
  navFeatures: 'ఫీచర్లు',
  navOversight: 'పర్యవేక్షణ',
  navSignIn: 'సైన్ ఇన్',
  // hero
  heroBadge: 'సంక్షేమ విధాన అమలు',
  heroTitle1: 'ఖచ్చితమైన పాలన.',
  heroTitle2: 'పునర్విన్యాసం.',
  heroSubtitle: 'రియల్ టైమ్ డేటా, వికేంద్రీకృత గుర్తింపు మరియు నేరుగా బదిలీల ద్వారా సరైన వ్యక్తులకు సంక్షేమ ప్రయోజనాలను అందించే సురక్షితమైన, పౌరుల-మొదటి వేదిక.',
  heroCta: 'మీ Dashboardని యాక్సెస్ చేయండి',
  // features
  featuresBadge: 'సామర్థ్యాలు',
  featuresTitle: 'ఆధునిక సంక్షేమ వ్యవస్థకు కావలసినవన్నీ.',
  featuresSubtitle: 'గుర్తింపు, లక్ష్యీకరణ, చెల్లింపులు మరియు బాధ్యతను ఏకీకృతం చేసే ఒకే అనుసంధానిత వేదిక.',
  tileDynamicRegistries: 'డైనమిక్ సామాజిక-ఆర్థిక రిజిస్ట్రీలు',
  tileDynamicRegistriesDesc: 'పన్ను, యుటిలిటీ మరియు పౌర రికార్డుల నుండి నిరంతర అర్హత నవీకరణలు — ఎప్పుడూ వాస్తవాన్ని ప్రతిబింబించే, ఎన్నడూ పాత గణన కాని లక్ష్యీకరణ.',
  tileBiometrics: 'వికేంద్రీకృత బయోమెట్రిక్స్',
  tileBiometricsDesc: 'గుర్తింపు మోసం మరియు ద్వంద్వ ప్రయోజనాలను తలుపు వద్ద ఆపే సురక్షితమైన, వికేంద్రీకృత బయోమెట్రిక్ IDలు.',
  tileDbt: 'Direct Benefit Transfers',
  tileDbtDesc: 'నగదు మరియు రాయితీలు ధృవీకరించబడిన పౌర ఖాతాలలోకి నేరుగా — మధ్యవర్తులు సున్నా.',
  tileConditional: 'నిబంధనాధీన బదిలీలు',
  tileConditionalDesc: 'కొలమానం చేయగల సామాజిక ఫలితాల కోసం విద్యా మరియు ఆరోగ్య మైలురాళ్లకు అనుసంధానించబడిన చెల్లింపులు.',
  tileAudits: 'కమ్యూనిటీ సామాజిక ఆడిట్లు',
  tileAuditsDesc: 'పౌరులు నేలపై ఆస్తులకు వ్యతిరేకంగా ఖర్చులను పరీక్షించే ప్రజా సమావేశాలు.',
  tileAi: 'స్వయంచాలక మినహాయింపు నివేదికలు',
  tileAiDesc: 'AI అనుమానాస్పద నమూనాలను — బహుళ ప్రయోజన ఖాతాలకు లింక్ చేయబడిన ఒకే ఫోన్ నంబర్ వంటివి — తక్షణ దర్యాప్తు కోసం గుర్తిస్తుంది.',
  // oversight
  oversightBadge: 'మంత్రిత్వ శాఖ పర్యవేక్షణ',
  oversightTitle: 'మంత్రిత్వ శాఖ ఫ్రేమ్‌వర్క్ మరియు మౌలిక సదుపాయాలు',
  oversightSubtitle: 'చట్టపరమైన ఫ్రేమ్‌వర్క్‌లను ఏర్పాటు చేయడం, పర్యవేక్షణ బడ్జెట్‌లను కేటాయించడం, సురక్షిత డేటా వ్యవస్థలను నిర్వహించడం మరియు జరిమానాలను అమలు చేయడం ద్వారా మంత్రిత్వ శాఖలు సంక్షేమ విధాన ఆడిట్లను పర్యవేక్షిస్తాయి.',
  pillarAudit: 'తప్పనిసరి ఆడిట్ మార్గదర్శకాలు',
  pillarAuditDesc: 'సామాజిక మరియు ఆర్థిక ఆడిట్లను తప్పనిసరి చేసే ప్రామాణిక కార్యాచరణ విధానాలు మరియు చట్టపరమైన ఫ్రేమ్‌వర్క్‌లు.',
  pillarMetrics: 'స్పష్టమైన పనితీరు మెట్రిక్‌లు',
  pillarMetricsDesc: 'కొలమానం చేయగల బెంచ్‌మార్క్‌లు — మరుగుజ్జుతనం లేదా నిరుద్యోగంలో నిర్దిష్ట తగ్గుదల రేట్లు వంటివి.',
  pillarBodies: 'స్వతంత్ర సంస్థలు',
  pillarBodiesDesc: 'రాజకీయ జోక్యం నుండి థర్డ్-పార్టీ ఆడిటర్లు మరియు స్థానిక సామాజిక ఆడిట్ యూనిట్ల కోసం చట్టపరమైన రక్షణలు.',
  pillarDatabases: 'సురక్షిత మాస్టర్ డేటాబేస్‌లు',
  pillarDatabasesDesc: 'శుభ్రమైన డేటాతో కేంద్ర లబ్ధిదారు రిజిస్ట్రీలు, అధికారం పొందిన ఆడిట్ ఏజెన్సీలకు మాత్రమే అందుబాటులో ఉంటాయి.',
  // footer
  footerTagline: 'ప్రజల-మొదటి విధానం కోసం ఖచ్చితమైన పాలన.',
  footerSub: 'డైనమిక్ రిజిస్ట్రీలు · వికేంద్రీకృత బయోమెట్రిక్స్ · నేరుగా ప్రయోజన బదిలీలు',
  // login
  loginTitle: 'తిరిగి స్వాగతం',
  loginSubtitle: 'మీ సురక్షిత పౌర Dashboardని యాక్సెస్ చేయడానికి సైన్ ఇన్ అవ్వండి. కొత్త పౌరులు రెండు నిమిషాలలోపు ఆన్‌బోర్డ్ చేయబడతారు.',
  loginContinueGoogle: 'Googleతో కొనసాగించండి',
  loginContinueDemo: 'డెమో ఖాతాతో కొనసాగించండి',
  loginDemoHint: 'డెమో ఖాతా',
  loginPresetLabel: 'డెమో పౌరుడిని త్వరగా నింపండి:',
  loginOrUse: 'లేదా మీ వివరాలను ఉపయోగించండి',
  loginEmail: 'ఇమెయిల్',
  loginName: 'పేరు',
  loginImage: 'చిత్ర URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'మీ Aadhaarని ధృవీకరించండి',
  verifySubtitle: 'ఒక్కసారి గుర్తింపు ధృవీకరణ మీ సంక్షేమ Dashboardని అన్‌లాక్ చేస్తుంది.',
  verifyAadhaarLabel: '12-అంకెల Aadhaar నంబర్',
  verifyMobileLabel: 'OTP స్వీకరించడానికి మొబైల్ నంబర్',
  verifyGenerateOtp: 'OTP జెనరేట్ చేయండి',
  verifySendingOtp: 'OTP పంపుతోంది…',
  verifyDemoNote: 'డెమో మోడ్ — OTP అభ్యర్థన అనుకరించబడుతుంది. నిజమైన Aadhaar డేటా ఏదీ ప్రసారం చేయబడదు.',
  verifyOtpSentTo: 'మీ నమోదిత మొబైల్ నంబర్‌కు OTP పంపబడింది',
  verifyDemoOtpLabel: 'డెమో OTP:',
  verifyDemoOtpNote: 'నిజమైన డిప్లాయ్‌మెంట్ దీనిని SMS ద్వారా పంపుతుంది — పరీక్ష కోసం ఇక్కడ చూపబడింది.',
  verifyOtpLabel: '6-అంకెల OTP',
  verifyVerifyOtp: 'OTP ధృవీకరించండి',
  verifyVerifying: 'ధృవీకరిస్తోంది…',
  verifyChangeAadhaar: 'Aadhaar నంబర్‌ను మార్చండి',
  verifyIdentityVerified: 'గుర్తింపు ధృవీకరించబడింది',
  verifyRedirecting: 'మీ Dashboardకు రీడైరెక్ట్ చేస్తోంది…',
  verifyInvalidAadhaar: 'దయచేసి చెల్లుబాటు అయ్యే 12-అంకెల Aadhaar నంబర్‌ను నమోదు చేయండి.',
  verifyInvalidOtp: 'దయచేసి మీ ఫోన్‌కు పంపబడిన 6-అంకెల OTPని నమోదు చేయండి.',
  verifyInvalidMobile: 'దయచేసి చెల్లుబాటు అయ్యే 10-అంకెల మొబైల్ నంబర్‌ను నమోదు చేయండి.',
  verifyFailedGenerate: 'OTP జెనరేట్ చేయడం విఫలమైంది.',
  verifyFailedVerify: 'ధృవీకరణ విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.',
  verifySpeakHint: 'మైక్‌పై నొక్కి మీ Aadhaar లేదా OTPని చెప్పండి',
  // dashboard
  dashWelcome: 'స్వాగతం',
  dashCitizen: 'పౌరుడు',
  dashVerified: 'ధృవీకరణ స్థితి: ధృవీకరించబడింది',
  dashPending: 'ధృవీకరణ స్థితి: పెండింగ్‌లో',
  dashVerifyAadhaar: 'Aadhaar ధృవీకరించండి',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'సైన్ అవుట్',
  dashFoodSubsidy: 'ఆహార రాయితీ (PDS)',
  dashDbt: 'Direct Benefit Transfer',
  dashEducation: 'విద్యా గ్రాంట్',
  dashHealth: 'ఆరోగ్య కవరేజ్',
  dashNotEnrolled: 'నమోదు కాలేదు',
  dashNextSocialAudit: 'తదుపరి సామాజిక ఆడిట్',
  dashSocialAuditDesc: 'మీ గ్రామ ప్రజా వ్యయ సమీక్ష — అన్ని నివాసితులకు తెరిచి ఉంటుంది.',
  // admin
  adminAccess: 'అడ్మిన్ యాక్సెస్',
  adminOversightPortal: 'మంత్రిత్వ శాఖ పర్యవేక్షణ పోర్టల్',
  adminAccessPassword: 'యాక్సెస్ పాస్‌వర్డ్',
  adminEnterPortal: 'పోర్టల్‌లోకి ప్రవేశించండి',
  adminIncorrect: 'తప్పు పాస్‌వర్డ్. మళ్లీ ప్రయత్నించండి.',
  adminDemoPassword: 'డెమో పాస్‌వర్డ్:',
  adminRegistration: 'అధికారిక నమోదు',
  adminRegisterDesc: 'ఫిర్యాదు Dashboardని యాక్సెస్ చేయడానికి మీ పర్యవేక్షణ పాత్రను నమోదు చేసుకోండి.',
  adminFullName: 'పూర్తి పేరు',
  adminEmail: 'అధికారిక ఇమెయిల్',
  adminPhone: 'ఫోన్',
  adminPosition: 'పదవి',
  adminState: 'రాష్ట్రం',
  adminDistrict: 'జిల్లా',
  adminSelectState: 'రాష్ట్రాన్ని ఎంచుకోండి',
  adminSelectDistrict: 'జిల్లాను ఎంచుకోండి',
  adminRegisterContinue: 'నమోదు చేసి కొనసాగించండి',
  adminOversightDashboard: 'పర్యవేక్షణ Dashboard',
  adminGrievanceIntelligence: 'ఫిర్యాదు ఇంటెలిజెన్స్',
  adminAllDistricts: 'అన్ని జిల్లాలు',
  adminExit: 'నిష్క్రమించండి',
  adminStatusDistribution: 'స్థితి పంపిణీ',
  adminByCategory: 'వర్గం వారీగా ఫిర్యాదులు',
  adminDistrictBreakdown: 'జిల్లా విశ్లేషణ',
  adminRecentGrievances: 'ఇటీవలి ఫిర్యాదులు',
  adminTotalGrievances: 'మొత్తం ఫిర్యాదులు',
  adminOpen: 'తెరిచిన',
  adminNoGrievances: 'ఈ వీక్షణలో ఫిర్యాదులు లేవు.',
  adminAiSummary: 'AI అంశ సారాంశం',
  adminAiNone: 'ఈ వీక్షణ కోసం ఫిర్యాదులు నమోదు చేయబడలేదు.',
  adminPosDm: 'జిల్లా మేజిస్ట్రేట్',
  adminPosBdo: 'బ్లాక్ డెవలప్‌మెంట్ అధికారి',
  adminPosPanchayat: 'పంచాయతీ కార్యదర్శి',
  adminPosWelfare: 'సంక్షేమ అధికారి',
  adminPosAudit: 'సామాజిక ఆడిట్ కోఆర్డినేటర్',
  adminPosState: 'రాష్ట్ర నోడల్ అధికారి',
  adminPosManager: 'ప్రోగ్రామ్ మేనేజర్',
  // common
  commonSubmit: 'సమర్పించండి',
  commonCancel: 'రద్దు చేయండి',
  commonLoading: 'లోడ్ అవుతోంది…',
}
