export const _ur = {
  // nav
  navFeatures: 'خصوصیات',
  navOversight: 'نگرانی',
  navSignIn: 'سائن ان',
  // hero
  heroBadge: 'فلاحی پالیسی کا نفاذ',
  heroTitle1: 'درستگی پر مبنی حکمرانی۔',
  heroTitle2: 'ازسرِ نو تشکیل۔',
  heroSubtitle: 'ایک محفوظ، شہری اول پلیٹ فارم جہاں حقیقی وقت کا ڈیٹا، غیر مرکزی شناخت، اور براہ راست منتقلیاں فلاحی فوائد بالکل صحیح افراد تک پہنچاتی ہیں۔',
  heroCta: 'اپنا ڈیش بورڈ کھولیں',
  // features
  featuresBadge: 'صلاحیتیں',
  featuresTitle: 'ایک جدید فلاحی نظام کو جو کچھ درکار ہے، یہ سب کچھ۔',
  featuresSubtitle: 'ایک مربوط پلیٹ فارم شناخت، ہدف بندی، ادائیگی، اور جوابدہی کو یکجا کرتا ہے۔',
  tileDynamicRegistries: 'متحرک سماجی و معاشی رجسٹریز',
  tileDynamicRegistriesDesc: 'ٹیکس، یوٹیلیٹی، اور سول ریکارڈز سے مسلسل اہلیت کی تازہ کاری — ہدف بندی جو ہمیشہ حقیقت کی عکاسی کرتی ہے، کبھی پرانی مردم شماری نہیں۔',
  tileBiometrics: 'غیر مرکزی بائیو میٹرکس',
  tileBiometricsDesc: 'محفوظ، غیر مرکزی بائیو میٹرک آئی ڈیز جو دروازے پر ہی شناختی دھوکہ دہی اور دوہرے فائدے کو روک دیتی ہیں۔',
  tileDbt: 'براہ راست فائدہ منتقلیاں (DBT)',
  tileDbtDesc: 'نقد رقم اور سبسڈیز براہ راست تصدیق شدہ شہری اکاؤنٹس میں — کوئی درمیانی شخص نہیں۔',
  tileConditional: 'مشروط منتقلیاں',
  tileConditionalDesc: 'ادائیگیاں تعلیم اور صحت کی منزلوں سے وابستہ تاکہ ماپنے کے قابل سماجی نتائج حاصل ہوں۔',
  tileAudits: 'کمیونٹی سماجی آڈٹ',
  tileAuditsDesc: 'عوامی مجلسیں جہاں شہری زمین پر موجود اثاثوں کے مقابلے میں خرچ کا جائزہ لیتے ہیں۔',
  tileAi: 'خودکار استثنیٰ رپورٹس',
  tileAiDesc: 'اے آئی مشتبہ پیٹرنز کی نشاندہی کرتا ہے — جیسے ایک ہی فون نمبر متعدد فائدہ کے اکاؤنٹس سے منسلک ہو — فوری تفتیش کے لیے۔',
  // oversight
  oversightBadge: 'وزارتِ نگرانی',
  oversightTitle: 'وزارت کا فریم ورک اور بنیادی ڈھانچہ',
  oversightSubtitle: 'وزارتیں قانونی فریم ورک قائم کر کے، نگرانی کے بجٹ مختص کر کے، محفوظ ڈیٹا سسٹمز برقرار رکھ کر، اور جرمانے نافذ کر کے فلاحی پالیسی کے آڈٹ کی نگرانی کرتی ہیں۔',
  pillarAudit: 'لازمی آڈٹ گائیڈ لائنز',
  pillarAuditDesc: 'معیاری آپریٹنگ طریقہ کار اور قانونی فریم ورک جو سماجی اور مالیاتی آڈٹ کو لازمی بناتے ہیں۔',
  pillarMetrics: 'واضح کارکردگی کے پیمانے',
  pillarMetricsDesc: 'ماپنے کے قابل معیارات — جیسے قد میں رکاوٹ یا بے روزگاری میں مخصوص کمی کی شرحیں۔',
  pillarBodies: 'آزاد ادارے',
  pillarBodiesDesc: 'تھرڈ پارٹی آڈٹرز اور مقامی سماجی آڈٹ یونٹس کے لیے سیاسی مداخلت کے خلاف قانونی تحفظ۔',
  pillarDatabases: 'محفوظ ماسٹر ڈیٹا بیس',
  pillarDatabasesDesc: 'مرکزی مستفیدین کی رجسٹریز صاف ڈیٹا کے ساتھ، جن تک صرف مجاز آڈٹ ایجنسیز ہی رسائی حاصل کر سکیں۔',
  // footer
  footerTagline: 'عوام اول پالیسی کے لیے درستگی پر مبنی حکمرانی۔',
  footerSub: 'متحرک رجسٹریز · غیر مرکزی بائیو میٹرکس · براہ راست فائدہ منتقلیاں',
  // login
  loginTitle: 'خوش آمدید واپس',
  loginSubtitle: 'اپنا محفوظ شہری ڈیش بورڈ کھولنے کے لیے سائن ان کریں۔ نئے شہریوں کی اندراج دو منٹ سے کم میں ہو جاتی ہے۔',
  loginContinueGoogle: 'Google کے ساتھ جاری رکھیں',
  loginContinueDemo: 'ڈیمو اکاؤنٹ کے ساتھ جاری رکھیں',
  loginDemoHint: 'ڈیمو اکاؤنٹ',
  loginPresetLabel: 'ایک ڈیمو شہری کو فوری بھریں:',
  loginOrUse: 'یا اپنی تفصیلات استعمال کریں',
  loginEmail: 'ای میل',
  loginName: 'نام',
  loginImage: 'تصویر کا URL',
  // verify
  verifyStepAadhaar: 'Aadhaar',
  verifyStepOtp: 'OTP',
  verifyTitle: 'اپنا Aadhaar تصدیق کریں',
  verifySubtitle: 'ایک بار کی شناختی تصدیق آپ کا فلاحی ڈیش بورڈ کھول دیتی ہے۔',
  verifyAadhaarLabel: '12 ہندسوں کا Aadhaar نمبر',
  verifyMobileLabel: 'OTP وصول کرنے کا موبائل نمبر',
  verifyGenerateOtp: 'OTP بنائیں',
  verifySendingOtp: 'OTP بھیجا جا رہا ہے…',
  verifyDemoNote: 'ڈیمو موڈ — OTP کی درخواست کی تقلید کی جا رہی ہے۔ کوئی حقیقی Aadhaar ڈیٹا منتقل نہیں ہوتا۔',
  verifyOtpSentTo: 'OTP آپ کے رجسٹرڈ موبائل نمبر پر بھیجا گیا',
  verifyDemoOtpLabel: 'ڈیمو OTP:',
  verifyDemoOtpNote: 'اصل تعیناتی میں یہ SMS کے ذریعے بھیجا جاتا ہے — ٹیسٹنگ کے لیے یہاں دکھایا گیا ہے۔',
  verifyOtpLabel: '6 ہندسوں کا OTP',
  verifyVerifyOtp: 'OTP تصدیق کریں',
  verifyVerifying: 'تصدیق ہو رہی ہے…',
  verifyChangeAadhaar: 'Aadhaar نمبر تبدیل کریں',
  verifyIdentityVerified: 'شناخت تصدیق شدہ',
  verifyRedirecting: 'آپ کے ڈیش بورڈ پر بھیجا جا رہا ہے…',
  verifyInvalidAadhaar: 'براہ کرم ایک درست 12 ہندسوں کا Aadhaar نمبر درج کریں۔',
  verifyInvalidOtp: 'براہ کرم اپنے فون پر بھیجا گیا 6 ہندسوں کا OTP درج کریں۔',
  verifyInvalidMobile: 'براہ کرم ایک درست 10 ہندسوں کا موبائل نمبر درج کریں۔',
  verifyFailedGenerate: 'OTP بنانے میں ناکامی۔',
  verifyFailedVerify: 'تصدیق ناکام ہو گئی۔ براہ کرم دوبارہ کوشش کریں۔',
  verifySpeakHint: 'مائیک پر ٹیپ کریں اور اپنا Aadhaar یا OTP بولیں',
  // dashboard
  dashWelcome: 'خوش آمدید',
  dashCitizen: 'شہری',
  dashVerified: 'تصدیق کی حیثیت: تصدیق شدہ',
  dashPending: 'تصدیق کی حیثیت: زیر التواء',
  dashVerifyAadhaar: 'Aadhaar تصدیق کریں',
  dashAadhaar: 'Aadhaar',
  dashSignOut: 'سائن آؤٹ',
  dashFoodSubsidy: 'خوراک سبسڈی (PDS)',
  dashDbt: 'براہ راست فائدہ منتقلی (DBT)',
  dashEducation: 'تعلیمی گرانٹ',
  dashHealth: 'صحت کوریج',
  dashNotEnrolled: 'رجسٹرڈ نہیں',
  dashNextSocialAudit: 'اگلا سماجی آڈٹ',
  dashSocialAuditDesc: 'آپ کے گاؤں کا عوامی اخراجات کا جائزہ — تمام رہائشیوں کے لیے کھلا۔',
  // admin
  adminAccess: 'ایڈمن رسائی',
  adminOversightPortal: 'وزارت نگرانی پورٹل',
  adminAccessPassword: 'رسائی کا پاس ورڈ',
  adminEnterPortal: 'پورٹل میں داخل ہوں',
  adminIncorrect: 'غلط پاس ورڈ۔ دوبارہ کوشش کریں۔',
  adminDemoPassword: 'ڈیمو پاس ورڈ:',
  adminRegistration: 'سرکاری رجسٹریشن',
  adminRegisterDesc: 'شکایت ڈیش بورڈ تک رسائی کے لیے اپنا نگرانی کا کردار رجسٹر کریں۔',
  adminFullName: 'پورا نام',
  adminEmail: 'سرکاری ای میل',
  adminPhone: 'فون',
  adminPosition: 'عہدہ',
  adminState: 'ریاست',
  adminDistrict: 'ضلع',
  adminSelectState: 'ریاست منتخب کریں',
  adminSelectDistrict: 'ضلع منتخب کریں',
  adminRegisterContinue: 'رجسٹر کریں اور جاری رکھیں',
  adminOversightDashboard: 'نگرانی ڈیش بورڈ',
  adminGrievanceIntelligence: 'شکایت انٹیلی جنس',
  adminAllDistricts: 'تمام اضلاع',
  adminExit: 'باہر نکلیں',
  adminStatusDistribution: 'حیثیت کی تقسیم',
  adminByCategory: 'زمرہ وار شکایات',
  adminDistrictBreakdown: 'ضلع وار تفصیل',
  adminRecentGrievances: 'حالیہ شکایات',
  adminTotalGrievances: 'کل شکایات',
  adminOpen: 'کھلا',
  adminNoGrievances: 'اس منظر میں کوئی شکایت نہیں۔',
  adminAiSummary: 'اے آئی موضوع خلاصہ',
  adminAiNone: 'اس منظر کے لیے کوئی شکایت ریکارڈ نہیں۔',
  adminPosDm: 'ضلعی مجسٹریٹ',
  adminPosBdo: 'بلاک ڈویلپمنٹ آفیسر',
  adminPosPanchayat: 'پنچایت سیکرٹری',
  adminPosWelfare: 'فلاحی آفیسر',
  adminPosAudit: 'سماجی آڈٹ کوآرڈینیٹر',
  adminPosState: 'ریاستی نوڈل آفیسر',
  adminPosManager: 'پروگرام منیجر',
  // common
  commonSubmit: 'جمع کریں',
  commonCancel: 'منسوخ کریں',
  commonLoading: 'لوڈ ہو رہا ہے…',
}
